/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UINavigationController.h>


@interface CustomNavigationBarController : UINavigationController {
}
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
- (unsigned)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (void)viewDidUnload;
@end

