/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import </libobjc.A.h>

@class UIView, UIViewController;

@interface FacebookiOSGLSocialLib : NSObject {
	UIViewController *socialViewController;	// 4 = 0x4
	BOOL valueHandleOpenUrl;	// 8 = 0x8
	BOOL isLoggedIn;	// 9 = 0x9
	UIView *gameView;	// 12 = 0xc
}
@property(retain, nonatomic) UIView *gameView;	// @synthesize
@property(assign, nonatomic) BOOL isLoggedIn;	// @synthesize
@property(assign, nonatomic) BOOL valueHandleOpenUrl;	// @synthesize
+ (void)didBecomeActive;
+ (void)load;
- (void)CallPendingRequest;
- (void)CheckPublishPermissions:(id)permissions andCallRequestPermissionIfNeeded:(BOOL)needed;
- (id)HasPermission:(id)permission fromResult:(id)result andError:(id)error;
- (BOOL)ParseAppResponse:(id)response FromRequest:(SNSRequestState *)request;
- (BOOL)ParseAvatarResponse:(id)response FromRequest:(SNSRequestState *)request;
- (BOOL)ParseChangeScoreResponse:(id)response FromRequest:(SNSRequestState *)request;
- (BOOL)ParseFriendsDataResponse:(id)response FromRequest:(SNSRequestState *)request;
- (BOOL)ParseFriendsResponse:(id)response FromRequest:(SNSRequestState *)request;
- (BOOL)ParseGetUserAchievements:(id)achievements FromRequest:(SNSRequestState *)request;
- (BOOL)ParseScoreResponse:(id)response FromRequest:(SNSRequestState *)request;
- (BOOL)ParseUserData:(id)data FromRequest:(SNSRequestState *)request;
- (BOOL)ParseUserLikesResponse:(id)response FromRequest:(SNSRequestState *)request;
- (BOOL)ParseUserNamesResponse:(id)response FromRequest:(SNSRequestState *)request;
- (void)RequestPublishPermissions;
- (void)customRequest:(id)request andParams:(id)params andHttpMethod:(id)method;
- (void)dealloc;
- (void)dialogCompleteWithUrl:(id)url;
- (void)facebookiOSGLSocialLib_checkLoginDelegateWithState:(int)state;
- (void)facebookiOSGLSocialLib_getResponseWithId:(id)anId andError:(id)error;
- (void)facebookiOSGLSocialLib_isLoggedIn;
// declared property getter: - (id)gameView;
- (void)handleOpenURL:(id)url;
// declared property getter: - (BOOL)isLoggedIn;
- (id)parseURLParams:(id)params;
- (void)sendRequest:(id)request;
- (void)sessionStateChanged:(id)changed state:(int)state error:(id)error isFirstRequest:(BOOL)request;
- (void)setError:(id)error fromRequest:(SNSRequestState *)request;
- (void)setErrorForRequest:(SNSRequestState *)request andMessage:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)message;
// declared property setter: - (void)setGameView:(id)view;
// declared property setter: - (void)setIsLoggedIn:(BOOL)anIn;
// declared property setter: - (void)setValueHandleOpenUrl:(BOOL)url;
// declared property getter: - (BOOL)valueHandleOpenUrl;
@end

