/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray;

@interface FBAppBridgeTypeToJSONConverter : NSObject {
	NSMutableArray *_createdPasteboardNames;	// 4 = 0x4
}
@property(retain, nonatomic) NSMutableArray *createdPasteboardNames;	// @synthesize=_createdPasteboardNames
+ (id)appBridgeTypeFromJSON:(id)json;
- (id)convertedArrayFromArray:(id)array convertingToJSON:(BOOL)json;
- (id)convertedDictionaryFromDictionary:(id)dictionary convertingToJSON:(BOOL)json;
- (id)convertedObjectFromObject:(id)object convertingToJSON:(BOOL)json;
// declared property getter: - (id)createdPasteboardNames;
- (void)dealloc;
- (id)dictionaryWithAppBridgeTypesFromJSONDictionary:(id)jsondictionary;
- (id)jsonDictionaryFromDictionaryWithAppBridgeTypes:(id)appBridgeTypes;
- (id)jsonFromData:(id)data tag:(id)tag;
// declared property setter: - (void)setCreatedPasteboardNames:(id)names;
@end

