/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class FBAppBridgeTypeToJSONConverter, NSString, NSMutableDictionary;

@interface FBAppBridge : NSObject {
	NSMutableDictionary *_pendingAppCalls;	// 4 = 0x4
	NSMutableDictionary *_callbacks;	// 8 = 0x8
	FBAppBridgeTypeToJSONConverter *_jsonConverter;	// 12 = 0xc
	NSString *_appID;	// 16 = 0x10
	NSString *_bundleID;	// 20 = 0x14
	NSString *_appName;	// 24 = 0x18
}
@property(copy, nonatomic) NSString *appID;	// @synthesize=_appID
@property(copy, nonatomic) NSString *appName;	// @synthesize=_appName
@property(copy, nonatomic) NSString *bundleID;	// @synthesize=_bundleID
@property(retain, nonatomic) NSMutableDictionary *callbacks;	// @synthesize=_callbacks
@property(retain, nonatomic) FBAppBridgeTypeToJSONConverter *jsonConverter;	// @synthesize=_jsonConverter
@property(retain, nonatomic) NSMutableDictionary *pendingAppCalls;	// @synthesize=_pendingAppCalls
+ (id)appIconFromBundleInfo:(id)bundleInfo;
+ (id)errorFromDictionary:(id)dictionary;
+ (id)installedFBNativeAppVersionForMethod:(id)method minVersion:(id)version;
+ (id)sharedInstance;
+ (id)symmetricKeyAndForceRefresh:(BOOL)refresh;
+ (id)urlForMethod:(id)method queryParams:(id)params version:(id)version;
- (id)init;
- (void)addAppMetadataToDictionary:(id)dictionary;
// declared property getter: - (id)appID;
// declared property getter: - (id)appName;
// declared property getter: - (id)bundleID;
// declared property getter: - (id)callbacks;
- (void)dealloc;
- (id)decryptUrlQueryParams:(id)params method:(id)method fallbackHandler:(id)handler;
- (void)deletePasteboardsForAppCallID:(id)appCallID;
- (id)dictionaryFromJSONString:(id)jsonstring;
- (void)dispatchDialogAppCall:(id)call version:(id)version session:(id)session completionHandler:(id)handler;
- (void)handleDidBecomeActive;
- (BOOL)handleOpenURL:(id)url sourceApplication:(id)application session:(id)session fallbackHandler:(id)handler;
- (void)invoke:(id)invoke forFailedAppCall:(id)failedAppCall withMessage:(id)message;
// declared property getter: - (id)jsonConverter;
- (id)jsonStringFromDictionary:(id)dictionary;
// declared property getter: - (id)pendingAppCalls;
- (void)performDialogAppCall:(id)call version:(id)version session:(id)session completionHandler:(id)handler;
- (BOOL)processResponse:(id)response method:(id)method session:(id)session fallbackHandler:(id)handler;
- (void)savePasteboardNames:(id)names forAppCallID:(id)appCallID;
// declared property setter: - (void)setAppID:(id)anId;
// declared property setter: - (void)setAppName:(id)name;
// declared property setter: - (void)setBundleID:(id)anId;
// declared property setter: - (void)setCallbacks:(id)callbacks;
// declared property setter: - (void)setJsonConverter:(id)converter;
// declared property setter: - (void)setPendingAppCalls:(id)calls;
- (void)stopTrackingCallWithID:(id)anId;
- (void)trackAppCall:(id)call withCompletionHandler:(id)completionHandler;
@end

