/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import </libobjc.A.h>
#import "NSCacheDelegate.h"

@class NSCache;
@protocol FBCacheIndexFileDelegate;

@interface FBCacheIndex : NSObject <NSCacheDelegate> {
	id<FBCacheIndexFileDelegate> _delegate;	// 4 = 0x4
	NSCache *_cachedEntries;	// 8 = 0x8
	unsigned _currentDiskUsage;	// 12 = 0xc
	unsigned _diskCapacity;	// 16 = 0x10
	sqlite3 *_database;	// 20 = 0x14
	sqlite3_stmt *_insertStatement;	// 24 = 0x18
	sqlite3_stmt *_removeByKeyStatement;	// 28 = 0x1c
	sqlite3_stmt *_selectByKeyStatement;	// 32 = 0x20
	sqlite3_stmt *_selectByKeyFragmentStatement;	// 36 = 0x24
	sqlite3_stmt *_selectExcludingKeyFragmentStatement;	// 40 = 0x28
	sqlite3_stmt *_trimStatement;	// 44 = 0x2c
	sqlite3_stmt *_updateStatement;	// 48 = 0x30
	dispatch_queue_s *_databaseQueue;	// 52 = 0x34
}
@property(readonly, assign, nonatomic) unsigned currentDiskUsage;	// @synthesize=_currentDiskUsage
@property(readonly, assign, nonatomic) dispatch_queue_s *databaseQueue;	// @synthesize=_databaseQueue
@property(assign) id delegate;	// @synthesize=_delegate
@property(assign, nonatomic) unsigned diskCapacity;	// @synthesize=_diskCapacity
@property(assign, nonatomic) unsigned entryCacheCountLimit;
- (id)initWithCacheFolder:(id)cacheFolder;
- (id)_createCacheEntityInfo:(sqlite3_stmt *)info;
- (void)_dropTrimmingTable;
- (id)_entryForKey:(id)key;
- (void)_fetchCurrentDiskUsage;
- (void)_flushOrphanedFiles;
- (id)_readEntriesFromDatabase:(id)database excludingFragment:(BOOL)fragment;
- (id)_readEntryFromDatabase:(id)database;
- (void)_removeEntryFromDatabaseForKey:(id)key;
- (void)_trimDatabase;
- (void)_updateEntryInDatabaseForKey:(id)key entry:(id)entry;
- (void)_writeEntryInDatabase:(id)database;
- (void)cache:(id)cache willEvictObject:(id)object;
// declared property getter: - (unsigned)currentDiskUsage;
// declared property getter: - (dispatch_queue_s *)databaseQueue;
- (void)dealloc;
// declared property getter: - (id)delegate;
// declared property getter: - (unsigned)diskCapacity;
// declared property getter: - (unsigned)entryCacheCountLimit;
- (id)fileNameForKey:(id)key;
- (void)removeEntries:(id)entries excludingFragment:(BOOL)fragment;
- (void)removeEntryForKey:(id)key;
// declared property setter: - (void)setDelegate:(id)delegate;
// declared property setter: - (void)setDiskCapacity:(unsigned)capacity;
// declared property setter: - (void)setEntryCacheCountLimit:(unsigned)limit;
- (id)storeFileForKey:(id)key withData:(id)data;
@end

