/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBCacheIndexFileDelegate <NSObject>
- (void)cacheIndex:(id)index deleteFileWithName:(id)name;
- (void)cacheIndex:(id)index writeFileWithName:(id)name data:(id)data;
@end

