/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSDictionary;

@interface FBDialogsData : NSObject {
	NSString *_method;	// 4 = 0x4
	NSDictionary *_arguments;	// 8 = 0x8
	NSDictionary *_clientState;	// 12 = 0xc
	NSDictionary *_results;	// 16 = 0x10
}
@property(copy, nonatomic) NSDictionary *arguments;	// @synthesize=_arguments
@property(copy, nonatomic) NSDictionary *clientState;	// @synthesize=_clientState
@property(copy, nonatomic) NSString *method;	// @synthesize=_method
@property(copy, nonatomic) NSDictionary *results;	// @synthesize=_results
- (id)initWithMethod:(id)method arguments:(id)arguments;
// declared property getter: - (id)arguments;
// declared property getter: - (id)clientState;
- (void)dealloc;
- (id)description;
- (BOOL)isValid;
// declared property getter: - (id)method;
// declared property getter: - (id)results;
// declared property setter: - (void)setArguments:(id)arguments;
// declared property setter: - (void)setClientState:(id)state;
// declared property setter: - (void)setMethod:(id)method;
// declared property setter: - (void)setResults:(id)results;
@end

