/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FBDialogDelegate <NSObject>
@optional
- (void)dialog:(id)dialog didFailWithError:(id)error;
- (BOOL)dialog:(id)dialog shouldOpenURLInExternalBrowser:(id)externalBrowser;
- (void)dialogCompleteWithUrl:(id)url;
- (void)dialogDidComplete:(id)dialog;
- (void)dialogDidNotComplete:(id)dialog;
- (void)dialogDidNotCompleteWithUrl:(id)dialog;
@end

