/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "ModernCombat5-Structs.h"


@interface FBDynamicFrameworkLoader : NSObject {
}
+ (id)frameworkPathTemplate;
+ (Class)loadClass:(id)aClass withFramework:(id)framework;
+ (id)loadStringConstant:(id)constant withFramework:(id)framework;
+ (void *)loadSymbol:(id)symbol withFramework:(id)framework;
+ (SecRandom *)loadkSecRandomDefault;
+ (void)setFrameworkPathTemplate:(id)aTemplate;
+ (void)setSqlitePath:(id)path;
+ (id)sqlitePath;
@end

