/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBErrorUtility : NSObject {
}
+ (int)errorCategoryForError:(id)error;
+ (int)fberrorCategoryFromError:(id)error code:(int)code subcode:(int)subcode returningUserMessage:(id *)message andShouldNotifyUser:(BOOL *)anAnd;
+ (id)fberrorForRetry:(id)retry;
+ (id)fberrorForSystemPasswordChange:(id)systemPasswordChange;
+ (void)fberrorGetCodeValueForError:(id)error index:(unsigned)index code:(int *)code subcode:(int *)subcode;
+ (BOOL)fberrorIsErrorFromSystemSession:(id)systemSession;
+ (BOOL)shouldNotifyUserForError:(id)error;
+ (id)userMessageForError:(id)error;
@end

