/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface FBFetchedAppSettings : NSObject {
	BOOL _supportsAttribution;	// 4 = 0x4
	BOOL _supportsImplicitSdkLogging;	// 5 = 0x5
	BOOL _suppressNativeGdp;	// 6 = 0x6
	NSString *_serverAppName;	// 8 = 0x8
	NSString *_appID;	// 12 = 0xc
}
@property(retain, nonatomic) NSString *appID;	// @synthesize=_appID
@property(copy, nonatomic) NSString *serverAppName;	// @synthesize=_serverAppName
@property(assign) BOOL supportsAttribution;	// @synthesize=_supportsAttribution
@property(assign) BOOL supportsImplicitSdkLogging;	// @synthesize=_supportsImplicitSdkLogging
@property(assign) BOOL suppressNativeGdp;	// @synthesize=_suppressNativeGdp
- (id)init;
- (id)initWithAppID:(id)appID;
// declared property getter: - (id)appID;
- (void)dealloc;
// declared property getter: - (id)serverAppName;
// declared property setter: - (void)setAppID:(id)anId;
// declared property setter: - (void)setServerAppName:(id)name;
// declared property setter: - (void)setSupportsAttribution:(BOOL)attribution;
// declared property setter: - (void)setSupportsImplicitSdkLogging:(BOOL)logging;
// declared property setter: - (void)setSuppressNativeGdp:(BOOL)gdp;
// declared property getter: - (BOOL)supportsAttribution;
// declared property getter: - (BOOL)supportsImplicitSdkLogging;
// declared property getter: - (BOOL)suppressNativeGdp;
@end

