/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBImageResourceLoader : NSObject {
}
+ (id)imageFromBytes:(const char *)bytes length:(unsigned)length fromRetinaBytes:(const char *)retinaBytes retinaLength:(unsigned)length4;
+ (id)imageNamed:(id)named fromBytes:(const char *)bytes length:(unsigned)length fromRetinaBytes:(const char *)retinaBytes retinaLength:(unsigned)length5;
+ (id)loadImageFromBytes:(const char *)bytes length:(unsigned)length scale:(float)scale;
@end

