/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBDialogsParams.h"

@class FBSession, NSArray;

@interface FBLoginDialogParams : FBDialogsParams {
	BOOL _isRefreshOnly;	// 4 = 0x4
	NSArray *_permissions;	// 8 = 0x8
	int _writePrivacy;	// 12 = 0xc
	FBSession *_session;	// 16 = 0x10
}
@property(assign) BOOL isRefreshOnly;	// @synthesize=_isRefreshOnly
@property(copy, nonatomic) NSArray *permissions;	// @synthesize=_permissions
@property(retain, nonatomic) FBSession *session;	// @synthesize=_session
@property(assign, nonatomic) int writePrivacy;	// @synthesize=_writePrivacy
- (id)appBridgeVersion;
- (void)dealloc;
- (id)dictionaryMethodArgs;
// declared property getter: - (BOOL)isRefreshOnly;
// declared property getter: - (id)permissions;
// declared property getter: - (id)session;
// declared property setter: - (void)setIsRefreshOnly:(BOOL)only;
// declared property setter: - (void)setPermissions:(id)permissions;
// declared property setter: - (void)setSession:(id)session;
// declared property setter: - (void)setWritePrivacy:(int)privacy;
// declared property getter: - (int)writePrivacy;
@end

