/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBDialog.h"

@protocol FBLoginDialogDelegate;

@interface FBLoginDialog : FBDialog {
	id<FBLoginDialogDelegate> _loginDelegate;	// 96 = 0x60
}
- (id)initWithURL:(id)url loginParams:(id)params delegate:(id)delegate;
- (void)dialogDidCancel:(id)dialog;
- (void)dialogDidSucceed:(id)dialog;
- (void)webView:(id)view didFailLoadWithError:(id)error;
@end

