/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSMutableString;

@interface FBLogger : NSObject {
	BOOL _isActive;	// 4 = 0x4
	NSMutableString *_internalContents;	// 8 = 0x8
	NSString *_loggingBehavior;	// 12 = 0xc
	unsigned _loggerSerialNumber;	// 16 = 0x10
}
@property(copy, nonatomic) NSString *contents;
@property(readonly, assign, nonatomic) NSMutableString *internalContents;	// @synthesize=_internalContents
@property(readonly, assign, nonatomic) BOOL isActive;	// @synthesize=_isActive
@property(readonly, assign, nonatomic) unsigned loggerSerialNumber;	// @synthesize=_loggerSerialNumber
@property(readonly, assign, nonatomic) NSString *loggingBehavior;	// @synthesize=_loggingBehavior
+ (unsigned)newSerialNumber;
+ (void)registerCurrentTime:(id)time withTag:(id)tag;
+ (void)registerStringToReplace:(id)replace replaceWith:(id)with;
+ (void)singleShotLogEntry:(id)entry formatString:(id)string;
+ (void)singleShotLogEntry:(id)entry logEntry:(id)entry2;
+ (void)singleShotLogEntry:(id)entry timestampTag:(id)tag formatString:(id)string;
- (id)initWithLoggingBehavior:(id)loggingBehavior;
- (void)appendFormat:(id)format;
- (void)appendKey:(id)key value:(id)value;
- (void)appendString:(id)string;
// declared property getter: - (id)contents;
- (void)dealloc;
- (void)emitToNSLog;
// declared property getter: - (id)internalContents;
// declared property getter: - (BOOL)isActive;
// declared property getter: - (unsigned)loggerSerialNumber;
// declared property getter: - (id)loggingBehavior;
// declared property setter: - (void)setContents:(id)contents;
@end

