/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBNativeDialogs : NSObject {
}
+ (BOOL)canPresentShareDialogWithSession:(id)session;
+ (id)handlerFromHandler:(id)handler;
+ (BOOL)presentShareDialogModallyFrom:(id)from initialText:(id)text image:(id)image url:(id)url handler:(id)handler;
+ (BOOL)presentShareDialogModallyFrom:(id)from initialText:(id)text images:(id)images urls:(id)urls handler:(id)handler;
+ (BOOL)presentShareDialogModallyFrom:(id)from session:(id)session initialText:(id)text images:(id)images urls:(id)urls handler:(id)handler;
@end

