/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBDialogsParams.h"

@class NSString;
@protocol FBOpenGraphAction;

@interface FBOpenGraphActionShareDialogParams : FBDialogsParams {
	id<FBOpenGraphAction> _action;	// 4 = 0x4
	NSString *_previewPropertyName;	// 8 = 0x8
	NSString *_actionType;	// 12 = 0xc
}
@property(retain, nonatomic) id<FBOpenGraphAction> action;	// @synthesize=_action
@property(copy, nonatomic) NSString *actionType;	// @synthesize=_actionType
@property(copy, nonatomic) NSString *previewPropertyName;	// @synthesize=_previewPropertyName
+ (id)getIdOrUrlFromObject:(id)object;
+ (id)getPostedObjectTypeFromObject:(id)object;
// declared property getter: - (id)action;
// declared property getter: - (id)actionType;
- (id)appBridgeVersion;
- (BOOL)containsUIImages:(id)images;
- (void)dealloc;
- (id)dictionaryMethodArgs;
- (id)flattenGraphObjects:(id)objects;
- (id)flattenObject:(id)object;
// declared property getter: - (id)previewPropertyName;
// declared property setter: - (void)setAction:(id)action;
// declared property setter: - (void)setActionType:(id)type;
// declared property setter: - (void)setPreviewPropertyName:(id)name;
- (id)validate;
@end

