/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAlertViewDelegate.h"
#import </libobjc.A.h>


@interface FBRequestConnectionRetryManagerAlertViewHelper : NSObject <UIAlertViewDelegate> {
	id _callback;	// 4 = 0x4
}
@property(copy, nonatomic) id callback;	// @synthesize=_callback
- (void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
// declared property getter: - (id)callback;
- (void)dealloc;
// declared property setter: - (void)setCallback:(id)callback;
- (void)show:(id)show message:(id)message cancelButtonTitle:(id)title handler:(id)handler;
@end

