/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "ModernCombat5-Structs.h"

@class NSMutableArray, FBRequestConnectionRetryManager, FBRequest, FBLogger, FBURLConnection, NSMutableURLRequest, NSHTTPURLResponse;

@interface FBRequestConnection : NSObject {
	BOOL _errorBehavior;	// 4 = 0x4
	BOOL _isResultFromCache;	// 5 = 0x5
	NSHTTPURLResponse *_urlResponse;	// 8 = 0x8
	FBURLConnection *_connection;	// 12 = 0xc
	NSMutableArray *_requests;	// 16 = 0x10
	int _state;	// 20 = 0x14
	NSMutableURLRequest *_internalUrlRequest;	// 24 = 0x18
	FBRequest *_deprecatedRequest;	// 28 = 0x1c
	FBLogger *_logger;	// 32 = 0x20
	unsigned long _requestStartTime;	// 36 = 0x24
	FBRequestConnectionRetryManager *_retryManager;	// 40 = 0x28
	double _timeout;	// 44 = 0x2c
}
@property(retain, nonatomic) FBURLConnection *connection;	// @synthesize=_connection
@property(retain, nonatomic) FBRequest *deprecatedRequest;	// @synthesize=_deprecatedRequest
@property(assign, nonatomic) int errorBehavior;
@property(retain, nonatomic) NSMutableURLRequest *internalUrlRequest;	// @synthesize=_internalUrlRequest
@property(readonly, assign, nonatomic) BOOL isResultFromCache;	// @synthesize=_isResultFromCache
@property(retain, nonatomic) FBLogger *logger;	// @synthesize=_logger
@property(assign, nonatomic) unsigned long requestStartTime;	// @synthesize=_requestStartTime
@property(retain, nonatomic) NSMutableArray *requests;	// @synthesize=_requests
@property(retain, nonatomic) FBRequestConnectionRetryManager *retryManager;	// @synthesize=_retryManager
@property(assign, nonatomic) int state;	// @synthesize=_state
@property(assign, nonatomic) double timeout;	// @synthesize=_timeout
@property(retain, nonatomic) NSMutableURLRequest *urlRequest;
@property(retain, nonatomic) NSHTTPURLResponse *urlResponse;	// @synthesize=_urlResponse
+ (void)addRequestToExtendTokenForSession:(id)session connection:(id)connection;
+ (void)addRequestToRefreshPermissionsSession:(id)refreshPermissionsSession connection:(id)connection;
+ (void)processGraphObject:(id)object forPath:(id)path withAction:(id)action;
+ (void)processGraphObjectPropertyKey:(id)key value:(id)value action:(id)action passByValue:(BOOL)value4;
+ (id)startForCustomAudienceThirdPartyID:(id)customAudienceThirdPartyID completionHandler:(id)handler;
+ (id)startForDeleteObject:(id)deleteObject completionHandler:(id)handler;
+ (id)startForMeWithCompletionHandler:(id)completionHandler;
+ (id)startForMyFriendsWithCompletionHandler:(id)completionHandler;
+ (id)startForPlacesSearchAtCoordinate:(XXStruct_UNJ7RC)coordinate radiusInMeters:(int)meters resultsLimit:(int)limit searchText:(id)text completionHandler:(id)handler;
+ (id)startForPostOpenGraphObject:(id)postOpenGraphObject completionHandler:(id)handler;
+ (id)startForPostOpenGraphObjectWithType:(id)type title:(id)title image:(id)image url:(id)url description:(id)description objectProperties:(id)properties completionHandler:(id)handler;
+ (id)startForPostStatusUpdate:(id)postStatusUpdate completionHandler:(id)handler;
+ (id)startForPostStatusUpdate:(id)postStatusUpdate place:(id)place tags:(id)tags completionHandler:(id)handler;
+ (id)startForPostWithGraphPath:(id)graphPath graphObject:(id)object completionHandler:(id)handler;
+ (id)startForUpdateOpenGraphObject:(id)updateOpenGraphObject completionHandler:(id)handler;
+ (id)startForUpdateOpenGraphObjectWithId:(id)anId title:(id)title image:(id)image url:(id)url description:(id)description objectProperties:(id)properties completionHandler:(id)handler;
+ (id)startForUploadPhoto:(id)uploadPhoto completionHandler:(id)handler;
+ (id)startForUploadStagingResourceWithImage:(id)image completionHandler:(id)handler;
+ (id)startWithGraphPath:(id)graphPath completionHandler:(id)handler;
+ (id)startWithGraphPath:(id)graphPath parameters:(id)parameters HTTPMethod:(id)method completionHandler:(id)handler;
+ (id)userAgent;
- (id)init;
- (id)initWithMetadata:(id)metadata;
- (id)initWithTimeout:(double)timeout;
- (void)addPiggybackRequests;
- (void)addRequest:(id)request completionHandler:(id)handler;
- (void)addRequest:(id)request completionHandler:(id)handler batchEntryName:(id)name;
- (void)addRequest:(id)request completionHandler:(id)handler batchParameters:(id)parameters;
- (void)addRequest:(id)request completionHandler:(id)handler batchParameters:(id)parameters behavior:(int)behavior;
- (void)addRequest:(id)request toBatch:(id)batch attachments:(id)attachments;
- (void)appendAttachments:(id)attachments toBody:(id)body addFormData:(BOOL)data logger:(id)logger;
- (void)appendJSONRequests:(id)requests toBody:(id)body andNameAttachments:(id)attachments logger:(id)logger;
- (void)cancel;
- (id)checkConnectionError:(id)error statusCode:(int)code parsedJSONResponse:(id)response;
- (void)completeDeprecatedWithData:(id)data results:(id)results orError:(id)error;
- (void)completeWithResponse:(id)response data:(id)data orError:(id)error;
- (void)completeWithResults:(id)results orError:(id)error;
// declared property getter: - (id)connection;
- (void)dealloc;
// declared property getter: - (id)deprecatedRequest;
- (id)description;
// declared property getter: - (int)errorBehavior;
- (id)errorFromResult:(id)result;
- (id)errorWithCode:(int)code statusCode:(int)code2 parsedJSONResponse:(id)response innerError:(id)error message:(id)message;
- (id)getBatchAppID:(id)anId;
- (id)getRequestMetadata:(id)metadata;
// declared property getter: - (id)internalUrlRequest;
- (BOOL)isAttachment:(id)attachment;
- (BOOL)isExpiredTokenError:(id)error resultIndex:(unsigned)index;
- (BOOL)isInsufficientPermissionError:(id)error resultIndex:(unsigned)index;
- (BOOL)isInvalidSessionError:(id)error resultIndex:(unsigned)index;
- (BOOL)isPasswordChangeError:(id)error resultIndex:(unsigned)index;
// declared property getter: - (BOOL)isResultFromCache;
- (void)logRequest:(id)request bodyLength:(unsigned)length bodyLogger:(id)logger attachmentLogger:(id)logger4;
// declared property getter: - (id)logger;
- (id)newFBURLConnection;
- (id)parseJSONOrOtherwise:(id)otherwise error:(id *)error;
- (id)parseJSONResponse:(id)response error:(id *)error statusCode:(int)code;
- (void)registerTokenToOmitFromLog:(id)log;
// declared property getter: - (unsigned long)requestStartTime;
- (id)requestWithBatch:(id)batch timeout:(double)timeout;
// declared property getter: - (id)requests;
// declared property getter: - (id)retryManager;
// declared property setter: - (void)setConnection:(id)connection;
// declared property setter: - (void)setDeprecatedRequest:(id)request;
// declared property setter: - (void)setErrorBehavior:(int)behavior;
// declared property setter: - (void)setInternalUrlRequest:(id)request;
// declared property setter: - (void)setLogger:(id)logger;
// declared property setter: - (void)setRequestStartTime:(unsigned long)time;
// declared property setter: - (void)setRequests:(id)requests;
// declared property setter: - (void)setRetryManager:(id)manager;
// declared property setter: - (void)setState:(int)state;
// declared property setter: - (void)setTimeout:(double)timeout;
// declared property setter: - (void)setUrlRequest:(id)request;
// declared property setter: - (void)setUrlResponse:(id)response;
- (BOOL)shouldCloseRequestSession:(id)session;
- (void)start;
- (void)startURLConnectionWithRequest:(id)request skipRoundTripIfCached:(BOOL)cached completionHandler:(id)handler;
- (void)startWithCacheIdentity:(id)cacheIdentity skipRoundtripIfCached:(BOOL)cached;
// declared property getter: - (int)state;
// declared property getter: - (double)timeout;
- (id)unpackIndividualJSONResponseError:(id)error;
// declared property getter: - (id)urlRequest;
// declared property getter: - (id)urlResponse;
- (id)urlStringForSingleRequest:(id)singleRequest forBatch:(BOOL)batch;
@end

