/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray, FBRequestConnectionRetryManagerAlertViewHelper, NSString, FBRequestConnection, FBSession;

@interface FBRequestConnectionRetryManager : NSObject {
	FBRequestConnection *_requestConnection;	// 4 = 0x4
	int _state;	// 8 = 0x8
	FBSession *_sessionToReconnect;	// 12 = 0xc
	NSString *_alertMessage;	// 16 = 0x10
	NSMutableArray *_requestMetadatas;	// 20 = 0x14
	FBRequestConnectionRetryManagerAlertViewHelper *_alertViewHelper;	// 24 = 0x18
}
@property(copy, nonatomic) NSString *alertMessage;	// @synthesize=_alertMessage
@property(retain, nonatomic) FBRequestConnectionRetryManagerAlertViewHelper *alertViewHelper;	// @synthesize=_alertViewHelper
@property(assign, nonatomic) FBRequestConnection *requestConnection;	// @synthesize=_requestConnection
@property(retain, nonatomic) NSMutableArray *requestMetadatas;	// @synthesize=_requestMetadatas
@property(retain, nonatomic) FBSession *sessionToReconnect;	// @synthesize=_sessionToReconnect
@property(assign, nonatomic) int state;	// @synthesize=_state
- (id)initWithFBRequestConnection:(id)fbrequestConnection;
- (void)addRequestMetadata:(id)metadata;
// declared property getter: - (id)alertMessage;
// declared property getter: - (id)alertViewHelper;
- (void)dealloc;
- (void)performRetries;
- (void)repairFailed;
- (void)repairSuccess;
// declared property getter: - (id)requestConnection;
// declared property getter: - (id)requestMetadatas;
// declared property getter: - (id)sessionToReconnect;
// declared property setter: - (void)setAlertMessage:(id)message;
// declared property setter: - (void)setAlertViewHelper:(id)helper;
// declared property setter: - (void)setRequestConnection:(id)connection;
// declared property setter: - (void)setRequestMetadatas:(id)metadatas;
// declared property setter: - (void)setSessionToReconnect:(id)reconnect;
// declared property setter: - (void)setState:(int)state;
// declared property getter: - (int)state;
@end

