/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSError, FBRequest, NSDictionary;

@interface FBRequestMetadata : NSObject {
	FBRequest *_request;	// 4 = 0x4
	id _completionHandler;	// 8 = 0x8
	NSDictionary *_batchParameters;	// 12 = 0xc
	int _behavior;	// 16 = 0x10
	id _originalCompletionHandler;	// 20 = 0x14
	int _retryCount;	// 24 = 0x18
	id _originalResult;	// 28 = 0x1c
	NSError *_originalError;	// 32 = 0x20
}
@property(copy, nonatomic) NSDictionary *batchParameters;	// @synthesize=_batchParameters
@property(assign, nonatomic) int behavior;	// @synthesize=_behavior
@property(copy, nonatomic) id completionHandler;	// @synthesize=_completionHandler
@property(copy, nonatomic) id originalCompletionHandler;	// @synthesize=_originalCompletionHandler
@property(retain, nonatomic) NSError *originalError;	// @synthesize=_originalError
@property(retain, nonatomic) id originalResult;	// @synthesize=_originalResult
@property(retain, nonatomic) FBRequest *request;	// @synthesize=_request
@property(assign, nonatomic) int retryCount;	// @synthesize=_retryCount
- (id)initWithRequest:(id)request completionHandler:(id)handler batchParameters:(id)parameters behavior:(int)behavior;
// declared property getter: - (id)batchParameters;
// declared property getter: - (int)behavior;
// declared property getter: - (id)completionHandler;
- (void)dealloc;
- (id)description;
- (void)invokeCompletionHandlerForConnection:(id)connection withResults:(id)results error:(id)error;
// declared property getter: - (id)originalCompletionHandler;
// declared property getter: - (id)originalError;
// declared property getter: - (id)originalResult;
// declared property getter: - (id)request;
// declared property getter: - (int)retryCount;
// declared property setter: - (void)setBatchParameters:(id)parameters;
// declared property setter: - (void)setBehavior:(int)behavior;
// declared property setter: - (void)setCompletionHandler:(id)handler;
// declared property setter: - (void)setOriginalCompletionHandler:(id)handler;
// declared property setter: - (void)setOriginalError:(id)error;
// declared property setter: - (void)setOriginalResult:(id)result;
// declared property setter: - (void)setRequest:(id)request;
// declared property setter: - (void)setRetryCount:(int)count;
@end

