/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "ModernCombat5-Structs.h"

@class NSString, NSURLConnection, NSMutableData, NSError, FBSession, NSMutableDictionary;
@protocol FBRequestDelegate, FBGraphObject;

@interface FBRequest : NSObject {
	id<FBRequestDelegate> _delegate;	// 4 = 0x4
	NSString *_url;	// 8 = 0x8
	NSURLConnection *_connection;	// 12 = 0xc
	NSMutableData *_responseText;	// 16 = 0x10
	unsigned _state;	// 20 = 0x14
	NSError *_error;	// 24 = 0x18
	BOOL _sessionDidExpire;	// 28 = 0x1c
	id<FBGraphObject> _graphObject;	// 32 = 0x20
	BOOL _canCloseSessionOnError;	// 36 = 0x24
	NSMutableDictionary *_parameters;	// 40 = 0x28
	FBSession *_session;	// 44 = 0x2c
	NSString *_graphPath;	// 48 = 0x30
	NSString *_restMethod;	// 52 = 0x34
	NSString *_HTTPMethod;	// 56 = 0x38
}
@property(copy, nonatomic) NSString *HTTPMethod;	// @synthesize=_HTTPMethod
@property(assign, nonatomic) BOOL canCloseSessionOnError;	// @synthesize=_canCloseSessionOnError
@property(retain, nonatomic) NSURLConnection *connection;
@property(assign, nonatomic) id<FBRequestDelegate> delegate;
@property(retain, nonatomic) NSError *error;
@property(retain, nonatomic) id<FBGraphObject> graphObject;
@property(copy, nonatomic) NSString *graphPath;	// @synthesize=_graphPath
@property(copy, nonatomic) NSString *httpMethod;
@property(readonly, assign, nonatomic) NSMutableDictionary *parameters;	// @synthesize=_parameters
@property(retain, nonatomic) NSMutableDictionary *params;
@property(retain, nonatomic) NSMutableData *responseText;
@property(copy, nonatomic) NSString *restMethod;	// @synthesize=_restMethod
@property(retain, nonatomic) FBSession *session;	// @synthesize=_session
@property(assign, nonatomic) BOOL sessionDidExpire;
@property(assign, nonatomic) unsigned state;
@property(copy, nonatomic) NSString *url;
+ (id)requestForCustomAudienceThirdPartyID:(id)customAudienceThirdPartyID;
+ (id)requestForDeleteObject:(id)deleteObject;
+ (id)requestForGraphPath:(id)graphPath;
+ (id)requestForMe;
+ (id)requestForMyFriends;
+ (id)requestForPlacesSearchAtCoordinate:(XXStruct_UNJ7RC)coordinate radiusInMeters:(int)meters resultsLimit:(int)limit searchText:(id)text;
+ (id)requestForPostOpenGraphObject:(id)postOpenGraphObject;
+ (id)requestForPostOpenGraphObjectWithType:(id)type title:(id)title image:(id)image url:(id)url description:(id)description objectProperties:(id)properties;
+ (id)requestForPostStatusUpdate:(id)postStatusUpdate;
+ (id)requestForPostStatusUpdate:(id)postStatusUpdate place:(id)place tags:(id)tags;
+ (id)requestForPostWithGraphPath:(id)graphPath graphObject:(id)object;
+ (id)requestForUpdateOpenGraphObject:(id)updateOpenGraphObject;
+ (id)requestForUpdateOpenGraphObjectWithId:(id)anId graphObject:(id)object;
+ (id)requestForUpdateOpenGraphObjectWithId:(id)anId title:(id)title image:(id)image url:(id)url description:(id)description objectProperties:(id)properties;
+ (id)requestForUploadPhoto:(id)uploadPhoto;
+ (id)requestForUploadStagingResourceWithImage:(id)image;
+ (id)requestWithGraphPath:(id)graphPath parameters:(id)parameters HTTPMethod:(id)method;
+ (id)serializeURL:(id)url params:(id)params;
+ (id)serializeURL:(id)url params:(id)params httpMethod:(id)method;
- (id)init;
- (id)initForPostWithSession:(id)session graphPath:(id)path graphObject:(id)object;
- (id)initWithSession:(id)session graphPath:(id)path;
- (id)initWithSession:(id)session graphPath:(id)path parameters:(id)parameters HTTPMethod:(id)method;
- (id)initWithSession:(id)session restMethod:(id)method parameters:(id)parameters HTTPMethod:(id)method4;
// declared property getter: - (id)HTTPMethod;
// declared property getter: - (BOOL)canCloseSessionOnError;
// declared property getter: - (id)connection;
- (id)createRequestConnection;
- (void)dealloc;
// declared property getter: - (id)delegate;
- (id)description;
// declared property getter: - (id)error;
// declared property getter: - (id)graphObject;
// declared property getter: - (id)graphPath;
// declared property getter: - (id)httpMethod;
- (BOOL)loading;
// declared property getter: - (id)parameters;
// declared property getter: - (id)params;
// declared property getter: - (id)responseText;
// declared property getter: - (id)restMethod;
// declared property getter: - (id)session;
// declared property getter: - (BOOL)sessionDidExpire;
// declared property setter: - (void)setCanCloseSessionOnError:(BOOL)error;
// declared property setter: - (void)setConnection:(id)connection;
// declared property setter: - (void)setDelegate:(id)delegate;
// declared property setter: - (void)setError:(id)error;
// declared property setter: - (void)setGraphObject:(id)object;
// declared property setter: - (void)setGraphPath:(id)path;
// declared property setter: - (void)setHTTPMethod:(id)method;
// declared property setter: - (void)setHttpMethod:(id)method;
// declared property setter: - (void)setParams:(id)params;
// declared property setter: - (void)setResponseText:(id)text;
// declared property setter: - (void)setRestMethod:(id)method;
// declared property setter: - (void)setSession:(id)session;
// declared property setter: - (void)setSessionDidExpire:(BOOL)expire;
// declared property setter: - (void)setState:(unsigned)state;
// declared property setter: - (void)setUrl:(id)url;
- (id)startWithCompletionHandler:(id)completionHandler;
// declared property getter: - (unsigned)state;
// declared property getter: - (id)url;
@end

