/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "FBSessionLoginStrategy.h"

@class NSString;

@interface FBSessionAppSwitchingLoginStategy : NSObject <FBSessionLoginStrategy> {
	NSString *_methodName;	// 4 = 0x4
}
@property(copy) NSString *methodName;	// @synthesize=_methodName
- (id)init;
- (void)dealloc;
// declared property getter: - (id)methodName;
// declared property setter: - (void)setMethodName:(id)name;
- (BOOL)tryPerformAuthorizeWithParams:(id)params session:(id)session logger:(id)logger;
@end

