/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBSessionUtility : NSObject {
}
+ (void)addWebLoginStartTimeToParams:(id)params;
+ (BOOL)areRequiredPermissions:(id)permissions aSubsetOfPermissions:(id)permissions2;
+ (id)clientStateFromQueryParams:(id)queryParams;
+ (id)expirationDateFromResponseParams:(id)responseParams;
+ (BOOL)isOpenSessionResponseURL:(id)url;
+ (BOOL)logIfFoundUnexpectedPermissions:(id)permissions isRead:(BOOL)read;
+ (id)queryParamsFromLoginURL:(id)loginURL appID:(id)anId urlSchemeSuffix:(id)suffix;
+ (id)sessionStateDescription:(int)description;
+ (void)validateRequestForPermissions:(id)permissions defaultAudience:(int)audience allowSystemAccount:(BOOL)account isRead:(BOOL)read;
@end

