/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class FBSession, NSMutableDictionary, NSString;

@interface FBSessionAuthLogger : NSObject {
	NSString *_ID;	// 4 = 0x4
	NSMutableDictionary *_extras;	// 8 = 0x8
	FBSession *_session;	// 12 = 0xc
	NSString *_authMethod;	// 16 = 0x10
}
@property(copy, nonatomic) NSString *ID;	// @synthesize=_ID
@property(copy, nonatomic) NSString *authMethod;	// @synthesize=_authMethod
@property(retain, nonatomic) NSMutableDictionary *extras;	// @synthesize=_extras
@property(assign, nonatomic) FBSession *session;	// @synthesize=_session
- (id)initWithSession:(id)session;
- (id)initWithSession:(id)session ID:(id)anId authMethod:(id)method;
// declared property getter: - (id)ID;
- (void)addExtrasForNextEvent:(id)nextEvent;
// declared property getter: - (id)authMethod;
- (void)dealloc;
// declared property getter: - (id)extras;
- (void)logEndAuthMethodWithResult:(id)result error:(id)error;
- (void)logEndAuthWithResult:(id)result error:(id)error;
- (void)logEvent:(id)event params:(id)params;
- (void)logEvent:(id)event result:(id)result error:(id)error;
- (void)logStartAuth;
- (void)logStartAuthMethod:(id)method;
- (id)newEventParameters;
// declared property getter: - (id)session;
// declared property setter: - (void)setAuthMethod:(id)method;
// declared property setter: - (void)setExtras:(id)extras;
// declared property setter: - (void)setID:(id)anId;
// declared property setter: - (void)setSession:(id)session;
@end

