/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray;

@interface FBSessionAppEventsState : NSObject {
	BOOL requestInFlight;	// 4 = 0x4
	NSMutableArray *_accumulatedEvents;	// 8 = 0x8
	NSMutableArray *_inFlightEvents;	// 12 = 0xc
	int numSkippedEventsDueToFullBuffer;	// 16 = 0x10
}
@property(retain) NSMutableArray *accumulatedEvents;	// @synthesize=_accumulatedEvents
@property(retain) NSMutableArray *inFlightEvents;	// @synthesize=_inFlightEvents
@property(assign) int numSkippedEventsDueToFullBuffer;	// @synthesize
@property(assign) BOOL requestInFlight;	// @synthesize
- (id)init;
// declared property getter: - (id)accumulatedEvents;
- (void)addEvent:(id)event isImplicit:(BOOL)implicit;
- (void)clearInFlightAndStats;
- (void)dealloc;
- (unsigned)getAccumulatedEventCount;
// declared property getter: - (id)inFlightEvents;
- (id)jsonEncodeInFlightEvents:(BOOL)flightEvents;
// declared property getter: - (int)numSkippedEventsDueToFullBuffer;
// declared property getter: - (BOOL)requestInFlight;
// declared property setter: - (void)setAccumulatedEvents:(id)events;
// declared property setter: - (void)setInFlightEvents:(id)flightEvents;
// declared property setter: - (void)setNumSkippedEventsDueToFullBuffer:(int)fullBuffer;
// declared property setter: - (void)setRequestInFlight:(BOOL)flight;
@end

