/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBSessionTokenCachingStrategy.h"


@interface FBSessionTokenCachingStrategyNoOpInstance : FBSessionTokenCachingStrategy {
}
- (void)cacheTokenInformation:(id)information;
- (void)clearToken;
- (id)fetchTokenInformation;
@end

