/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface FBSessionTokenCachingStrategy : NSObject {
	NSString *_accessTokenInformationKeyName;	// 4 = 0x4
}
+ (id)defaultInstance;
+ (BOOL)isValidTokenInformation:(id)information;
+ (id)nullCacheInstance;
- (id)init;
- (id)initWithUserDefaultTokenInformationKeyName:(id)userDefaultTokenInformationKeyName;
- (void)cacheFBAccessTokenData:(id)data;
- (void)cacheTokenInformation:(id)information;
- (void)clearToken;
- (void)dealloc;
- (id)fetchFBAccessTokenData;
- (id)fetchTokenInformation;
@end

