/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary, NSArray;

@interface FBSessionLoginStrategyParams : NSObject {
	BOOL _tryIntegratedAuth;	// 4 = 0x4
	BOOL _tryFBAppAuth;	// 5 = 0x5
	BOOL _trySafariAuth;	// 6 = 0x6
	BOOL _tryFallback;	// 7 = 0x7
	BOOL _isReauthorize;	// 8 = 0x8
	BOOL _canFetchAppSettings;	// 9 = 0x9
	int _defaultAudience;	// 12 = 0xc
	NSArray *_permissions;	// 16 = 0x10
	NSMutableDictionary *_webParams;	// 20 = 0x14
}
@property(assign) BOOL canFetchAppSettings;	// @synthesize=_canFetchAppSettings
@property(assign) int defaultAudience;	// @synthesize=_defaultAudience
@property(assign) BOOL isReauthorize;	// @synthesize=_isReauthorize
@property(retain, nonatomic) NSArray *permissions;	// @synthesize=_permissions
@property(assign) BOOL tryFBAppAuth;	// @synthesize=_tryFBAppAuth
@property(assign) BOOL tryFallback;	// @synthesize=_tryFallback
@property(assign) BOOL tryIntegratedAuth;	// @synthesize=_tryIntegratedAuth
@property(assign) BOOL trySafariAuth;	// @synthesize=_trySafariAuth
@property(retain, nonatomic) NSMutableDictionary *webParams;	// @synthesize=_webParams
// declared property getter: - (BOOL)canFetchAppSettings;
- (void)dealloc;
// declared property getter: - (int)defaultAudience;
// declared property getter: - (BOOL)isReauthorize;
// declared property getter: - (id)permissions;
// declared property setter: - (void)setCanFetchAppSettings:(BOOL)settings;
// declared property setter: - (void)setDefaultAudience:(int)audience;
// declared property setter: - (void)setIsReauthorize:(BOOL)reauthorize;
// declared property setter: - (void)setPermissions:(id)permissions;
// declared property setter: - (void)setTryFBAppAuth:(BOOL)auth;
// declared property setter: - (void)setTryFallback:(BOOL)fallback;
// declared property setter: - (void)setTryIntegratedAuth:(BOOL)auth;
// declared property setter: - (void)setTrySafariAuth:(BOOL)auth;
// declared property setter: - (void)setWebParams:(id)params;
// declared property getter: - (BOOL)tryFBAppAuth;
// declared property getter: - (BOOL)tryFallback;
// declared property getter: - (BOOL)tryIntegratedAuth;
// declared property getter: - (BOOL)trySafariAuth;
// declared property getter: - (id)webParams;
@end

