/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FBDialogsParams.h"

@class NSURL, NSString, NSArray;

@interface FBShareDialogParams : FBDialogsParams {
	BOOL _dataFailuresFatal;	// 4 = 0x4
	NSURL *_link;	// 8 = 0x8
	NSString *_name;	// 12 = 0xc
	NSString *_caption;	// 16 = 0x10
	NSString *_description;	// 20 = 0x14
	NSURL *_picture;	// 24 = 0x18
	NSArray *_friends;	// 28 = 0x1c
	id _place;	// 32 = 0x20
	NSString *_ref;	// 36 = 0x24
}
@property(copy, nonatomic) NSString *caption;	// @synthesize=_caption
@property(assign, nonatomic) BOOL dataFailuresFatal;	// @synthesize=_dataFailuresFatal
@property(copy, nonatomic) NSString *description;	// @synthesize=_description
@property(copy, nonatomic) NSArray *friends;	// @synthesize=_friends
@property(copy, nonatomic) NSURL *link;	// @synthesize=_link
@property(copy, nonatomic) NSString *name;	// @synthesize=_name
@property(copy, nonatomic) NSURL *picture;	// @synthesize=_picture
@property(copy, nonatomic) id place;	// @synthesize=_place
@property(copy, nonatomic) NSString *ref;	// @synthesize=_ref
- (id)appBridgeVersion;
// declared property getter: - (id)caption;
// declared property getter: - (BOOL)dataFailuresFatal;
- (void)dealloc;
// declared property getter: - (id)description;
- (id)dictionaryMethodArgs;
// declared property getter: - (id)friends;
- (BOOL)isSupportedScheme:(id)scheme;
// declared property getter: - (id)link;
// declared property getter: - (id)name;
// declared property getter: - (id)picture;
// declared property getter: - (id)place;
// declared property getter: - (id)ref;
// declared property setter: - (void)setCaption:(id)caption;
// declared property setter: - (void)setDataFailuresFatal:(BOOL)fatal;
// declared property setter: - (void)setDescription:(id)description;
// declared property setter: - (void)setFriends:(id)friends;
// declared property setter: - (void)setLink:(id)link;
// declared property setter: - (void)setName:(id)name;
// declared property setter: - (void)setPicture:(id)picture;
// declared property setter: - (void)setPlace:(id)place;
// declared property setter: - (void)setRef:(id)ref;
@end

