/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class ACAccountStore, ACAccountType;

@interface FBSystemAccountStoreAdapter : NSObject {
	BOOL _forceBlockingRenew;	// 4 = 0x4
	ACAccountStore *_accountStore;	// 8 = 0x8
	ACAccountType *_accountTypeFB;	// 12 = 0xc
}
@property(readonly, assign, nonatomic) ACAccountStore *accountStore;	// @synthesize=_accountStore
@property(readonly, assign, nonatomic) ACAccountType *accountTypeFB;	// @synthesize=_accountTypeFB
@property(readonly, assign) BOOL canRequestAccessWithoutUI;
@property(assign) BOOL forceBlockingRenew;
+ (void)setSharedInstance:(id)instance;
+ (id)sharedInstance;
- (id)init;
// declared property getter: - (id)accountStore;
// declared property getter: - (id)accountTypeFB;
// declared property getter: - (BOOL)canRequestAccessWithoutUI;
- (void)dealloc;
// declared property getter: - (BOOL)forceBlockingRenew;
- (void)renewSystemAuthorization:(id)authorization;
- (id)renewSystemAuthorizationAsTask;
- (void)requestAccessToFacebookAccountStore:(id)facebookAccountStore defaultAudience:(int)audience isReauthorize:(BOOL)reauthorize appID:(id)anId session:(id)session handler:(id)handler;
- (void)requestAccessToFacebookAccountStore:(id)facebookAccountStore handler:(id)handler;
- (id)requestAccessToFacebookAccountStoreAsTask:(id)facebookAccountStoreAsTask;
// declared property setter: - (void)setForceBlockingRenew:(BOOL)renew;
@end

