/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBUtility : NSObject {
}
+ (id)addBasicInfoPermission:(id)permission;
+ (id)advertiserID;
+ (int)advertisingTrackingStatus;
+ (BOOL)areAllPermissionsReadPermissions:(id)permissions;
+ (id)attributionID;
+ (id)buildFacebookUrlWithPre:(id)pre;
+ (id)buildFacebookUrlWithPre:(id)pre withPost:(id)post;
+ (void)callTheFetchAppSettingsCallback:(id)callback;
+ (void)centerView:(id)view tableView:(id)view2;
+ (unsigned long)currentTimeInMilliseconds;
+ (void)deleteFacebookCookies;
+ (id)dialogBaseURL;
+ (id)dictionaryByParsingURLQueryPart:(id)part;
+ (id)expirationDateFromExpirationTimeIntervalString:(id)expirationTimeIntervalString;
+ (id)expirationDateFromExpirationUnixTimeString:(id)expirationUnixTimeString;
+ (id)facebookSDKBundle;
+ (void)fetchAppSettings:(id)settings callback:(id)callback;
+ (id)fetchedAppSettings;
+ (id)graphObjectInArray:(id)array withSameIDAs:(id)sameIDAs;
+ (BOOL)isFacebookBundleIdentifier:(id)identifier;
+ (BOOL)isFetchedFBAppSettingsStale;
+ (BOOL)isMultitaskingSupported;
+ (BOOL)isPublishPermission:(id)permission;
+ (BOOL)isRegisteredURLScheme:(id)scheme;
+ (BOOL)isRetinaDisplay;
+ (BOOL)isSystemAccountStoreAvailable;
+ (id)localizedStringForKey:(id)key withDefault:(id)aDefault;
+ (id)localizedStringForKey:(id)key withDefault:(id)aDefault inBundle:(id)bundle;
+ (id)newUUIDString;
+ (id)queryParamsDictionaryFromFBURL:(id)fburl;
+ (double)randomTimeInterval:(double)interval withMaxValue:(double)maxValue;
+ (id)simpleJSONDecode:(id)decode;
+ (id)simpleJSONDecode:(id)decode error:(id *)error;
+ (id)simpleJSONEncode:(id)encode;
+ (id)simpleJSONEncode:(id)encode error:(id *)error writingOptions:(unsigned)options;
+ (id)stringAppBaseUrlFromAppId:(id)appId urlSchemeSuffix:(id)suffix;
+ (id)stringBySerializingQueryParameters:(id)parameters;
+ (id)stringByURLDecodingString:(id)string;
+ (id)stringByURLEncodingString:(id)string;
+ (id)stringFBIDFromObject:(id)object;
+ (void)updateParametersWithEventUsageLimitsAndBundleInfo:(id)eventUsageLimitsAndBundleInfo;
@end

