/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface FBWebDialogs : NSObject {
}
+ (void)presentDialogModallyWithSession:(id)session dialog:(id)dialog parameters:(id)parameters handler:(id)handler;
+ (void)presentDialogModallyWithSession:(id)session dialog:(id)dialog parameters:(id)parameters handler:(id)handler delegate:(id)delegate;
+ (void)presentFeedDialogModallyWithSession:(id)session parameters:(id)parameters handler:(id)handler;
+ (void)presentRequestsDialogModallyWithSession:(id)session message:(id)message title:(id)title parameters:(id)parameters handler:(id)handler;
+ (void)presentRequestsDialogModallyWithSession:(id)session message:(id)message title:(id)title parameters:(id)parameters handler:(id)handler friendCache:(id)cache;
@end

