/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "UIWebViewDelegate.h"
#import "ModernCombat5-Structs.h"

@class NSTimer, UIImageView, UIImage, UIView, UIButton, NSURLConnection, NSMutableData, UIWebView, NSString, UIActivityIndicatorView;

@interface FreemiumIGP : NSObject <UIWebViewDelegate> {
	UIView *_freemiumIGPView;	// 4 = 0x4
	UIActivityIndicatorView *_activityIndicator;	// 8 = 0x8
	UIActivityIndicatorView *_activityIndicatorRedirect;	// 12 = 0xc
	UIWebView *_freemiumIGPWebView;	// 16 = 0x10
	NSMutableData *_receivedData;	// 20 = 0x14
	NSURLConnection *_redirectConnection;	// 24 = 0x18
	UIImageView *_headerView;	// 28 = 0x1c
	UIImage *_headerImagePortrait;	// 32 = 0x20
	UIImage *_headerImageLandscape;	// 36 = 0x24
	UIButton *_backButton;	// 40 = 0x28
	BOOL _isInFreemiumIGP;	// 44 = 0x2c
	float _screenWidth;	// 48 = 0x30
	float _screenHeight;	// 52 = 0x34
	NSString *urlAddressIGPFreemium;	// 56 = 0x38
	int _languageIndex;	// 60 = 0x3c
	NSString *_gameVersion;	// 64 = 0x40
	NSTimer *_freemiumIGPTimer;	// 68 = 0x44
	/*function-pointer*/ void *stateCallback;	// 72 = 0x48
	int linkType;	// 76 = 0x4c
}
@property(assign, nonatomic) BOOL isInFreemiumIGP;	// @synthesize=_isInFreemiumIGP
+ (id)EncryptAES_FreemiumIGP:(id)igp :(id)arg2;
+ (id)allocWithZone:(NSZone *)zone;
+ (id)encodeBase64WithData_FreemiumIGP:(id)data_FreemiumIGP;
+ (id)sharedFreemiumIGP;
- (id)init;
- (id)autorelease;
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connection:(id)connection didReceiveData:(id)data;
- (void)connection:(id)connection didReceiveResponse:(id)response;
- (void)connectionDidFinishLoading:(id)connection;
- (id)copyWithZone:(NSZone *)zone;
- (void)getFreemiumIGPLink;
- (void)igpTimerTimeout;
// declared property getter: - (BOOL)isInFreemiumIGP;
- (void)openRedirectLinkWithType:(int)type languageIndex:(int)index andGameVersion:(id)version;
- (void)openRedirectLinkWithType:(int)type languageIndex:(int)index andGameVersion:(id)version ctgSource:(id)source promotedGame:(id)game;
- (void)orientationChanged;
- (void)quitIGPFreemium;
- (oneway void)release;
- (void)reloadIGPWebview;
- (id)retain;
- (unsigned)retainCount;
- (void)setFreemiumIGPStateCallback:(/*function-pointer*/ void *)callback;
// declared property setter: - (void)setIsInFreemiumIGP:(BOOL)freemiumIGP;
- (void)showOnView:(id)view withLanguageIndex:(int)languageIndex andGameVersion:(id)version;
- (void)webView:(id)view didFailWithError:(id)error;
- (BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
- (void)webViewDidFinishLoad:(id)webView;
- (void)webViewDidStartLoad:(id)webView;
@end

