/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "AppDelegate.h"

@class UIWindow, GameView, MPMusicPlayerController, Reachability;

@interface GameDelegate : AppDelegate {
	UIWindow *window;	// 116 = 0x74
	GameView *glView;	// 120 = 0x78
	bool hasWWan;	// 124 = 0x7c
	bool hasWiFi;	// 125 = 0x7d
	MPMusicPlayerController *_musicPlayer;	// 128 = 0x80
	Reachability *_internetReachability;	// 132 = 0x84
}
@property(readonly, assign) GameView *glView;	// @synthesize
@property(assign) bool hasWWan;	// @synthesize
@property(assign) bool hasWiFi;	// @synthesize
@property(assign, nonatomic) Reachability *internetReachability;	// @synthesize=_internetReachability
@property(retain, nonatomic) MPMusicPlayerController *musicPlayer;	// @synthesize=_musicPlayer
@property(readonly, assign) UIWindow *window;	// @synthesize
+ (void)DeleteAllPreviousNotifications;
+ (void)RemoveLocalNotificationsWithId:(const char *)anId;
+ (id)sharedInstance;
- (void)initReachability;
- (id)NewGLView:(BOOL)view;
- (void)activateStatusBar:(void *)bar;
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;
- (void)application:(id)application didFailToRegisterForRemoteNotificationsWithError:(id)error;
- (BOOL)application:(id)application didFinishLaunchingWithOptions:(id)options;
- (void)application:(id)application didReceiveLocalNotification:(id)notification;
- (void)application:(id)application didReceiveRemoteNotification:(id)notification;
- (void)application:(id)application didRegisterForRemoteNotificationsWithDeviceToken:(id)deviceToken;
- (BOOL)application:(id)application handleOpenURL:(id)url;
- (void)applicationDidBecomeActive:(id)application;
- (void)applicationDidEnterBackground:(id)application;
- (void)applicationDidFinishLaunching:(id)application;
- (void)applicationWillEnterForeground:(id)application;
- (void)applicationWillResignActive:(id)application;
- (void)applicationWillTerminate:(id)application;
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connection:(id)connection didReceiveData:(id)data;
- (void)connection:(id)connection didReceiveResponse:(id)response;
- (void)connectionDidFinishLoading:(id)connection;
- (id)createUIViewController;
- (void)dealloc;
- (void)drawView:(id)view;
- (float)getTotalDiskSpaceInBytes;
- (id)getView;
// declared property getter: - (id)glView;
- (void)handlePlaybackStateChanged:(id)changed;
// declared property getter: - (bool)hasWWan;
// declared property getter: - (bool)hasWiFi;
// declared property getter: - (id)internetReachability;
// declared property getter: - (id)musicPlayer;
- (void)reachabilityChanged:(id)changed;
- (void)scheduleNotifications:(const char *)notifications andAction:(const char *)action andTime:(double)time pnId:(const char *)anId;
// declared property setter: - (void)setHasWWan:(bool)wan;
// declared property setter: - (void)setHasWiFi:(bool)fi;
// declared property setter: - (void)setInternetReachability:(id)reachability;
// declared property setter: - (void)setMusicPlayer:(id)player;
- (void)showAlert:(id)alert;
- (void)showInAppPurchaseTimeout:(id)appPurchaseTimeout;
- (void)showInAppPurchaseWaiting:(id)appPurchaseWaiting;
- (void)updateConectivityType;
// declared property getter: - (id)window;
@end

