/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol GameCenterGLSocialLibDelegate <NSObject>
@optional
- (void)onAuthenticateHandler:(id)handler;
- (void)onGetAvatar:(id)avatar withError:(id)error;
- (void)onGetFriendsDataLoad:(id)load withError:(id)error;
- (void)onGetUserDataLoad:(id)load withError:(id)error;
- (void)onReportAchievementDone:(id)done;
- (void)onSelectChallengeablePlayers:(id)players withError:(id)error;
@end

