/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import "MainGLView.h"

@class UIAlertView;

@interface GameView : MainGLView {
	int m_state;	// 128 = 0x80
	bool m_isAppInited;	// 132 = 0x84
	UIAlertView *m_notEnoughFreeSpaceAlert;	// 136 = 0x88
}
- (id)initWithFrame:(CGRect)frame;
- (void)drawView:(id)view;
- (bool)hasEnoughDiskSpaceAvailable;
- (bool)isInErrorMode;
- (void)resumeFromInterrupt;
- (void)showNotEnoughDiskFreeSpace;
@end

