/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class GKTurnBasedMatch, NSString, NSArray, NSData, GKMatchRequest;
@protocol GCEncodingDelegate;

@interface GCEncoding : NSObject {
	id<GCEncodingDelegate> m_delegate;	// 4 = 0x4
	GKMatchRequest *m_request;	// 8 = 0x8
	GKTurnBasedMatch *m_match;	// 12 = 0xc
	NSString *m_matchID;	// 16 = 0x10
	NSData *m_matchData;	// 20 = 0x14
	NSString *m_accessToken;	// 24 = 0x18
	float m_deviceVersion;	// 28 = 0x1c
	int m_matchDataState;	// 32 = 0x20
	NSArray *m_matches;	// 36 = 0x24
	int m_indexMatches;	// 40 = 0x28
}
@property(retain, nonatomic) NSString *m_accessToken;	// @synthesize
@property(retain, nonatomic) id<GCEncodingDelegate> m_delegate;	// @synthesize
@property(assign, nonatomic) float m_deviceVersion;	// @synthesize
@property(assign, nonatomic) int m_indexMatches;	// @synthesize
@property(retain, nonatomic) GKTurnBasedMatch *m_match;	// @synthesize
@property(retain, nonatomic) NSData *m_matchData;	// @synthesize
@property(assign, nonatomic) int m_matchDataState;	// @synthesize
@property(retain, nonatomic) NSString *m_matchID;	// @synthesize
@property(retain, nonatomic) NSArray *m_matches;	// @synthesize
@property(retain, nonatomic) GKMatchRequest *m_request;	// @synthesize
- (id)initWithDelegate:(id)delegate;
- (void)checkMatch;
- (void)checkMatchWithData;
- (void)createMatch;
- (void)createMatchRequest;
- (void)createMatchWithData;
- (void)dealloc;
- (void)deleteMatchContainingData:(id)data;
- (void)deleteMatches;
- (void)findMatch;
- (void)generateAccessToken;
- (void)generateMatchData;
- (void)getMatchData;
- (void)getNumberOfMatches;
- (void)loadMatchHandler:(id)handler withError:(id)error;
- (void)loadMatchWithID:(id)anId;
// declared property getter: - (id)m_accessToken;
// declared property getter: - (id)m_delegate;
// declared property getter: - (float)m_deviceVersion;
// declared property getter: - (int)m_indexMatches;
// declared property getter: - (id)m_match;
// declared property getter: - (id)m_matchData;
// declared property getter: - (int)m_matchDataState;
// declared property getter: - (id)m_matchID;
// declared property getter: - (id)m_matches;
// declared property getter: - (id)m_request;
- (void)retrieveMatchDataFrom:(id)from andError:(id)error;
- (void)sendError:(id)error;
// declared property setter: - (void)setM_accessToken:(id)token;
// declared property setter: - (void)setM_delegate:(id)delegate;
// declared property setter: - (void)setM_deviceVersion:(float)version;
// declared property setter: - (void)setM_indexMatches:(int)matches;
// declared property setter: - (void)setM_match:(id)match;
// declared property setter: - (void)setM_matchData:(id)data;
// declared property setter: - (void)setM_matchDataState:(int)state;
// declared property setter: - (void)setM_matchID:(id)anId;
// declared property setter: - (void)setM_matches:(id)matches;
// declared property setter: - (void)setM_request:(id)request;
- (void)updateMatchData:(id)data;
@end

