/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "ModernCombat5-Structs.h"

@class EAGLContext, UIScreen;

@interface GenericGLView : UIView {
	bool withViewController;	// 51 = 0x33
	bool activateMSAA;	// 52 = 0x34
	int desiredMSAA;	// 56 = 0x38
	int requestedScreenBits;	// 60 = 0x3c
	int requestedDepthBits;	// 64 = 0x40
	int requestedStencilBits;	// 68 = 0x44
	UIScreen *screen;	// 72 = 0x48
	EAGLContext *context;	// 76 = 0x4c
	unsigned viewRenderbuffer;	// 80 = 0x50
	unsigned viewFramebuffer;	// 84 = 0x54
	unsigned depthRenderbuffer;	// 88 = 0x58
	unsigned stencilRenderbuffer;	// 92 = 0x5c
	unsigned resolveFramebuffer;	// 96 = 0x60
	unsigned resolveRenderbuffer;	// 100 = 0x64
	int backingWidth;	// 104 = 0x68
	int backingHeight;	// 108 = 0x6c
	GenericGLViewConfig oglConfig;	// 112 = 0x70
	CreationSettings *creationSettings;	// 124 = 0x7c
}
@property(readonly, assign, nonatomic) bool activateMSAA;	// @synthesize
@property(retain, nonatomic) EAGLContext *context;	// @synthesize
@property(assign, nonatomic) CreationSettings *creationSettings;	// @dynamic
@property(readonly, assign, nonatomic) int desiredMSAA;	// @synthesize
@property(readonly, assign, nonatomic) int requestedDepthBits;	// @synthesize
@property(readonly, assign, nonatomic) int requestedScreenBits;	// @synthesize
@property(readonly, assign, nonatomic) int requestedStencilBits;	// @synthesize
@property(retain, nonatomic) UIScreen *screen;	// @synthesize
@property(readonly, assign, nonatomic) unsigned viewFramebuffer;	// @synthesize
@property(assign, nonatomic) bool withViewController;	// @synthesize
+ (id)alloc;
+ (Class)layerClass;
- (void)initGL;
- (id)initWithFrame:(CGRect)frame;
- (id).cxx_construct;
// declared property getter: - (bool)activateMSAA;
- (void)bind;
// declared property getter: - (id)context;
- (void)createFrameBuffer;
// declared property getter: - (CreationSettings *)creationSettings;
- (void)dealloc;
// declared property getter: - (int)desiredMSAA;
- (void)destroyFrameBuffer;
- (void)destroyRenderBuffers;
- (void)flush;
- (void)layoutSubviews;
// declared property getter: - (int)requestedDepthBits;
// declared property getter: - (int)requestedScreenBits;
// declared property getter: - (int)requestedStencilBits;
// declared property getter: - (id)screen;
// declared property setter: - (void)setContext:(id)context;
// declared property setter: - (void)setCreationSettings:(CreationSettings *)settings;
// declared property setter: - (void)setScreen:(id)screen;
// declared property setter: - (void)setWithViewController:(bool)viewController;
- (BOOL)setupFrameBuffer;
// declared property getter: - (unsigned)viewFramebuffer;
// declared property getter: - (bool)withViewController;
@end

