/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GLSocialLib_SBJsonWriter.h"
#import "GLSocialLib_SBJsonBase.h"


@protocol GLSocialLib_SBJsonWriter
@property(assign) BOOL humanReadable;
@property(assign) BOOL sortKeys;
// declared property getter: - (BOOL)humanReadable;
// declared property setter: - (void)setHumanReadable:(BOOL)readable;
// declared property setter: - (void)setSortKeys:(BOOL)keys;
// declared property getter: - (BOOL)sortKeys;
- (id)stringWithObject:(id)object;
@end

@interface GLSocialLib_SBJsonWriter : GLSocialLib_SBJsonBase <GLSocialLib_SBJsonWriter> {
	BOOL sortKeys;	// 16 = 0x10
	BOOL humanReadable;	// 17 = 0x11
}
@property(assign) BOOL humanReadable;	// @synthesize
@property(assign) BOOL sortKeys;	// @synthesize
+ (void)initialize;
- (BOOL)appendArray:(id)array into:(id)into;
- (BOOL)appendDictionary:(id)dictionary into:(id)into;
- (BOOL)appendString:(id)string into:(id)into;
- (BOOL)appendValue:(id)value into:(id)into;
// declared property getter: - (BOOL)humanReadable;
- (id)indent;
// declared property setter: - (void)setHumanReadable:(BOOL)readable;
// declared property setter: - (void)setSortKeys:(BOOL)keys;
// declared property getter: - (BOOL)sortKeys;
- (id)stringWithFragment:(id)fragment;
- (id)stringWithObject:(id)object;
@end

