/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GLSocialLib_SBJsonParser.h"
#import "GLSocialLib_SBJsonWriter.h"
#import "GLSocialLib_SBJsonBase.h"

@class GLSocialLib_SBJsonParser, GLSocialLib_SBJsonWriter;

@interface GLSocialLib_SBJSON : GLSocialLib_SBJsonBase <GLSocialLib_SBJsonParser, GLSocialLib_SBJsonWriter> {
	GLSocialLib_SBJsonParser *jsonParser;	// 16 = 0x10
	GLSocialLib_SBJsonWriter *jsonWriter;	// 20 = 0x14
}
@property(assign) BOOL humanReadable;
@property(assign) BOOL sortKeys;
- (id)init;
- (void)dealloc;
- (id)fragmentWithString:(id)string error:(id *)error;
// declared property getter: - (BOOL)humanReadable;
- (unsigned)maxDepth;
- (id)objectWithString:(id)string;
- (id)objectWithString:(id)string allowScalar:(BOOL)scalar error:(id *)error;
- (id)objectWithString:(id)string error:(id *)error;
// declared property setter: - (void)setHumanReadable:(BOOL)readable;
- (void)setMaxDepth:(unsigned)depth;
// declared property setter: - (void)setSortKeys:(BOOL)keys;
// declared property getter: - (BOOL)sortKeys;
- (id)stringWithFragment:(id)fragment error:(id *)error;
- (id)stringWithObject:(id)object;
- (id)stringWithObject:(id)object allowScalar:(BOOL)scalar error:(id *)error;
- (id)stringWithObject:(id)object error:(id *)error;
@end

