/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GLSocialLib_SBJsonParser.h"
#import "GLSocialLib_SBJsonBase.h"


@protocol GLSocialLib_SBJsonParser
- (id)objectWithString:(id)string;
@end

@interface GLSocialLib_SBJsonParser : GLSocialLib_SBJsonBase <GLSocialLib_SBJsonParser> {
	const char *c;	// 16 = 0x10
}
+ (void)initialize;
- (id)fragmentWithString:(id)string;
- (id)objectWithString:(id)string;
- (BOOL)scanHexQuad:(unsigned short *)quad;
- (BOOL)scanIsAtEnd;
- (BOOL)scanNumber:(id *)number;
- (BOOL)scanRestOfArray:(id *)array;
- (BOOL)scanRestOfDictionary:(id *)dictionary;
- (BOOL)scanRestOfFalse:(id *)aFalse;
- (BOOL)scanRestOfNull:(id *)null;
- (BOOL)scanRestOfString:(id *)string;
- (BOOL)scanRestOfTrue:(id *)aTrue;
- (BOOL)scanUnicodeChar:(unsigned short *)aChar;
- (BOOL)scanValue:(id *)value;
@end

