/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray, NSArray;

@interface GLSocialLib_SBJsonBase : NSObject {
	NSMutableArray *errorTrace;	// 4 = 0x4
	unsigned depth;	// 8 = 0x8
	unsigned maxDepth;	// 12 = 0xc
}
@property(readonly, copy) NSArray *errorTrace;	// @synthesize
@property(assign) unsigned maxDepth;	// @synthesize
- (id)init;
- (void)addErrorWithCode:(unsigned)code description:(id)description;
- (void)clearErrorTrace;
- (void)dealloc;
// declared property getter: - (id)errorTrace;
// declared property getter: - (unsigned)maxDepth;
// declared property setter: - (void)setMaxDepth:(unsigned)depth;
@end

