/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIAccelerometerDelegate.h"
#import </libobjc.A.h>


@interface InputDelegate : NSObject <UIAccelerometerDelegate> {
}
- (void)accelerometer:(id)accelerometer didAccelerate:(id)accelerate;
@end

