/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSDictionary;

@interface KAAuthAPIRequest : NSObject {
	NSString *_method;	// 4 = 0x4
	NSString *_server;	// 8 = 0x8
	NSDictionary *_parameters;	// 12 = 0xc
	BOOL _post;	// 16 = 0x10
	id _completionHandler;	// 20 = 0x14
}
@property(readonly, assign, nonatomic) id completionHandler;	// @synthesize=_completionHandler
@property(readonly, assign, nonatomic) NSString *method;	// @synthesize=_method
@property(readonly, assign, nonatomic) NSDictionary *parameters;	// @synthesize=_parameters
@property(readonly, assign, nonatomic, getter=isPost) BOOL post;	// @synthesize=_post
@property(readonly, assign, nonatomic) NSString *server;	// @synthesize=_server
- (id)initWithMethod:(id)method server:(id)server parameters:(id)parameters post:(BOOL)post completionHandler:(id)handler;
- (void).cxx_destruct;
// declared property getter: - (id)completionHandler;
// declared property getter: - (BOOL)isPost;
// declared property getter: - (id)method;
// declared property getter: - (id)parameters;
// declared property getter: - (id)server;
@end

