/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol KAAuthWebLoginControllerDelegate <NSObject>
@optional
- (void)loginController:(id)controller didFailWithError:(id)error;
- (void)loginController:(id)controller didFinishAgeAuthWithAccessToken:(id)accessToken;
- (void)loginController:(id)controller didFinishWithAccessToken:(id)accessToken expiresIn:(int)anIn refreshToken:(id)token;
@end

