/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import </libobjc.A.h>
#import "UIWebViewDelegate.h"

@class UIImageView, UIBarButtonItem, KANavigationBar, UIView, UIWebView, NSString;
@protocol KAAuthWebLoginControllerDelegate;

@interface KAAuthWebLoginController : NSObject <UIWebViewDelegate> {
	id<KAAuthWebLoginControllerDelegate> _delegate;	// 4 = 0x4
	UIView *_view;	// 8 = 0x8
	UIImageView *_frameImageView;	// 12 = 0xc
	UIView *_backgroundView;	// 16 = 0x10
	KANavigationBar *_navigationBar;	// 20 = 0x14
	UIWebView *_webView;	// 24 = 0x18
	NSString *_clientID;	// 28 = 0x1c
	NSString *_clientSecret;	// 32 = 0x20
	NSString *_kakaoTalkVersion;	// 36 = 0x24
	BOOL _isIpad;	// 40 = 0x28
	NSString *_accessToken;	// 44 = 0x2c
	UIBarButtonItem *_backButtonItem;	// 48 = 0x30
}
@property(copy, nonatomic) NSString *accessToken;	// @synthesize=_accessToken
@property(retain, nonatomic) UIBarButtonItem *backButtonItem;	// @synthesize=_backButtonItem
@property(assign, nonatomic) id<KAAuthWebLoginControllerDelegate> delegate;	// @synthesize=_delegate
- (id)initWithAccessToken:(id)accessToken clientId:(id)anId kakaoTalkVersion:(id)version;
- (id)initWithClientID:(id)clientID clientSecret:(id)secret kakaoTalkVersion:(id)version;
- (void).cxx_destruct;
// declared property getter: - (id)accessToken;
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;
- (void)applicationDidChangeStatusBarFrameWithNotification:(id)application;
- (void)applicationDidChangeStatusBarOrientationWithNotification:(id)application;
// declared property getter: - (id)backButtonItem;
- (id)countryISO;
- (void)dealloc;
// declared property getter: - (id)delegate;
- (id)getCustomButtonByTitle:(id)title action:(SEL)action isBack:(BOOL)back;
- (void)hideWithCompletionHandler:(id)completionHandler;
- (void)invokeBackWithTarget:(id)target;
- (void)invokeCancelWithTarget:(id)target;
- (void)layoutLoginViewForOrientation:(int)orientation;
- (void)loadAgeAuthRequest;
- (void)loadLoginModalViewIfNotLoaded;
- (void)loadLoginRequest;
- (id)preferredLanguage;
- (void)processNavigationTypeAlert:(id)alert;
- (void)processNavigationTypeAppAuth:(id)auth;
- (void)processNavigationTypeCanOpenURL:(id)url;
- (void)processNavigationTypeConfirm:(id)confirm;
- (void)processNavigationTypeNavigate:(id)navigate;
// declared property setter: - (void)setAccessToken:(id)token;
// declared property setter: - (void)setBackButtonItem:(id)item;
// declared property setter: - (void)setDelegate:(id)delegate;
- (void)show;
- (void)sizeViewToFitOrientation:(int)fitOrientation;
- (CGAffineTransform)transformForOrientation:(int)orientation;
- (void)webView:(id)view didFailLoadWithError:(id)error;
- (BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
- (void)webViewDidFinishLoad:(id)webView;
- (void)webViewDidStartLoad:(id)webView;
@end

