/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import </libobjc.A.h>
#import "KAAuthWebLoginControllerDelegate.h"

@class NSMutableArray, NSString, KAAuthWebLoginController;

@interface KAAuth : NSObject <KAAuthWebLoginControllerDelegate> {
	NSString *_clientID;	// 4 = 0x4
	NSString *_clientSecret;	// 8 = 0x8
	NSString *_redirectURL;	// 12 = 0xc
	NSString *_accessToken;	// 16 = 0x10
	NSString *_refreshToken;	// 20 = 0x14
	id _authenticationCompletionHandler;	// 24 = 0x18
	id _guestLoginCompletionHandler;	// 28 = 0x1c
	struct {
		unsigned isExtendingAccessToken : 1;
	} _authFlags;	// 32 = 0x20
	NSMutableArray *_pendingRequests;	// 36 = 0x24
	dispatch_queue_s *_queue;	// 40 = 0x28
	KAAuthWebLoginController *_webLoginController;	// 44 = 0x2c
	BOOL _guestLoggedOn;	// 48 = 0x30
}
@property(copy, nonatomic) NSString *accessToken;	// @synthesize=_accessToken
@property(readonly, assign, nonatomic, getter=isAuthenticated) BOOL authenticated;
@property(readonly, assign, nonatomic) NSString *clientID;	// @synthesize=_clientID
@property(readonly, assign, nonatomic) NSString *clientSecret;	// @synthesize=_clientSecret
@property(retain, nonatomic) NSString *deviceToken;
@property(readonly, assign, nonatomic, getter=isGuestLoggedOn) BOOL guestLoggedOn;
@property(readonly, assign, nonatomic) NSString *redirectURL;	// @synthesize=_redirectURL
@property(copy, nonatomic) NSString *refreshToken;	// @synthesize=_refreshToken
+ (void)setSharedAuth:(id)auth;
+ (id)sharedAuth;
- (id)init;
- (id)initWithClientID:(id)clientID clientSecret:(id)secret redirectURL:(id)url accessToken:(id)token refreshToken:(id)token5;
- (void).cxx_destruct;
- (id)KAAPIURLString;
- (void)_sendAPIRequestWithMethod:(id)method server:(id)server parameters:(id)parameters HTTPMethod:(int)method4 completionHandler:(id)handler;
- (void)_sendAPIRequestWithMethod:(id)method server:(id)server parameters:(id)parameters post:(BOOL)post completionHandler:(id)handler secondTry:(BOOL)aTry;
// declared property getter: - (id)accessToken;
- (void)cancelPendingRequestsWithError:(id)error;
- (void)cancelRegistration;
- (void)clearRegistration;
// declared property getter: - (id)clientID;
// declared property getter: - (id)clientSecret;
- (void)dealloc;
// declared property getter: - (id)deviceToken;
- (void)extendToken;
- (id)guestLoginID;
- (void)guestLoginWithCompletionHandler:(id)completionHandler;
- (void)guestLogout;
- (BOOL)handleOpenURL:(id)url;
// declared property getter: - (BOOL)isAuthenticated;
// declared property getter: - (BOOL)isGuestLoggedOn;
- (id)kakaoTalkVersion;
- (BOOL)kakaotalkAuthAvailable;
- (void)loginController:(id)controller didFailWithError:(id)error;
- (void)loginController:(id)controller didFinishWithAccessToken:(id)accessToken expiresIn:(int)anIn refreshToken:(id)token;
- (id)oldUser;
- (void)postAuthenticationDidChangeNotificationOnMainThread;
// declared property getter: - (id)redirectURL;
// declared property getter: - (id)refreshToken;
- (void)registerWithCompletionHandler:(id)completionHandler;
- (void)registerWithRefreshToken:(id)refreshToken accessToken:(id)token expiresIn:(int)anIn;
- (void)requestTokensWithCode:(id)code;
- (void)resumePendingRequests;
- (void)sendAPIRequestWithMethod:(id)method parameters:(id)parameters post:(BOOL)post completionHandler:(id)handler;
- (void)sendUploadAPIRequestWithUIImage:(id)uiimage completionHandler:(id)handler;
// declared property setter: - (void)setAccessToken:(id)token;
// declared property setter: - (void)setDeviceToken:(id)token;
- (void)setGuestLoggedOn:(BOOL)on;
- (void)setGuestLoginID:(id)anId;
// declared property setter: - (void)setRefreshToken:(id)token;
- (void)unregisterGuestUserID;
@end

