/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import </libobjc.A.h>

@class NSString;

@interface KakaoGLSocialLib : NSObject {
	NSString *_accessToken;	// 4 = 0x4
	NSString *_refreshToken;	// 8 = 0x8
}
@property(retain, nonatomic) NSString *accessToken;	// @synthesize=_accessToken
@property(retain, nonatomic) NSString *refreshToken;	// @synthesize=_refreshToken
- (id)initWithClientID:(id)clientID andClientSecret:(id)secret;
// declared property getter: - (id)accessToken;
- (void)authSucceded:(BOOL)succeded;
- (void)doStoryPost:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)post;
- (BOOL)handleOpenUrl:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)url;
- (BOOL)isAuthenticated;
- (void)kakaoAuthenticationDidChangeWithNotification:(id)kakaoAuthentication;
- (void)loadFriends:(int)friends;
- (void)loadFriendsData:(int)data;
- (void)loadFriendsWithIds:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)ids;
- (void)loadUserAvatar;
- (void)loadUserData;
- (void)loadUserId;
- (void)loadUserName;
- (void)login;
- (void)logout;
- (void)logoutSucceeded:(BOOL)succeeded;
// declared property getter: - (id)refreshToken;
- (void)sendGameRequestToFriends:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)friends withMessage:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)message;
// declared property setter: - (void)setAccessToken:(id)token;
// declared property setter: - (void)setRefreshToken:(id)token;
@end

