/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, NSDictionary;

@interface KALinkMessageRequest : NSObject {
	NSString *_receiverID;	// 4 = 0x4
	NSString *_chatID;	// 8 = 0x8
	NSString *_message;	// 12 = 0xc
	NSString *_executeURLString;	// 16 = 0x10
	NSString *_templateID;	// 20 = 0x14
	NSDictionary *_metaInfo;	// 24 = 0x18
}
@property(readonly, assign, nonatomic) NSString *chatID;	// @synthesize=_chatID
@property(readonly, assign, nonatomic) NSString *executeURLString;	// @synthesize=_executeURLString
@property(readonly, assign, nonatomic) NSString *message;	// @synthesize=_message
@property(readonly, assign, nonatomic) NSDictionary *metaInfo;	// @synthesize=_metaInfo
@property(readonly, assign, nonatomic) NSString *receiverID;	// @synthesize=_receiverID
@property(readonly, assign, nonatomic) NSString *templateID;	// @synthesize=_templateID
+ (id)requestWithChatID:(id)chatID message:(id)message executeURLString:(id)string;
+ (id)requestWithChatID:(id)chatID templateID:(id)anId metaInfo:(id)info;
+ (id)requestWithReceiverID:(id)receiverID message:(id)message executeURLString:(id)string;
+ (id)requestWithReceiverID:(id)receiverID templateID:(id)anId metaInfo:(id)info;
- (id)initWithReceiverID:(id)receiverID chatID:(id)anId message:(id)message executeURLString:(id)string;
- (id)initWithReceiverID:(id)receiverID chatID:(id)anId templateID:(id)anId3 metaInfo:(id)info;
- (void).cxx_destruct;
// declared property getter: - (id)chatID;
// declared property getter: - (id)executeURLString;
// declared property getter: - (id)message;
// declared property getter: - (id)metaInfo;
// declared property getter: - (id)receiverID;
// declared property getter: - (id)templateID;
@end

