/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface KALocalUser : NSObject {
}
+ (void)initialize;
+ (id)localUser;
- (id)init;
- (id)convertFriendsUserIDToString:(id)string;
- (double)friendListCachingInterval;
- (void)getPushInfoWithCompletionHandler:(id)completionHandler;
- (BOOL)hasValidDeviceToken;
- (void)loadFriendsWithCompletionHandler:(id)completionHandler;
- (void)loadLocalUserWithCompletionHandler:(id)completionHandler;
- (void)logoutWithCompletionHandler:(id)completionHandler;
- (void)pushAPIRequestWithMethod:(id)method parameters:(id)parameters completionHandler:(id)handler;
- (void)registerDeviceTokenWithCompletionHandler:(id)completionHandler;
- (void)sendLinkMessageWithRequest:(id)request completionHandler:(id)handler;
- (void)sendPaymentInfo:(id)info withCompletionHandler:(id)completionHandler;
- (void)sendPushToReceiverId:(id)receiverId message:(id)message customField:(id)field withCompletionHandler:(id)completionHandler;
- (void)setPushAlert:(BOOL)alert withCompletionHandler:(id)completionHandler;
- (void)unregisterWithCompletionHandler:(id)completionHandler;
@end

