/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface KAProperties : NSObject {
}
@property(retain, nonatomic) NSString *deviceToken;
+ (void)initialize;
+ (id)sharedProperties;
- (id)init;
- (id)APIDomain;
- (id)cachingInterval;
// declared property getter: - (id)deviceToken;
- (id)friendListCache;
- (id)friendListUpdateAt;
- (id)objectForKey:(id)key;
- (void)removeObjectForKey:(id)key;
- (void)removePrevVersionCache;
- (void)resetCache;
- (void)setAPIDomain:(id)domain;
- (void)setCachingInterval:(id)interval;
// declared property setter: - (void)setDeviceToken:(id)token;
- (void)setFriendListCache:(id)cache;
- (void)setFriendListUpdateAt:(id)at;
- (void)setObject:(id)object forKey:(id)key;
- (id)versionKey:(id)key;
@end

