/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GenericGLView.h"
#import "ModernCombat5-Structs.h"


@interface MainGLView : GenericGLView {
}
- (id)initWithFrame:(CGRect)frame;
- (BOOL)canBecomeFirstResponder;
- (void)motionBegan:(int)began withEvent:(id)event;
- (void)motionCancelled:(int)cancelled withEvent:(id)event;
- (void)motionEnded:(int)ended withEvent:(id)event;
- (void)touchesBegan:(id)began withEvent:(id)event;
- (void)touchesCancelled:(id)cancelled withEvent:(id)event;
- (void)touchesEnded:(id)ended withEvent:(id)event;
- (void)touchesMoved:(id)moved withEvent:(id)event;
@end

