/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "MGTwitterParserDelegate.h"

@class NSString, NSMutableDictionary;
@protocol MGTwitterEngineDelegate;

@interface MGTwitterEngine : NSObject <MGTwitterParserDelegate> {
	NSObject<MGTwitterEngineDelegate> *_delegate;	// 4 = 0x4
	NSString *_username;	// 8 = 0x8
	NSString *_password;	// 12 = 0xc
	NSMutableDictionary *_connections;	// 16 = 0x10
	NSString *_clientName;	// 20 = 0x14
	NSString *_clientVersion;	// 24 = 0x18
	NSString *_clientURL;	// 28 = 0x1c
	NSString *_clientSourceToken;	// 32 = 0x20
	NSString *_APIDomain;	// 36 = 0x24
	BOOL _secureConnection;	// 40 = 0x28
	BOOL _clearsCookies;	// 41 = 0x29
}
+ (id)twitterEngineWithDelegate:(id)delegate;
+ (id)version;
- (id)initWithDelegate:(id)delegate;
- (id)APIDomain;
- (id)_HTTPDateFormatter;
- (id)_HTTPToDate:(id)date;
- (id)_dateToHTTP:(id)http;
- (id)_encodeString:(id)string;
- (BOOL)_isValidDelegateForSelector:(SEL)selector;
- (void)_parseDataForConnection:(id)connection;
- (id)_queryStringWithBase:(id)base parameters:(id)parameters prefixed:(BOOL)prefixed;
- (id)_sendRequestWithMethod:(id)method path:(id)path queryParameters:(id)parameters body:(id)body requestType:(int)type responseType:(int)type6;
- (id)block:(id)block;
- (id)checkUserCredentials;
- (BOOL)clearsCookies;
- (id)clientName;
- (id)clientSourceToken;
- (id)clientURL;
- (id)clientVersion;
- (void)closeAllConnections;
- (void)closeConnection:(id)connection;
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connection:(id)connection didReceiveAuthenticationChallenge:(id)challenge;
- (void)connection:(id)connection didReceiveData:(id)data;
- (void)connection:(id)connection didReceiveResponse:(id)response;
- (void)connectionDidFinishLoading:(id)connection;
- (id)connectionIdentifiers;
- (void)dealloc;
- (id)deleteDirectMessage:(unsigned long)message;
- (id)deleteUpdate:(unsigned long)update;
- (id)disableNotificationsFor:(id)aFor;
- (id)disableUpdatesFor:(id)aFor;
- (id)enableNotificationsFor:(id)aFor;
- (id)enableUpdatesFor:(id)aFor;
- (id)endUserSession;
- (id)getDirectMessagesSinceID:(unsigned long)anId startingAtPage:(int)page;
- (id)getDirectMessagesSinceID:(unsigned long)anId withMaximumID:(unsigned long)maximumID startingAtPage:(int)page count:(int)count;
- (id)getDowntimeSchedule;
- (id)getFavoriteUpdatesFor:(id)aFor startingAtPage:(int)page;
- (id)getFeaturedUsers;
- (id)getFollowedTimelineSinceID:(unsigned long)anId startingAtPage:(int)page count:(int)count;
- (id)getFollowedTimelineSinceID:(unsigned long)anId withMaximumID:(unsigned long)maximumID startingAtPage:(int)page count:(int)count;
- (id)getFollowersIncludingCurrentStatus:(BOOL)status;
- (id)getImageAtURL:(id)url;
- (id)getPublicTimeline;
- (id)getRateLimitStatus;
- (id)getRecentlyUpdatedFriendsFor:(id)aFor startingAtPage:(int)page;
- (id)getRepliesSinceID:(unsigned long)anId startingAtPage:(int)page count:(int)count;
- (id)getRepliesSinceID:(unsigned long)anId withMaximumID:(unsigned long)maximumID startingAtPage:(int)page count:(int)count;
- (id)getRepliesStartingAtPage:(int)page;
- (id)getSentDirectMessagesSinceID:(unsigned long)anId startingAtPage:(int)page;
- (id)getSentDirectMessagesSinceID:(unsigned long)anId withMaximumID:(unsigned long)maximumID startingAtPage:(int)page count:(int)count;
- (id)getUpdate:(unsigned long)update;
- (id)getUserInformationFor:(id)aFor;
- (id)getUserInformationForEmail:(id)email;
- (id)getUserTimelineFor:(id)aFor sinceID:(unsigned long)anId startingAtPage:(int)page count:(int)count;
- (id)getUserTimelineFor:(id)aFor sinceID:(unsigned long)anId withMaximumID:(unsigned long)maximumID startingAtPage:(int)page count:(int)count;
- (id)isUser:(id)user receivingUpdatesFor:(id)aFor;
- (id)markUpdate:(unsigned long)update asFavorite:(BOOL)favorite;
- (int)numberOfConnections;
- (void)parsingFailedForRequest:(id)request ofResponseType:(int)responseType withError:(id)error;
- (void)parsingSucceededForRequest:(id)request ofResponseType:(int)responseType withParsedObjects:(id)parsedObjects;
- (id)password;
- (id)sendDirectMessage:(id)message to:(id)to;
- (id)sendUpdate:(id)update;
- (id)sendUpdate:(id)update inReplyTo:(unsigned long)to;
- (void)setAPIDomain:(id)domain;
- (void)setClearsCookies:(BOOL)cookies;
- (void)setClientName:(id)name version:(id)version URL:(id)url token:(id)token;
- (id)setLocation:(id)location;
- (id)setNotificationsDeliveryMethod:(id)method;
- (void)setUsername:(id)username password:(id)password;
- (void)setUsesSecureConnection:(BOOL)connection;
- (id)testService;
- (id)unblock:(id)unblock;
- (id)username;
- (BOOL)usesSecureConnection;
@end

