/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray, NSString, NSXMLParser, NSMutableDictionary, NSData;
@protocol MGTwitterParserDelegate;

@interface MGTwitterXMLParser : NSObject {
	NSObject<MGTwitterParserDelegate> *delegate;	// 4 = 0x4
	NSString *identifier;	// 8 = 0x8
	int requestType;	// 12 = 0xc
	int responseType;	// 16 = 0x10
	NSData *xml;	// 20 = 0x14
	NSMutableArray *parsedObjects;	// 24 = 0x18
	NSXMLParser *parser;	// 28 = 0x1c
	NSMutableDictionary *currentNode;	// 32 = 0x20
	NSString *lastOpenedElement;	// 36 = 0x24
}
+ (id)parserWithXML:(id)xml delegate:(id)delegate connectionIdentifier:(id)identifier requestType:(int)type responseType:(int)type5;
- (id)initWithXML:(id)xml delegate:(id)delegate connectionIdentifier:(id)identifier requestType:(int)type responseType:(int)type5;
- (void)addSource;
- (void)dealloc;
- (id)lastOpenedElement;
- (void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;
- (void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;
- (void)parser:(id)parser foundAttributeDeclarationWithName:(id)name forElement:(id)element type:(id)type defaultValue:(id)value;
- (void)parser:(id)parser foundCharacters:(id)characters;
- (void)parser:(id)parser foundIgnorableWhitespace:(id)whitespace;
- (void)parser:(id)parser parseErrorOccurred:(id)occurred;
- (void)parserDidEndDocument:(id)parser;
- (void)parserDidStartDocument:(id)parser;
- (void)setLastOpenedElement:(id)element;
@end

