/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol MGTwitterParserDelegate
- (void)parsingFailedForRequest:(id)request ofResponseType:(int)responseType withError:(id)error;
- (void)parsingSucceededForRequest:(id)request ofResponseType:(int)responseType withParsedObjects:(id)parsedObjects;
@end

