/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol MGTwitterEngineDelegate
@optional
- (void)connectionFinished:(id)finished;
- (void)directMessagesReceived:(id)received forRequest:(id)request;
- (void)imageReceived:(id)received forRequest:(id)request;
- (void)miscInfoReceived:(id)received forRequest:(id)request;
@required
- (void)requestFailed:(id)failed withError:(id)error;
- (void)requestSucceeded:(id)succeeded;
@optional
- (void)statusesReceived:(id)received forRequest:(id)request;
- (void)userInfoReceived:(id)received forRequest:(id)request;
@end

