/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "ModernCombat5-Structs.h"

@class UILabel, UIButton;

@interface MovieSubtitlesView : UIView {
	UILabel *m_Label;	// 52 = 0x34
	UILabel *m_LabelShadow;	// 56 = 0x38
	UIButton *m_SkipBtn;	// 60 = 0x3c
	int m_MoviePlaytime;	// 64 = 0x40
	int m_SubtitleUpdateTime;	// 68 = 0x44
	int m_btnsTimeBeforeFade;	// 72 = 0x48
	CGAffineTransform m_baseTransform;	// 76 = 0x4c
}
@property(retain, nonatomic) UIButton *m_SkipBtn;	// @synthesize
- (id)initWithFrame:(CGRect)frame :(bool)arg2;
- (id).cxx_construct;
- (void)FadebuttonOnTime:(id)time;
- (void)SkipButtonTapped:(id)tapped event:(id)event;
- (void)dealloc;
// declared property getter: - (id)m_SkipBtn;
- (void)rewind:(int)rewind;
// declared property setter: - (void)setM_SkipBtn:(id)btn;
- (void)signalPlaybackStarted:(int)started;
- (void)touchesBegan:(id)began withEvent:(id)event;
- (void)updateSubtitles;
@end

