/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <MediaPlayer/MPMoviePlayerViewController.h>


@interface MoviePlayerViewController : MPMoviePlayerViewController {
	unsigned char m_bIsOnSecondaryScreen;	// 164 = 0xa4
}
@end

