/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class UIViewController, MovieSubtitlesView;

@interface MoviePlayer : NSObject {
	UIViewController *mMoviePlayer;	// 4 = 0x4
	unsigned char m_isMoviePlaying;	// 8 = 0x8
	unsigned char m_isMovieLoading;	// 9 = 0x9
	MovieSubtitlesView *m_subtitles;	// 12 = 0xc
	double m_resumeTime;	// 16 = 0x10
	int m_orientation;	// 24 = 0x18
}
@property(readonly, assign) MovieSubtitlesView *m_subtitles;	// @synthesize
- (id)initWithFile:(id)file andFlipped:(unsigned char)flipped;
- (void)BtnTapped_Skip:(id)skip event:(id)event;
- (void)changeSubtitlesOrientation:(int)orientation;
- (void)checkResume;
- (void)checkViewController;
- (void)dealloc;
- (void)doDismissViewController;
- (void)doPresentViewController;
- (void)freeMovie;
- (double)getCurrentPlaybackTime;
- (unsigned char)isLoading;
- (unsigned char)isPlaying;
// declared property getter: - (id)m_subtitles;
- (void)moviePlayBackDidFinish:(id)moviePlayBack;
- (void)moviePlayBackLoadStateChanged:(id)changed;
- (void)moviePlayBackStateChange:(id)change;
- (void)moviePreloadDidFinish:(id)moviePreload;
- (void)movieSubtitles_init;
- (void)movieSubtitles_reset;
- (void)pauseMovie;
- (void)playMovie;
- (void)playMovieFromInterrupt;
- (void)stopMovie;
- (void)willStop;
@end

