/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import "UIAlertViewDelegate.h"
#import </libobjc.A.h>


@interface MyAlert : NSObject <UIAlertViewDelegate> {
	Atomic<int> buttonResult;	// 4 = 0x4
}
@property(assign) Atomic<int> buttonResult;	// @synthesize
+ (int)showModal:(id)modal Message:(id)message Cancel:(id)cancel Elems:(id)elems;
+ (int)showModal:(id)modal Message:(id)message Cancel:(id)cancel Other:(id)other;
- (id)init;
- (id).cxx_construct;
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;
// declared property getter: - (Atomic<int>)buttonResult;
// declared property setter: - (void)setButtonResult:(Atomic<int>)result;
- (int)show:(id)show;
@end

