/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSString.h>


@interface NSString (NSAddition)
- (id)stringBetweenString:(id)string andString:(id)string2;
@end

@interface NSString (SinaWeiboEncode)
- (id)URLEncodedString;
- (id)URLEncodedStringWithCFStringEncoding:(unsigned long)cfstringEncoding;
@end

@interface NSString (TwitterOAuth)
- (BOOL)oauthtwitter_isNumeric;
@end

