/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import "MFMessageComposeViewControllerDelegate.h"
#import <UIKit/UIViewController.h>

@class UIWindow;

@interface NumberPhonebookiOSGLSocialLib : UIViewController <MFMessageComposeViewControllerDelegate> {
	void *addressbook;	// 160 = 0xa0
	set<std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::basic_string<char> > > m_nameCheckSet;	// 164 = 0xa4
	map<std::__1::basic_string<char>, std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::basic_string<char> > > > m_numberToNameMap;	// 176 = 0xb0
	basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > m_message;	// 188 = 0xbc
	vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > > m_toUids;	// 200 = 0xc8
	UIWindow *parentWindow;	// 212 = 0xd4
	UIWindow *oldWindow;	// 216 = 0xd8
	BOOL wasStatusBarVisible;	// 220 = 0xdc
	int gameOrientation;	// 224 = 0xe0
}
@property(assign, nonatomic) void *addressbook;	// @synthesize
@property(assign, nonatomic) int gameOrientation;	// @synthesize
@property(assign, nonatomic) basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > m_message;	// @synthesize
@property(assign, nonatomic) set<std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::basic_string<char> > > m_nameCheckSet;	// @synthesize
@property(assign, nonatomic) map<std::__1::basic_string<char>, std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::basic_string<char> > > > m_numberToNameMap;	// @synthesize
@property(assign, nonatomic) vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > > m_toUids;	// @synthesize
@property(assign, nonatomic) BOOL wasStatusBarVisible;	// @synthesize
+ (void)setGameViewController:(id)controller;
- (id)init;
- (id).cxx_construct;
- (void).cxx_destruct;
// declared property getter: - (void *)addressbook;
// declared property getter: - (int)gameOrientation;
- (void)getFriends;
- (void)getUserData:(id)data;
- (void)getUserNames:(id)names;
// declared property getter: - (basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)m_message;
// declared property getter: - (set<std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::basic_string<char> > >)m_nameCheckSet;
// declared property getter: - (map<std::__1::basic_string<char>, std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::basic_string<char> > > >)m_numberToNameMap;
// declared property getter: - (vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >)m_toUids;
- (void)messageComposeViewController:(id)controller didFinishWithResult:(int)result;
- (void)onFriendsLoaded;
- (int)preferredInterfaceOrientationForPresentation;
- (void)queryPhonebook;
- (void)readAddressBookContacts;
- (void)sendMessageTo;
// declared property setter: - (void)setAddressbook:(void *)addressbook;
// declared property setter: - (void)setGameOrientation:(int)orientation;
// declared property setter: - (void)setM_message:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)message;
// declared property setter: - (void)setM_nameCheckSet:(set<std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::basic_string<char> > >)set;
// declared property setter: - (void)setM_numberToNameMap:(map<std::__1::basic_string<char>, std::__1::basic_string<char>, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, std::__1::basic_string<char> > > >)nameMap;
// declared property setter: - (void)setM_toUids:(vector<std::__1::basic_string<char>, std::__1::allocator<std::__1::basic_string<char> > >)uids;
// declared property setter: - (void)setWasStatusBarVisible:(BOOL)visible;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
- (unsigned)supportedInterfaceOrientations;
// declared property getter: - (BOOL)wasStatusBarVisible;
@end

