/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface OAConsumer : NSObject {
	NSString *key;	// 4 = 0x4
	NSString *secret;	// 8 = 0x8
}
@property(retain) NSString *key;	// @synthesize
@property(retain) NSString *secret;	// @synthesize
- (id)initWithKey:(id)key secret:(id)secret;
- (void)dealloc;
// declared property getter: - (id)key;
// declared property getter: - (id)secret;
// declared property setter: - (void)setKey:(id)key;
// declared property setter: - (void)setSecret:(id)secret;
@end

