/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSURLResponse, NSURLConnection, NSError, NSData, OAMutableURLRequest;

@interface OADataFetcher : NSObject {
	OAMutableURLRequest *request;	// 4 = 0x4
	NSURLResponse *response;	// 8 = 0x8
	NSURLConnection *connection;	// 12 = 0xc
	NSError *error;	// 16 = 0x10
	NSData *responseData;	// 20 = 0x14
	id delegate;	// 24 = 0x18
	SEL didFinishSelector;	// 28 = 0x1c
	SEL didFailSelector;	// 32 = 0x20
}
- (void)fetchDataWithRequest:(id)request delegate:(id)delegate didFinishSelector:(SEL)selector didFailSelector:(SEL)selector4;
@end

