/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "OASignatureProviding.h"
#import </libobjc.A.h>


@interface OAHMAC_SHA1SignatureProvider : NSObject <OASignatureProviding> {
}
- (id)name;
- (id)signClearText:(id)text withSecret:(id)secret;
@end

