/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSMutableURLRequest.h>

@class NSString, OAToken, NSArray, OAConsumer;
@protocol OASignatureProviding;

@interface OAMutableURLRequest : NSMutableURLRequest {
	OAConsumer *consumer;	// 8 = 0x8
	OAToken *token;	// 12 = 0xc
	NSString *realm;	// 16 = 0x10
	NSString *signature;	// 20 = 0x14
	id<OASignatureProviding> signatureProvider;	// 24 = 0x18
	NSString *nonce;	// 28 = 0x1c
	NSString *timestamp;	// 32 = 0x20
}
@property(readonly, assign) NSString *nonce;	// @synthesize
@property(retain, nonatomic) NSArray *parameters;
@property(readonly, assign) NSString *signature;	// @synthesize
- (id)initWithURL:(id)url consumer:(id)consumer token:(id)token realm:(id)realm signatureProvider:(id)provider;
- (id)initWithURL:(id)url consumer:(id)consumer token:(id)token realm:(id)realm signatureProvider:(id)provider nonce:(id)nonce timestamp:(id)timestamp;
- (id)URLEncodedString:(id)string;
- (id)URLStringWithoutQueryFromURL:(id)url;
- (void)_generateNonce;
- (void)_generateTimestamp;
- (id)_signatureBaseString;
- (void)dealloc;
// declared property getter: - (id)nonce;
// declared property getter: - (id)parameters;
- (void)prepare;
// declared property setter: - (void)setParameters:(id)parameters;
// declared property getter: - (id)signature;
@end

