/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface OARequestParameter : NSObject {
	NSString *name;	// 4 = 0x4
	NSString *value;	// 8 = 0x8
}
@property(retain) NSString *name;	// @synthesize
@property(retain) NSString *value;	// @synthesize
+ (id)requestParameterWithName:(id)name value:(id)value;
- (id)initWithName:(id)name value:(id)value;
- (id)URLEncodedName;
- (id)URLEncodedNameValuePair;
- (id)URLEncodedValue;
- (void)dealloc;
// declared property getter: - (id)name;
// declared property setter: - (void)setName:(id)name;
// declared property setter: - (void)setValue:(id)value;
// declared property getter: - (id)value;
@end

