/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSURLResponse, OAMutableURLRequest;

@interface OAServiceTicket : NSObject {
	OAMutableURLRequest *request;	// 4 = 0x4
	NSURLResponse *response;	// 8 = 0x8
	BOOL didSucceed;	// 12 = 0xc
}
@property(assign) BOOL didSucceed;	// @synthesize
@property(retain) OAMutableURLRequest *request;	// @synthesize
@property(retain) NSURLResponse *response;	// @synthesize
- (id)initWithRequest:(id)request response:(id)response didSucceed:(BOOL)succeed;
- (void)dealloc;
// declared property getter: - (BOOL)didSucceed;
// declared property getter: - (id)request;
// declared property getter: - (id)response;
// declared property setter: - (void)setDidSucceed:(BOOL)succeed;
// declared property setter: - (void)setRequest:(id)request;
// declared property setter: - (void)setResponse:(id)response;
@end

