/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface OAToken : NSObject {
	NSString *pin;	// 4 = 0x4
	NSString *callback;	// 8 = 0x8
	NSString *key;	// 12 = 0xc
	NSString *secret;	// 16 = 0x10
}
@property(retain) NSString *callback;	// @synthesize
@property(retain) NSString *key;	// @synthesize
@property(retain) NSString *pin;	// @synthesize
@property(retain) NSString *secret;	// @synthesize
- (id)init;
- (id)initWithHTTPResponseBody:(id)httpresponseBody;
- (id)initWithKey:(id)key secret:(id)secret;
- (id)initWithUserDefaultsUsingServiceProviderName:(id)userDefaultsUsingServiceProviderName prefix:(id)prefix;
// declared property getter: - (id)callback;
- (void)dealloc;
// declared property getter: - (id)key;
// declared property getter: - (id)pin;
// declared property getter: - (id)secret;
// declared property setter: - (void)setCallback:(id)callback;
// declared property setter: - (void)setKey:(id)key;
// declared property setter: - (void)setPin:(id)pin;
// declared property setter: - (void)setSecret:(id)secret;
- (int)storeInUserDefaultsWithServiceProviderName:(id)serviceProviderName prefix:(id)prefix;
@end

