/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "SKRequestDelegate.h"


__attribute__((visibility("hidden")))
@interface ReceiptDelegate : NSObject <SKRequestDelegate> {
	int m_state;	// 4 = 0x4
}
- (int)getState;
- (void)request:(id)request didFailWithError:(id)error;
- (void)requestDidFinish:(id)request;
- (void)setState:(int)state;
@end

