/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RenrenMobileDelegate.h"
#import "RenrenLoginViewControllerDelegate.h"
#import "RMRequestContextDelegate.h"
#import "RMShareComponentDelegate.h"
#import </libobjc.A.h>

@class NSString, RMCommonContext;

@interface RenreniOSGLSocialLib : NSObject <RenrenMobileDelegate, RenrenLoginViewControllerDelegate, RMRequestContextDelegate, RMShareComponentDelegate> {
	RMCommonContext *friendDataRequest;	// 4 = 0x4
	RMCommonContext *userGetInfo;	// 8 = 0x8
	RMCommonContext *postToWallRequest;	// 12 = 0xc
	RMCommonContext *friendsInGameRequest;	// 16 = 0x10
	RMCommonContext *likeObjectRequest;	// 20 = 0x14
	NSString *dialogMsg;	// 24 = 0x18
	NSString *dialogPictureUrl;	// 28 = 0x1c
	NSString *dialogLink;	// 32 = 0x20
	NSString *dialogTitle;	// 36 = 0x24
	NSString *dialogDescription;	// 40 = 0x28
	bool isLoggedIn;	// 44 = 0x2c
}
@property(retain, nonatomic) NSString *dialogDescription;	// @synthesize
@property(retain, nonatomic) NSString *dialogLink;	// @synthesize
@property(retain, nonatomic) NSString *dialogMsg;	// @synthesize
@property(retain, nonatomic) NSString *dialogPictureUrl;	// @synthesize
@property(retain, nonatomic) NSString *dialogTitle;	// @synthesize
@property(retain, nonatomic) RMCommonContext *friendDataRequest;	// @synthesize
@property(retain, nonatomic) RMCommonContext *friendsInGameRequest;	// @synthesize
@property(assign, nonatomic) bool isLoggedIn;	// @synthesize
@property(retain, nonatomic) RMCommonContext *likeObjectRequest;	// @synthesize
@property(retain, nonatomic) RMCommonContext *postToWallRequest;	// @synthesize
@property(retain, nonatomic) RMCommonContext *userGetInfo;	// @synthesize
- (id)init;
- (void)context:(id)context didFailLoadWithError:(id)error;
- (void)contextDidCancelLoad:(id)context;
- (void)contextDidFinishLoad:(id)context;
- (void)contextDidStartLoad:(id)context;
- (void)dashboardDidAppear;
- (void)dashboardDidDisappear;
- (void)dashboardWillAppear;
- (void)dashboardWillDisappear;
- (void)dealloc;
// declared property getter: - (id)dialogDescription;
// declared property getter: - (id)dialogLink;
// declared property getter: - (id)dialogMsg;
// declared property getter: - (id)dialogPictureUrl;
// declared property getter: - (id)dialogTitle;
- (void)didCloseToLoginCancel;
- (void)didCloseToLoginError:(id)loginError;
- (void)didCloseToLoginSuccess;
- (void)didCloseToShareCancel;
- (void)didCloseToShareSuccess;
// declared property getter: - (id)friendDataRequest;
// declared property getter: - (id)friendsInGameRequest;
- (BOOL)handleOpenURL:(id)url;
// declared property getter: - (bool)isLoggedIn;
// declared property getter: - (id)likeObjectRequest;
// declared property getter: - (id)postToWallRequest;
- (void)reAuthVerifyUserFailWithError:(id)error;
- (id)renreniOSGLSocialLib_getAppSecret;
- (void)renreniOSGLSocialLib_getFriends;
- (void)renreniOSGLSocialLib_getFriendsDataWithPage:(int)page andPageSize:(int)size;
- (void)renreniOSGLSocialLib_getFriendsInGame;
- (void)renreniOSGLSocialLib_getFriendsWithType:(int)type;
- (id)renreniOSGLSocialLib_getMyInfo;
- (id)renreniOSGLSocialLib_getMyName;
- (id)renreniOSGLSocialLib_getMyUid;
- (id)renreniOSGLSocialLib_getPicture:(int)picture;
- (void)renreniOSGLSocialLib_getUserData:(id)data;
- (BOOL)renreniOSGLSocialLib_isLoggedIn;
- (void)renreniOSGLSocialLib_likeObject:(id)object;
- (void)renreniOSGLSocialLib_login;
- (void)renreniOSGLSocialLib_logout;
- (void)renreniOSGLSocialLib_postPhotoToWall:(id)wall;
- (void)renreniOSGLSocialLib_postToWall;
- (void)renreniOSGLSocialLib_postToWallWithoutDialog;
// declared property setter: - (void)setDialogDescription:(id)description;
// declared property setter: - (void)setDialogLink:(id)link;
// declared property setter: - (void)setDialogMsg:(id)msg;
// declared property setter: - (void)setDialogPictureUrl:(id)url;
// declared property setter: - (void)setDialogTitle:(id)title;
// declared property setter: - (void)setFriendDataRequest:(id)request;
// declared property setter: - (void)setFriendsInGameRequest:(id)gameRequest;
// declared property setter: - (void)setIsLoggedIn:(bool)anIn;
// declared property setter: - (void)setLikeObjectRequest:(id)request;
// declared property setter: - (void)setPostToWallRequest:(id)wallRequest;
// declared property setter: - (void)setUserGetInfo:(id)info;
// declared property getter: - (id)userGetInfo;
@end

