/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMCommonContext.h"

@class RMGetResultResponse;

@interface RMActionLogContext : RMCommonContext {
	RMGetResultResponse *response;	// 16 = 0x10
}
- (id)init;
- (void)asynActionLog:(id)log fromId:(id)anId terminal:(id)terminal version:(id)version;
- (void)dealloc;
- (void)didCancelLoad;
- (void)didFailLoadWithError:(id)error;
- (void)didFinishLoad;
- (void)didStartLoad;
- (void)generateResponse;
- (id)getContextResponse;
- (BOOL)synActionLog:(id)log fromId:(id)anId terminal:(id)terminal version:(id)version error:(id *)error;
@end

