/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMCommonContext.h"


@interface RMAppGetInfoContext : RMCommonContext {
}
- (void)asynAppInfo;
- (void)didCancelLoad;
- (void)didFailLoadWithError:(id)error;
- (void)didFinishLoad;
- (void)didStartLoad;
- (void)generateResponse;
@end

