/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol RMASIHTTPRequestDelegate <NSObject>
@optional
- (void)authenticationNeededForRequest:(id)request;
- (void)proxyAuthenticationNeededForRequest:(id)request;
- (void)request:(id)request didReceiveData:(id)data;
- (void)request:(id)request didReceiveResponseHeaders:(id)headers;
- (void)request:(id)request willRedirectToURL:(id)url;
- (void)requestFailed:(id)failed;
- (void)requestFinished:(id)finished;
- (void)requestRedirected:(id)redirected;
- (void)requestStarted:(id)started;
@end

