/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "ModernCombat5-Structs.h"
#import "RMASIAutorotatingViewController.h"

@class RMASIHTTPRequest, UITableView;

@interface RMASIAuthenticationDialog : RMASIAutorotatingViewController <UIActionSheetDelegate, UITableViewDelegate, UITableViewDataSource> {
	RMASIHTTPRequest *request;	// 160 = 0xa0
	int type;	// 164 = 0xa4
	UITableView *tableView;	// 168 = 0xa8
	UIViewController *presentingController;	// 172 = 0xac
	BOOL didEnableRotationNotifications;	// 176 = 0xb0
}
@property(assign) BOOL didEnableRotationNotifications;	// @synthesize
@property(retain, nonatomic) UIViewController *presentingController;	// @synthesize
@property(retain) RMASIHTTPRequest *request;	// @synthesize
@property(retain) UITableView *tableView;	// @synthesize
@property(assign) int type;	// @synthesize
+ (void)dismiss;
+ (void)initialize;
+ (void)presentAuthenticationDialogForRequest:(id)request;
- (id)init;
- (void)cancelAuthenticationFromDialog:(id)dialog;
- (void)dealloc;
// declared property getter: - (BOOL)didEnableRotationNotifications;
- (void)dismiss;
- (id)domainField;
- (void)keyboardWillShow:(id)keyboard;
- (void)loginWithCredentialsFromDialog:(id)dialog;
- (int)numberOfSectionsInTableView:(id)tableView;
- (void)orientationChanged:(id)changed;
- (id)passwordField;
- (void)presentNextDialog;
// declared property getter: - (id)presentingController;
// declared property getter: - (id)request;
- (id)requestsRequiringTheseCredentials;
// declared property setter: - (void)setDidEnableRotationNotifications:(BOOL)enableRotationNotifications;
// declared property setter: - (void)setPresentingController:(id)controller;
// declared property setter: - (void)setRequest:(id)request;
// declared property setter: - (void)setTableView:(id)view;
// declared property setter: - (void)setType:(int)type;
- (void)show;
- (void)showTitle;
// declared property getter: - (id)tableView;
- (id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
- (float)tableView:(id)view heightForFooterInSection:(int)section;
- (float)tableView:(id)view heightForHeaderInSection:(int)section;
- (int)tableView:(id)view numberOfRowsInSection:(int)section;
- (id)tableView:(id)view titleForFooterInSection:(int)section;
- (id)tableView:(id)view titleForHeaderInSection:(int)section;
- (id)textFieldInRow:(unsigned)row section:(unsigned)section;
// declared property getter: - (int)type;
- (id)usernameField;
- (void)viewDidDisappear:(BOOL)view;
@end

