/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>


@interface RMASIAutorotatingViewController : UIViewController {
}
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
@end

