/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import "NSCopying.h"
#import <Foundation/NSOperation.h>

@class NSURL, NSRecursiveLock, NSDictionary, NSNumber, NSString, NSData, RMASIDataDecompressor, NSMutableArray, NSArray, NSDate, NSTimer, NSMutableData, NSError, NSOutputStream, NSMutableDictionary, NSInputStream;
@protocol RMASICacheDelegate, RMASIHTTPRequestDelegate, RMASIProgressDelegate;

@interface RMASIHTTPRequest : NSOperation <NSCopying> {
	NSURL *url;	// 12 = 0xc
	NSURL *originalURL;	// 16 = 0x10
	NSURL *redirectURL;	// 20 = 0x14
	id<RMASIHTTPRequestDelegate> delegate;	// 24 = 0x18
	id<RMASIHTTPRequestDelegate, RMASIProgressDelegate> queue;	// 28 = 0x1c
	NSString *requestMethod;	// 32 = 0x20
	NSMutableData *postBody;	// 36 = 0x24
	NSData *compressedPostBody;	// 40 = 0x28
	BOOL shouldStreamPostDataFromDisk;	// 44 = 0x2c
	NSString *postBodyFilePath;	// 48 = 0x30
	NSString *compressedPostBodyFilePath;	// 52 = 0x34
	BOOL didCreateTemporaryPostDataFile;	// 56 = 0x38
	NSOutputStream *postBodyWriteStream;	// 60 = 0x3c
	NSInputStream *postBodyReadStream;	// 64 = 0x40
	NSMutableDictionary *requestHeaders;	// 68 = 0x44
	BOOL haveBuiltRequestHeaders;	// 72 = 0x48
	NSDictionary *responseHeaders;	// 76 = 0x4c
	NSMutableArray *requestCookies;	// 80 = 0x50
	NSArray *responseCookies;	// 84 = 0x54
	BOOL useCookiePersistence;	// 88 = 0x58
	BOOL useKeychainPersistence;	// 89 = 0x59
	BOOL useSessionPersistence;	// 90 = 0x5a
	BOOL allowCompressedResponse;	// 91 = 0x5b
	BOOL shouldCompressRequestBody;	// 92 = 0x5c
	NSString *downloadDestinationPath;	// 96 = 0x60
	NSString *temporaryFileDownloadPath;	// 100 = 0x64
	NSString *temporaryUncompressedDataDownloadPath;	// 104 = 0x68
	NSOutputStream *fileDownloadOutputStream;	// 108 = 0x6c
	NSOutputStream *inflatedFileDownloadOutputStream;	// 112 = 0x70
	BOOL complete;	// 116 = 0x74
	BOOL finished;	// 117 = 0x75
	BOOL cancelled;	// 118 = 0x76
	NSError *error;	// 120 = 0x78
	NSString *username;	// 124 = 0x7c
	NSString *password;	// 128 = 0x80
	NSString *userAgent;	// 132 = 0x84
	NSString *domain;	// 136 = 0x88
	NSString *proxyUsername;	// 140 = 0x8c
	NSString *proxyPassword;	// 144 = 0x90
	NSString *proxyDomain;	// 148 = 0x94
	id<RMASIProgressDelegate> uploadProgressDelegate;	// 152 = 0x98
	id<RMASIProgressDelegate> downloadProgressDelegate;	// 156 = 0x9c
	BOOL haveExaminedHeaders;	// 160 = 0xa0
	NSMutableData *rawResponseData;	// 164 = 0xa4
	CFHTTPMessageRef request;	// 168 = 0xa8
	NSInputStream *readStream;	// 172 = 0xac
	CFHTTPAuthenticationRef requestAuthentication;	// 176 = 0xb0
	NSDictionary *requestCredentials;	// 180 = 0xb4
	int authenticationRetryCount;	// 184 = 0xb8
	NSString *authenticationScheme;	// 188 = 0xbc
	NSString *authenticationRealm;	// 192 = 0xc0
	BOOL shouldPresentAuthenticationDialog;	// 196 = 0xc4
	BOOL shouldPresentProxyAuthenticationDialog;	// 197 = 0xc5
	CFHTTPAuthenticationRef proxyAuthentication;	// 200 = 0xc8
	NSDictionary *proxyCredentials;	// 204 = 0xcc
	int proxyAuthenticationRetryCount;	// 208 = 0xd0
	NSString *proxyAuthenticationScheme;	// 212 = 0xd4
	NSString *proxyAuthenticationRealm;	// 216 = 0xd8
	int responseStatusCode;	// 220 = 0xdc
	NSString *responseStatusMessage;	// 224 = 0xe0
	unsigned long long contentLength;	// 228 = 0xe4
	unsigned long long partialDownloadSize;	// 236 = 0xec
	unsigned long long postLength;	// 244 = 0xf4
	unsigned long long totalBytesRead;	// 252 = 0xfc
	unsigned long long totalBytesSent;	// 260 = 0x104
	unsigned long long lastBytesRead;	// 268 = 0x10c
	unsigned long long lastBytesSent;	// 276 = 0x114
	NSRecursiveLock *cancelledLock;	// 284 = 0x11c
	SEL didStartSelector;	// 288 = 0x120
	SEL didReceiveResponseHeadersSelector;	// 292 = 0x124
	SEL willRedirectSelector;	// 296 = 0x128
	SEL didFinishSelector;	// 300 = 0x12c
	SEL didFailSelector;	// 304 = 0x130
	SEL didReceiveDataSelector;	// 308 = 0x134
	NSDate *lastActivityTime;	// 312 = 0x138
	double timeOutSeconds;	// 316 = 0x13c
	BOOL shouldResetUploadProgress;	// 324 = 0x144
	BOOL shouldResetDownloadProgress;	// 325 = 0x145
	RMASIHTTPRequest *mainRequest;	// 328 = 0x148
	BOOL showAccurateProgress;	// 332 = 0x14c
	BOOL updatedProgress;	// 333 = 0x14d
	BOOL haveBuiltPostBody;	// 334 = 0x14e
	unsigned long long uploadBufferSize;	// 336 = 0x150
	unsigned defaultResponseEncoding;	// 344 = 0x158
	unsigned responseEncoding;	// 348 = 0x15c
	BOOL allowResumeForFileDownloads;	// 352 = 0x160
	NSDictionary *userInfo;	// 356 = 0x164
	int tag;	// 360 = 0x168
	BOOL useHTTPVersionOne;	// 364 = 0x16c
	BOOL shouldRedirect;	// 365 = 0x16d
	BOOL needsRedirect;	// 366 = 0x16e
	int redirectCount;	// 368 = 0x170
	BOOL validatesSecureCertificate;	// 372 = 0x174
	SecIdentity *clientCertificateIdentity;	// 376 = 0x178
	NSArray *clientCertificates;	// 380 = 0x17c
	NSString *proxyHost;	// 384 = 0x180
	int proxyPort;	// 388 = 0x184
	NSString *proxyType;	// 392 = 0x188
	NSURL *PACurl;	// 396 = 0x18c
	int authenticationNeeded;	// 400 = 0x190
	BOOL shouldPresentCredentialsBeforeChallenge;	// 404 = 0x194
	BOOL inProgress;	// 405 = 0x195
	BOOL readStreamIsScheduled;	// 406 = 0x196
	int numberOfTimesToRetryOnTimeout;	// 408 = 0x198
	int retryCount;	// 412 = 0x19c
	BOOL willRetryRequest;	// 416 = 0x1a0
	BOOL shouldAttemptPersistentConnection;	// 417 = 0x1a1
	double persistentConnectionTimeoutSeconds;	// 420 = 0x1a4
	BOOL connectionCanBeReused;	// 428 = 0x1ac
	NSMutableDictionary *connectionInfo;	// 432 = 0x1b0
	BOOL shouldUseRFC2616RedirectBehaviour;	// 436 = 0x1b4
	BOOL downloadComplete;	// 437 = 0x1b5
	NSNumber *requestID;	// 440 = 0x1b8
	NSString *runLoopMode;	// 444 = 0x1bc
	NSTimer *statusTimer;	// 448 = 0x1c0
	id<RMASICacheDelegate> downloadCache;	// 452 = 0x1c4
	int cachePolicy;	// 456 = 0x1c8
	int cacheStoragePolicy;	// 460 = 0x1cc
	BOOL didUseCachedResponse;	// 464 = 0x1d0
	double secondsToCache;	// 468 = 0x1d4
	BOOL shouldContinueWhenAppEntersBackground;	// 476 = 0x1dc
	unsigned backgroundTask;	// 480 = 0x1e0
	RMASIDataDecompressor *dataDecompressor;	// 484 = 0x1e4
	BOOL shouldWaitToInflateCompressedResponses;	// 488 = 0x1e8
	BOOL isPACFileRequest;	// 489 = 0x1e9
	RMASIHTTPRequest *PACFileRequest;	// 492 = 0x1ec
	NSInputStream *PACFileReadStream;	// 496 = 0x1f0
	NSMutableData *PACFileData;	// 500 = 0x1f4
	BOOL isSynchronous;	// 504 = 0x1f8
	id startedBlock;	// 508 = 0x1fc
	id headersReceivedBlock;	// 512 = 0x200
	id completionBlock;	// 516 = 0x204
	id failureBlock;	// 520 = 0x208
	id bytesReceivedBlock;	// 524 = 0x20c
	id bytesSentBlock;	// 528 = 0x210
	id downloadSizeIncrementedBlock;	// 532 = 0x214
	id uploadSizeIncrementedBlock;	// 536 = 0x218
	id dataReceivedBlock;	// 540 = 0x21c
	id authenticationNeededBlock;	// 544 = 0x220
	id proxyAuthenticationNeededBlock;	// 548 = 0x224
	id requestRedirectedBlock;	// 552 = 0x228
}
@property(retain, nonatomic) NSMutableData *PACFileData;	// @synthesize
@property(retain, nonatomic) NSInputStream *PACFileReadStream;	// @synthesize
@property(retain, nonatomic) RMASIHTTPRequest *PACFileRequest;	// @synthesize
@property(retain) NSURL *PACurl;	// @synthesize
@property(assign) BOOL allowCompressedResponse;	// @synthesize
@property(assign) BOOL allowResumeForFileDownloads;	// @synthesize
@property(assign) int authenticationNeeded;	// @synthesize
@property(retain) NSString *authenticationRealm;	// @synthesize
@property(assign) int authenticationRetryCount;	// @synthesize
@property(retain) NSString *authenticationScheme;	// @synthesize
@property(assign) int cachePolicy;	// @synthesize
@property(assign) int cacheStoragePolicy;	// @synthesize
@property(retain) NSRecursiveLock *cancelledLock;	// @synthesize
@property(retain) NSArray *clientCertificates;	// @synthesize
@property(assign) BOOL complete;	// @synthesize
@property(retain, nonatomic) NSData *compressedPostBody;	// @synthesize
@property(retain, nonatomic) NSString *compressedPostBodyFilePath;	// @synthesize
@property(assign) BOOL connectionCanBeReused;	// @synthesize
@property(retain, nonatomic) NSMutableDictionary *connectionInfo;	// @synthesize
@property(assign) unsigned long long contentLength;	// @synthesize
@property(retain) RMASIDataDecompressor *dataDecompressor;	// @synthesize
@property(assign) unsigned defaultResponseEncoding;	// @synthesize
@property(assign, nonatomic) id delegate;	// @synthesize
@property(assign) BOOL didCreateTemporaryPostDataFile;	// @synthesize
@property(assign) SEL didFailSelector;	// @synthesize
@property(assign) SEL didFinishSelector;	// @synthesize
@property(assign) SEL didReceiveDataSelector;	// @synthesize
@property(assign) SEL didReceiveResponseHeadersSelector;	// @synthesize
@property(assign) SEL didStartSelector;	// @synthesize
@property(assign) BOOL didUseCachedResponse;	// @synthesize
@property(retain) NSString *domain;	// @synthesize
@property(assign) id<RMASICacheDelegate> downloadCache;	// @synthesize
@property(assign, nonatomic) BOOL downloadComplete;	// @synthesize
@property(retain) NSString *downloadDestinationPath;	// @synthesize
@property(assign, nonatomic) id downloadProgressDelegate;	// @synthesize
@property(retain) NSError *error;	// @synthesize
@property(retain, nonatomic) NSOutputStream *fileDownloadOutputStream;	// @synthesize
@property(assign, nonatomic) BOOL haveBuiltPostBody;	// @synthesize
@property(assign) BOOL haveBuiltRequestHeaders;	// @synthesize
@property(assign) BOOL inProgress;	// @synthesize
@property(retain, nonatomic) NSOutputStream *inflatedFileDownloadOutputStream;	// @synthesize
@property(assign, nonatomic) BOOL isPACFileRequest;	// @synthesize
@property(assign, nonatomic, setter=setSynchronous:) BOOL isSynchronous;	// @synthesize
@property(retain, nonatomic) NSDate *lastActivityTime;	// @synthesize
@property(assign, nonatomic) unsigned long long lastBytesRead;	// @synthesize
@property(assign, nonatomic) unsigned long long lastBytesSent;	// @synthesize
@property(assign) RMASIHTTPRequest *mainRequest;	// @synthesize
@property(assign, nonatomic) BOOL needsRedirect;	// @synthesize
@property(assign) int numberOfTimesToRetryOnTimeout;	// @synthesize
@property(retain) NSURL *originalURL;	// @synthesize
@property(assign) unsigned long long partialDownloadSize;	// @synthesize
@property(retain) NSString *password;	// @synthesize
@property(assign) double persistentConnectionTimeoutSeconds;	// @synthesize
@property(retain) NSMutableData *postBody;	// @synthesize
@property(retain) NSString *postBodyFilePath;	// @synthesize
@property(retain, nonatomic) NSInputStream *postBodyReadStream;	// @synthesize
@property(retain, nonatomic) NSOutputStream *postBodyWriteStream;	// @synthesize
@property(assign) unsigned long long postLength;	// @synthesize
@property(retain) NSString *proxyAuthenticationRealm;	// @synthesize
@property(assign) int proxyAuthenticationRetryCount;	// @synthesize
@property(retain) NSString *proxyAuthenticationScheme;	// @synthesize
@property(retain) NSDictionary *proxyCredentials;	// @synthesize
@property(retain) NSString *proxyDomain;	// @synthesize
@property(retain) NSString *proxyHost;	// @synthesize
@property(retain) NSString *proxyPassword;	// @synthesize
@property(assign) int proxyPort;	// @synthesize
@property(retain) NSString *proxyType;	// @synthesize
@property(retain) NSString *proxyUsername;	// @synthesize
@property(retain, nonatomic) id queue;	// @synthesize
@property(retain) NSMutableData *rawResponseData;	// @synthesize
@property(retain, nonatomic) NSInputStream *readStream;	// @synthesize
@property(assign, nonatomic) BOOL readStreamIsScheduled;	// @synthesize
@property(assign, nonatomic) int redirectCount;	// @synthesize
@property(retain, nonatomic) NSURL *redirectURL;	// @synthesize
@property(retain) NSMutableArray *requestCookies;	// @synthesize
@property(retain) NSDictionary *requestCredentials;	// @synthesize
@property(retain) NSMutableDictionary *requestHeaders;	// @synthesize
@property(retain) NSNumber *requestID;	// @synthesize
@property(retain, nonatomic) NSString *requestMethod;	// @synthesize
@property(retain) NSArray *responseCookies;	// @synthesize
@property(assign) unsigned responseEncoding;	// @synthesize
@property(retain) NSDictionary *responseHeaders;	// @synthesize
@property(assign) int responseStatusCode;	// @synthesize
@property(retain) NSString *responseStatusMessage;	// @synthesize
@property(assign) int retryCount;	// @synthesize
@property(assign, nonatomic) NSString *runLoopMode;	// @synthesize
@property(assign) double secondsToCache;	// @synthesize
@property(assign) BOOL shouldAttemptPersistentConnection;	// @synthesize
@property(assign) BOOL shouldCompressRequestBody;	// @synthesize
@property(assign) BOOL shouldContinueWhenAppEntersBackground;	// @synthesize
@property(assign) BOOL shouldPresentAuthenticationDialog;	// @synthesize
@property(assign) BOOL shouldPresentCredentialsBeforeChallenge;	// @synthesize
@property(assign) BOOL shouldPresentProxyAuthenticationDialog;	// @synthesize
@property(assign) BOOL shouldRedirect;	// @synthesize
@property(assign) BOOL shouldResetDownloadProgress;	// @synthesize
@property(assign) BOOL shouldResetUploadProgress;	// @synthesize
@property(assign) BOOL shouldStreamPostDataFromDisk;	// @synthesize
@property(assign) BOOL shouldUseRFC2616RedirectBehaviour;	// @synthesize
@property(assign) BOOL shouldWaitToInflateCompressedResponses;	// @synthesize
@property(assign) BOOL showAccurateProgress;	// @synthesize
@property(retain, nonatomic) NSTimer *statusTimer;	// @synthesize
@property(assign) int tag;	// @synthesize
@property(retain) NSString *temporaryFileDownloadPath;	// @synthesize
@property(retain) NSString *temporaryUncompressedDataDownloadPath;	// @synthesize
@property(assign) double timeOutSeconds;	// @synthesize
@property(assign) unsigned long long totalBytesRead;	// @synthesize
@property(assign) unsigned long long totalBytesSent;	// @synthesize
@property(assign, nonatomic) BOOL updatedProgress;	// @synthesize
@property(assign, nonatomic) unsigned long long uploadBufferSize;	// @synthesize
@property(assign, nonatomic) id uploadProgressDelegate;	// @synthesize
@property(retain, nonatomic, setter=setURL:) NSURL *url;	// @synthesize
@property(assign) BOOL useCookiePersistence;	// @synthesize
@property(assign) BOOL useHTTPVersionOne;	// @synthesize
@property(assign) BOOL useKeychainPersistence;	// @synthesize
@property(assign) BOOL useSessionPersistence;	// @synthesize
@property(retain) NSString *userAgent;	// @synthesize
@property(retain) NSDictionary *userInfo;	// @synthesize
@property(retain) NSString *username;	// @synthesize
@property(assign) BOOL validatesSecureCertificate;	// @synthesize
@property(assign) SEL willRedirectSelector;	// @synthesize
@property(assign) BOOL willRetryRequest;	// @synthesize
+ (void)addSessionCookie:(id)cookie;
+ (unsigned long)averageBandwidthUsedPerSecond;
+ (id)base64forData:(id)data;
+ (void)clearSession;
+ (id)dateFromRFC1123String:(id)rfc1123String;
+ (id)defaultCache;
+ (double)defaultTimeOutSeconds;
+ (id)defaultUserAgentString;
+ (void)expirePersistentConnections;
+ (id)expiryDateForRequest:(id)request maxAge:(double)age;
+ (void)hideNetworkActivityIndicator;
+ (void)hideNetworkActivityIndicatorAfterDelay;
+ (void)hideNetworkActivityIndicatorIfNeeeded;
+ (void)incrementBandwidthUsedInLastSecond:(unsigned long)lastSecond;
+ (void)initialize;
+ (BOOL)isBandwidthThrottled;
+ (BOOL)isMultitaskingSupported;
+ (BOOL)isNetworkInUse;
+ (BOOL)isNetworkReachableViaWWAN;
+ (unsigned long)maxBandwidthPerSecond;
+ (unsigned long)maxUploadReadLength;
+ (void)measureBandwidthUsage;
+ (id)mimeTypeForFileAtPath:(id)path;
+ (void)parseMimeType:(id *)type andResponseEncoding:(unsigned *)encoding fromContentType:(id)contentType;
+ (void)performInvocation:(id)invocation onTarget:(id *)target releasingObject:(id)object;
+ (void)performSelector:(SEL)selector onTarget:(id *)target withObject:(id)object amount:(void *)amount callerToRetain:(id)retain;
+ (void)reachabilityChanged:(id)changed;
+ (void)recordBandwidthUsage;
+ (void)registerForNetworkReachabilityNotifications;
+ (void)releaseBlocks:(id)blocks;
+ (void)removeAuthenticationCredentialsFromSessionStore:(id)sessionStore;
+ (void)removeCredentialsForHost:(id)host port:(int)port protocol:(id)protocol realm:(id)realm;
+ (void)removeCredentialsForProxy:(id)proxy port:(int)port realm:(id)realm;
+ (BOOL)removeFileAtPath:(id)path error:(id *)error;
+ (void)removeProxyAuthenticationCredentialsFromSessionStore:(id)sessionStore;
+ (id)requestWithURL:(id)url;
+ (id)requestWithURL:(id)url usingCache:(id)cache;
+ (id)requestWithURL:(id)url usingCache:(id)cache andCachePolicy:(int)policy;
+ (void)runRequests;
+ (void)saveCredentials:(id)credentials forHost:(id)host port:(int)port protocol:(id)protocol realm:(id)realm;
+ (void)saveCredentials:(id)credentials forProxy:(id)proxy port:(int)port realm:(id)realm;
+ (id)savedCredentialsForHost:(id)host port:(int)port protocol:(id)protocol realm:(id)realm;
+ (id)savedCredentialsForProxy:(id)proxy port:(int)port protocol:(id)protocol realm:(id)realm;
+ (id)sessionCookies;
+ (id)sessionCredentialsStore;
+ (id)sessionProxyCredentialsStore;
+ (void)setDefaultCache:(id)cache;
+ (void)setDefaultTimeOutSeconds:(double)seconds;
+ (void)setDefaultUserAgentString:(id)string;
+ (void)setMaxBandwidthPerSecond:(unsigned long)second;
+ (void)setSessionCookies:(id)cookies;
+ (void)setShouldThrottleBandwidthForWWAN:(BOOL)throttleBandwidthForWWAN;
+ (void)setShouldUpdateNetworkActivityIndicator:(BOOL)updateNetworkActivityIndicator;
+ (id)sharedQueue;
+ (void)showNetworkActivityIndicator;
+ (void)storeAuthenticationCredentialsInSessionStore:(id)sessionStore;
+ (void)storeProxyAuthenticationCredentialsInSessionStore:(id)sessionStore;
+ (id)threadForRequest:(id)request;
+ (void)throttleBandwidthForWWANUsingLimit:(unsigned long)wwanusingLimit;
+ (void)unsubscribeFromNetworkReachabilityNotifications;
+ (void)updateProgressIndicator:(id *)indicator withProgress:(unsigned long long)progress ofTotal:(unsigned long long)total;
- (id)initWithURL:(id)url;
- (id)HEADRequest;
// declared property getter: - (id)PACFileData;
// declared property getter: - (id)PACFileReadStream;
// declared property getter: - (id)PACFileRequest;
// declared property getter: - (id)PACurl;
- (void)addBasicAuthenticationHeaderWithUsername:(id)username andPassword:(id)password;
- (void)addRequestHeader:(id)header value:(id)value;
// declared property getter: - (BOOL)allowCompressedResponse;
// declared property getter: - (BOOL)allowResumeForFileDownloads;
- (void)appendPostData:(id)data;
- (void)appendPostDataFromFile:(id)file;
- (void)applyAuthorizationHeader;
- (void)applyCookieHeader;
- (BOOL)applyCredentials:(id)credentials;
- (BOOL)applyProxyCredentials:(id)credentials;
- (void)askDelegateForCredentials;
- (void)askDelegateForProxyCredentials;
- (void)attemptToApplyCredentialsAndResume;
- (void)attemptToApplyProxyCredentialsAndResume;
// declared property getter: - (int)authenticationNeeded;
// declared property getter: - (id)authenticationRealm;
// declared property getter: - (int)authenticationRetryCount;
// declared property getter: - (id)authenticationScheme;
- (void)buildPostBody;
- (void)buildRequestHeaders;
// declared property getter: - (int)cachePolicy;
// declared property getter: - (int)cacheStoragePolicy;
- (void)callBlock:(id)block;
- (void)cancel;
- (void)cancelAuthentication;
- (void)cancelLoad;
- (void)cancelOnRequestThread;
// declared property getter: - (id)cancelledLock;
- (void)checkRequestStatus;
- (void)clearDelegatesAndCancel;
// declared property getter: - (id)clientCertificates;
// declared property getter: - (BOOL)complete;
// declared property getter: - (id)compressedPostBody;
// declared property getter: - (id)compressedPostBodyFilePath;
- (BOOL)configureProxies;
// declared property getter: - (BOOL)connectionCanBeReused;
- (id)connectionID;
// declared property getter: - (id)connectionInfo;
// declared property getter: - (unsigned long long)contentLength;
- (id)copyWithZone:(NSZone *)zone;
// declared property getter: - (id)dataDecompressor;
- (void)dealloc;
// declared property getter: - (unsigned)defaultResponseEncoding;
// declared property getter: - (id)delegate;
- (void)destroyReadStream;
// declared property getter: - (BOOL)didCreateTemporaryPostDataFile;
// declared property getter: - (SEL)didFailSelector;
// declared property getter: - (SEL)didFinishSelector;
// declared property getter: - (SEL)didReceiveDataSelector;
// declared property getter: - (SEL)didReceiveResponseHeadersSelector;
// declared property getter: - (SEL)didStartSelector;
// declared property getter: - (BOOL)didUseCachedResponse;
// declared property getter: - (id)domain;
// declared property getter: - (id)downloadCache;
// declared property getter: - (BOOL)downloadComplete;
// declared property getter: - (id)downloadDestinationPath;
// declared property getter: - (id)downloadProgressDelegate;
// declared property getter: - (id)error;
- (void)failAuthentication;
- (void)failWithError:(id)error;
- (void)fetchPACFile;
// declared property getter: - (id)fileDownloadOutputStream;
- (id)findCredentials;
- (id)findProxyCredentials;
- (id)findSessionAuthenticationCredentials;
- (id)findSessionProxyAuthenticationCredentials;
- (void)finishedDownloadingPACFile:(id)file;
- (void)handleBytesAvailable;
- (void)handleNetworkEvent:(unsigned long)event;
- (void)handleStreamComplete;
- (void)handleStreamError;
// declared property getter: - (BOOL)haveBuiltPostBody;
// declared property getter: - (BOOL)haveBuiltRequestHeaders;
// declared property getter: - (BOOL)inProgress;
- (void)incrementDownloadSizeBy:(long long)by;
- (void)incrementUploadSizeBy:(long long)by;
// declared property getter: - (id)inflatedFileDownloadOutputStream;
- (BOOL)isCancelled;
- (BOOL)isConcurrent;
- (BOOL)isExecuting;
- (BOOL)isFinished;
// declared property getter: - (BOOL)isPACFileRequest;
- (BOOL)isResponseCompressed;
// declared property getter: - (BOOL)isSynchronous;
// declared property getter: - (id)lastActivityTime;
// declared property getter: - (unsigned long long)lastBytesRead;
// declared property getter: - (unsigned long long)lastBytesSent;
- (void)main;
// declared property getter: - (id)mainRequest;
- (void)markAsFinished;
// declared property getter: - (BOOL)needsRedirect;
// declared property getter: - (int)numberOfTimesToRetryOnTimeout;
// declared property getter: - (id)originalURL;
- (void)parseStringEncodingFromHeaders;
// declared property getter: - (unsigned long long)partialDownloadSize;
- (void)passOnReceivedData:(id)data;
// declared property getter: - (id)password;
- (void)performBlockOnMainThread:(id)thread;
- (void)performRedirect;
- (void)performThrottling;
// declared property getter: - (double)persistentConnectionTimeoutSeconds;
// declared property getter: - (id)postBody;
// declared property getter: - (id)postBodyFilePath;
// declared property getter: - (id)postBodyReadStream;
// declared property getter: - (id)postBodyWriteStream;
// declared property getter: - (unsigned long long)postLength;
// declared property getter: - (id)proxyAuthenticationRealm;
// declared property getter: - (int)proxyAuthenticationRetryCount;
// declared property getter: - (id)proxyAuthenticationScheme;
// declared property getter: - (id)proxyCredentials;
// declared property getter: - (id)proxyDomain;
// declared property getter: - (id)proxyHost;
// declared property getter: - (id)proxyPassword;
// declared property getter: - (int)proxyPort;
// declared property getter: - (id)proxyType;
// declared property getter: - (id)proxyUsername;
// declared property getter: - (id)queue;
// declared property getter: - (id)rawResponseData;
- (void)readResponseHeaders;
// declared property getter: - (id)readStream;
// declared property getter: - (BOOL)readStreamIsScheduled;
// declared property getter: - (int)redirectCount;
- (void)redirectToURL:(id)url;
// declared property getter: - (id)redirectURL;
- (void)releaseBlocksOnMainThread;
- (BOOL)removeTemporaryCompressedUploadFile;
- (BOOL)removeTemporaryDownloadFile;
- (BOOL)removeTemporaryUncompressedDownloadFile;
- (BOOL)removeTemporaryUploadFile;
- (void)removeUploadProgressSoFar;
- (void)reportFailure;
- (void)reportFinished;
// declared property getter: - (id)requestCookies;
// declared property getter: - (id)requestCredentials;
- (void)requestFinished;
// declared property getter: - (id)requestHeaders;
// declared property getter: - (id)requestID;
// declared property getter: - (id)requestMethod;
- (void)requestReceivedResponseHeaders:(id)headers;
- (void)requestRedirected;
- (void)requestStarted;
- (void)requestWillRedirectToURL:(id)request;
// declared property getter: - (id)responseCookies;
- (id)responseData;
// declared property getter: - (unsigned)responseEncoding;
// declared property getter: - (id)responseHeaders;
// declared property getter: - (int)responseStatusCode;
// declared property getter: - (id)responseStatusMessage;
- (id)responseString;
// declared property getter: - (int)retryCount;
- (BOOL)retryUsingNewConnection;
- (void)retryUsingSuppliedCredentials;
// declared property getter: - (id)runLoopMode;
- (void)runPACScript:(id)script;
- (void)saveCredentialsToKeychain:(id)keychain;
- (void)saveProxyCredentialsToKeychain:(id)keychain;
- (void)scheduleReadStream;
// declared property getter: - (double)secondsToCache;
// declared property setter: - (void)setAllowCompressedResponse:(BOOL)response;
// declared property setter: - (void)setAllowResumeForFileDownloads:(BOOL)fileDownloads;
// declared property setter: - (void)setAuthenticationNeeded:(int)needed;
- (void)setAuthenticationNeededBlock:(id)block;
// declared property setter: - (void)setAuthenticationRealm:(id)realm;
// declared property setter: - (void)setAuthenticationRetryCount:(int)count;
// declared property setter: - (void)setAuthenticationScheme:(id)scheme;
- (void)setBytesReceivedBlock:(id)block;
- (void)setBytesSentBlock:(id)block;
// declared property setter: - (void)setCachePolicy:(int)policy;
// declared property setter: - (void)setCacheStoragePolicy:(int)policy;
// declared property setter: - (void)setCancelledLock:(id)lock;
- (void)setClientCertificateIdentity:(SecIdentity *)identity;
// declared property setter: - (void)setClientCertificates:(id)certificates;
// declared property setter: - (void)setComplete:(BOOL)complete;
- (void)setCompletionBlock:(id)block;
// declared property setter: - (void)setCompressedPostBody:(id)body;
// declared property setter: - (void)setCompressedPostBodyFilePath:(id)path;
// declared property setter: - (void)setConnectionCanBeReused:(BOOL)reused;
// declared property setter: - (void)setConnectionInfo:(id)info;
// declared property setter: - (void)setContentLength:(unsigned long long)length;
// declared property setter: - (void)setDataDecompressor:(id)decompressor;
- (void)setDataReceivedBlock:(id)block;
// declared property setter: - (void)setDefaultResponseEncoding:(unsigned)encoding;
// declared property setter: - (void)setDelegate:(id)delegate;
// declared property setter: - (void)setDidCreateTemporaryPostDataFile:(BOOL)createTemporaryPostDataFile;
// declared property setter: - (void)setDidFailSelector:(SEL)failSelector;
// declared property setter: - (void)setDidFinishSelector:(SEL)finishSelector;
// declared property setter: - (void)setDidReceiveDataSelector:(SEL)receiveDataSelector;
// declared property setter: - (void)setDidReceiveResponseHeadersSelector:(SEL)receiveResponseHeadersSelector;
// declared property setter: - (void)setDidStartSelector:(SEL)startSelector;
// declared property setter: - (void)setDidUseCachedResponse:(BOOL)useCachedResponse;
// declared property setter: - (void)setDomain:(id)domain;
// declared property setter: - (void)setDownloadCache:(id)cache;
// declared property setter: - (void)setDownloadComplete:(BOOL)complete;
// declared property setter: - (void)setDownloadDestinationPath:(id)path;
// declared property setter: - (void)setDownloadProgressDelegate:(id)delegate;
- (void)setDownloadSizeIncrementedBlock:(id)block;
// declared property setter: - (void)setError:(id)error;
- (void)setFailedBlock:(id)block;
// declared property setter: - (void)setFileDownloadOutputStream:(id)stream;
// declared property setter: - (void)setHaveBuiltPostBody:(BOOL)body;
// declared property setter: - (void)setHaveBuiltRequestHeaders:(BOOL)headers;
- (void)setHeadersReceivedBlock:(id)block;
// declared property setter: - (void)setInProgress:(BOOL)progress;
// declared property setter: - (void)setInflatedFileDownloadOutputStream:(id)stream;
// declared property setter: - (void)setIsPACFileRequest:(BOOL)request;
// declared property setter: - (void)setLastActivityTime:(id)time;
// declared property setter: - (void)setLastBytesRead:(unsigned long long)read;
// declared property setter: - (void)setLastBytesSent:(unsigned long long)sent;
// declared property setter: - (void)setMainRequest:(id)request;
// declared property setter: - (void)setNeedsRedirect:(BOOL)redirect;
// declared property setter: - (void)setNumberOfTimesToRetryOnTimeout:(int)retryOnTimeout;
// declared property setter: - (void)setOriginalURL:(id)url;
// declared property setter: - (void)setPACFileData:(id)data;
// declared property setter: - (void)setPACFileReadStream:(id)stream;
// declared property setter: - (void)setPACFileRequest:(id)request;
// declared property setter: - (void)setPACurl:(id)curl;
// declared property setter: - (void)setPartialDownloadSize:(unsigned long long)size;
// declared property setter: - (void)setPassword:(id)password;
// declared property setter: - (void)setPersistentConnectionTimeoutSeconds:(double)seconds;
// declared property setter: - (void)setPostBody:(id)body;
// declared property setter: - (void)setPostBodyFilePath:(id)path;
// declared property setter: - (void)setPostBodyReadStream:(id)stream;
// declared property setter: - (void)setPostBodyWriteStream:(id)stream;
// declared property setter: - (void)setPostLength:(unsigned long long)length;
- (void)setProxyAuthenticationNeededBlock:(id)block;
// declared property setter: - (void)setProxyAuthenticationRealm:(id)realm;
// declared property setter: - (void)setProxyAuthenticationRetryCount:(int)count;
// declared property setter: - (void)setProxyAuthenticationScheme:(id)scheme;
// declared property setter: - (void)setProxyCredentials:(id)credentials;
// declared property setter: - (void)setProxyDomain:(id)domain;
// declared property setter: - (void)setProxyHost:(id)host;
// declared property setter: - (void)setProxyPassword:(id)password;
// declared property setter: - (void)setProxyPort:(int)port;
// declared property setter: - (void)setProxyType:(id)type;
// declared property setter: - (void)setProxyUsername:(id)username;
// declared property setter: - (void)setQueue:(id)queue;
// declared property setter: - (void)setRawResponseData:(id)data;
// declared property setter: - (void)setReadStream:(id)stream;
// declared property setter: - (void)setReadStreamIsScheduled:(BOOL)scheduled;
// declared property setter: - (void)setRedirectCount:(int)count;
// declared property setter: - (void)setRedirectURL:(id)url;
// declared property setter: - (void)setRequestCookies:(id)cookies;
// declared property setter: - (void)setRequestCredentials:(id)credentials;
// declared property setter: - (void)setRequestHeaders:(id)headers;
// declared property setter: - (void)setRequestID:(id)anId;
// declared property setter: - (void)setRequestMethod:(id)method;
- (void)setRequestRedirectedBlock:(id)block;
// declared property setter: - (void)setResponseCookies:(id)cookies;
// declared property setter: - (void)setResponseEncoding:(unsigned)encoding;
// declared property setter: - (void)setResponseHeaders:(id)headers;
// declared property setter: - (void)setResponseStatusCode:(int)code;
// declared property setter: - (void)setResponseStatusMessage:(id)message;
// declared property setter: - (void)setRetryCount:(int)count;
// declared property setter: - (void)setRunLoopMode:(id)mode;
// declared property setter: - (void)setSecondsToCache:(double)cache;
// declared property setter: - (void)setShouldAttemptPersistentConnection:(BOOL)attemptPersistentConnection;
// declared property setter: - (void)setShouldCompressRequestBody:(BOOL)compressRequestBody;
// declared property setter: - (void)setShouldContinueWhenAppEntersBackground:(BOOL)continueWhenAppEntersBackground;
// declared property setter: - (void)setShouldPresentAuthenticationDialog:(BOOL)presentAuthenticationDialog;
// declared property setter: - (void)setShouldPresentCredentialsBeforeChallenge:(BOOL)presentCredentialsBeforeChallenge;
// declared property setter: - (void)setShouldPresentProxyAuthenticationDialog:(BOOL)presentProxyAuthenticationDialog;
// declared property setter: - (void)setShouldRedirect:(BOOL)redirect;
// declared property setter: - (void)setShouldResetDownloadProgress:(BOOL)resetDownloadProgress;
// declared property setter: - (void)setShouldResetUploadProgress:(BOOL)resetUploadProgress;
// declared property setter: - (void)setShouldStreamPostDataFromDisk:(BOOL)streamPostDataFromDisk;
// declared property setter: - (void)setShouldUseRFC2616RedirectBehaviour:(BOOL)useRFC2616RedirectBehaviour;
// declared property setter: - (void)setShouldWaitToInflateCompressedResponses:(BOOL)waitToInflateCompressedResponses;
// declared property setter: - (void)setShowAccurateProgress:(BOOL)progress;
- (void)setStartedBlock:(id)block;
// declared property setter: - (void)setStatusTimer:(id)timer;
// declared property setter: - (void)setSynchronous:(BOOL)synchronous;
// declared property setter: - (void)setTag:(int)tag;
// declared property setter: - (void)setTemporaryFileDownloadPath:(id)path;
// declared property setter: - (void)setTemporaryUncompressedDataDownloadPath:(id)path;
// declared property setter: - (void)setTimeOutSeconds:(double)seconds;
// declared property setter: - (void)setTotalBytesRead:(unsigned long long)read;
// declared property setter: - (void)setTotalBytesSent:(unsigned long long)sent;
// declared property setter: - (void)setURL:(id)url;
// declared property setter: - (void)setUpdatedProgress:(BOOL)progress;
// declared property setter: - (void)setUploadBufferSize:(unsigned long long)size;
// declared property setter: - (void)setUploadProgressDelegate:(id)delegate;
- (void)setUploadSizeIncrementedBlock:(id)block;
// declared property setter: - (void)setUseCookiePersistence:(BOOL)persistence;
// declared property setter: - (void)setUseHTTPVersionOne:(BOOL)one;
// declared property setter: - (void)setUseKeychainPersistence:(BOOL)persistence;
// declared property setter: - (void)setUseSessionPersistence:(BOOL)persistence;
// declared property setter: - (void)setUserAgent:(id)agent;
// declared property setter: - (void)setUserInfo:(id)info;
// declared property setter: - (void)setUsername:(id)username;
// declared property setter: - (void)setValidatesSecureCertificate:(BOOL)certificate;
// declared property setter: - (void)setWillRedirectSelector:(SEL)redirectSelector;
// declared property setter: - (void)setWillRetryRequest:(BOOL)retryRequest;
- (void)setupPostBody;
// declared property getter: - (BOOL)shouldAttemptPersistentConnection;
// declared property getter: - (BOOL)shouldCompressRequestBody;
// declared property getter: - (BOOL)shouldContinueWhenAppEntersBackground;
// declared property getter: - (BOOL)shouldPresentAuthenticationDialog;
// declared property getter: - (BOOL)shouldPresentCredentialsBeforeChallenge;
// declared property getter: - (BOOL)shouldPresentProxyAuthenticationDialog;
// declared property getter: - (BOOL)shouldRedirect;
// declared property getter: - (BOOL)shouldResetDownloadProgress;
// declared property getter: - (BOOL)shouldResetUploadProgress;
// declared property getter: - (BOOL)shouldStreamPostDataFromDisk;
- (BOOL)shouldTimeOut;
// declared property getter: - (BOOL)shouldUseRFC2616RedirectBehaviour;
// declared property getter: - (BOOL)shouldWaitToInflateCompressedResponses;
// declared property getter: - (BOOL)showAccurateProgress;
- (BOOL)showAuthenticationDialog;
- (BOOL)showProxyAuthenticationDialog;
- (void)start;
- (void)startAsynchronous;
- (void)startRequest;
- (void)startSynchronous;
// declared property getter: - (id)statusTimer;
- (void)stream:(id)stream handleEvent:(unsigned)event;
// declared property getter: - (int)tag;
// declared property getter: - (id)temporaryFileDownloadPath;
// declared property getter: - (id)temporaryUncompressedDataDownloadPath;
- (void)timeOutPACRead;
// declared property getter: - (double)timeOutSeconds;
// declared property getter: - (unsigned long long)totalBytesRead;
// declared property getter: - (unsigned long long)totalBytesSent;
- (void)unscheduleReadStream;
- (void)updateDownloadProgress;
- (void)updatePartialDownloadSize;
- (void)updateProgressIndicators;
- (void)updateStatus:(id)status;
- (void)updateUploadProgress;
// declared property getter: - (BOOL)updatedProgress;
// declared property getter: - (unsigned long long)uploadBufferSize;
// declared property getter: - (id)uploadProgressDelegate;
// declared property getter: - (id)url;
// declared property getter: - (BOOL)useCookiePersistence;
- (void)useDataFromCache;
// declared property getter: - (BOOL)useHTTPVersionOne;
// declared property getter: - (BOOL)useKeychainPersistence;
// declared property getter: - (BOOL)useSessionPersistence;
// declared property getter: - (id)userAgent;
// declared property getter: - (id)userInfo;
// declared property getter: - (id)username;
// declared property getter: - (BOOL)validatesSecureCertificate;
- (BOOL)willAskDelegateForCredentials;
- (BOOL)willAskDelegateForProxyCredentials;
- (BOOL)willAskDelegateToConfirmRedirect;
- (BOOL)willRedirect;
// declared property getter: - (SEL)willRedirectSelector;
// declared property getter: - (BOOL)willRetryRequest;
@end

