/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "ModernCombat5-Structs.h"


@interface RMASIDataDecompressor : NSObject {
	BOOL streamReady;	// 4 = 0x4
	z_stream_s zStream;	// 8 = 0x8
}
@property(readonly, assign) BOOL streamReady;	// @synthesize
+ (id)decompressor;
+ (id)inflateErrorWithCode:(int)code;
+ (id)uncompressData:(id)data error:(id *)error;
+ (BOOL)uncompressDataFromFile:(id)file toFile:(id)file2 error:(id *)error;
- (id)closeStream;
- (void)dealloc;
- (id)setupStream;
// declared property getter: - (BOOL)streamReady;
- (id)uncompressBytes:(char *)bytes length:(unsigned)length error:(id *)error;
@end

