/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol RMAuthorizeViewDelegate <NSObject>
@optional
- (void)authFinishedFailure:(id)failure;
@required
- (void)authFinishedSuccess;
@optional
- (void)authWebViewDidCancel;
- (void)oauthWebView:(id)view didFailLoadWithError:(id)error;
- (void)oauthWebViewDidFinishLoad:(id)oauthWebView;
- (void)oauthWebViewDidStartLoad:(id)oauthWebView;
@end

