/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMViewController.h"
#import "UIWebViewDelegate.h"

@class NSString;
@protocol RMAuthorizeViewDelegate;

@interface RMAuthorizeViewController : RMViewController <UIWebViewDelegate> {
	BOOL _isOptEnd;	// 192 = 0xc0
	NSString *_scope;	// 196 = 0xc4
	id<RMAuthorizeViewDelegate> _delegate;	// 200 = 0xc8
}
@property(assign, nonatomic) id<RMAuthorizeViewDelegate> delegate;	// @synthesize=_delegate
@property(assign, nonatomic) BOOL isOptEnd;	// @synthesize=_isOptEnd
@property(retain, nonatomic) NSString *scope;	// @synthesize=_scope
- (id)initWithScope:(id)scope delegate:(id)delegate;
- (void)dealloc;
// declared property getter: - (id)delegate;
- (void)didFinishAuthCancel;
- (void)didFinishAuthSuccess;
- (void)didReceiveMemoryWarning;
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
// declared property getter: - (BOOL)isOptEnd;
- (void)loadAuthorizeWeb;
- (void)loadView;
- (void)loadViewInterfaceOrientationForiPad;
- (void)loadViewInterfaceOrientationIsLandscape;
- (void)loadViewInterfaceOrientationIsPortrait;
// declared property getter: - (id)scope;
// declared property setter: - (void)setDelegate:(id)delegate;
// declared property setter: - (void)setIsOptEnd:(BOOL)end;
// declared property setter: - (void)setScope:(id)scope;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
- (unsigned)supportedInterfaceOrientations;
- (void)viewDidAppear:(BOOL)view;
- (void)viewDidLoad;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)view;
- (void)webView:(id)view didFailLoadWithError:(id)error;
- (BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
- (void)webViewDidFinishLoad:(id)webView;
- (void)webViewDidStartLoad:(id)webView;
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
@end

