/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMRequestContextDelegate.h"
#import "ModernCombat5-Structs.h"
#import </libobjc.A.h>
#import "UIAlertViewDelegate.h"

@protocol RenrenMobileDelegate;

@interface RMConnectCenter : NSObject <RMRequestContextDelegate, RMRequestContextDelegate, UIAlertViewDelegate> {
	id<RenrenMobileDelegate> _connectCenterDelegate;	// 4 = 0x4
}
@property(assign, nonatomic) id<RenrenMobileDelegate> connectCenterDelegate;	// @synthesize=_connectCenterDelegate
+ (id)allocWithZone:(NSZone *)zone;
+ (BOOL)canLaunchRenrenSSO;
+ (void)createSharedCenter;
+ (id)currentUser;
+ (id)currertUserAccessToken;
+ (void)destroySharedCenter;
+ (void)disconnectRenrenMobile;
+ (void)dismissRMDashboard;
+ (void)hideRMDashboard;
+ (void)initializeConnectWithAPIKey:(id)apikey secretKey:(id)key appId:(id)anId mobileDelegate:(id)delegate;
+ (void)initializeConnectWithAPIKey:(id)apikey secretKey:(id)key appId:(id)anId urlSchemeSuffix:(id)suffix mobileDelegate:(id)delegate;
+ (BOOL)isCurrentUserLogined;
+ (void)logoutCurrentUser;
+ (void)sendActionLog:(int)log;
+ (void)sendHeartBeatMessage:(id)message;
+ (id)sharedCenter;
+ (void)showAlert:(id)alert withHanle:(id)hanle;
+ (void)showAlertWithTitle:(id)title message:(id)message cancelButtonTitle:(id)title3 otherButtonTitles:(id)titles handle:(id)handle;
+ (void)updateErrorList;
- (id)init;
- (void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
// declared property getter: - (id)connectCenterDelegate;
- (void)context:(id)context didFailLoadWithError:(id)error;
- (void)contextDidFinishLoad:(id)context;
- (void)dealloc;
- (void)didHideDashboard;
- (void)didShowDashboard;
- (void)getAppInfo;
- (BOOL)handleOpenURL:(id)url;
- (void)launchDashboardLoginWithScope:(id)scope orientation:(int)orientation andDelegate:(id)delegate;
- (void)launchDashboardLoginWithScope:(id)scope orientation:(int)orientation delegate:(id)delegate andManualSwitch:(BOOL)aSwitch;
- (void)launchDashboardRegisterWithOrientation:(int)orientation;
- (void)reauthFromSSO:(BOOL)sso;
// declared property setter: - (void)setConnectCenterDelegate:(id)delegate;
- (void)setLoginStatParam:(id)param;
- (void)startHeartBeat;
- (void)stopHeartBeat;
- (void)willHideDashboard;
- (void)willShowDashboard;
@end

