/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import </libobjc.A.h>

@class NSString, NSInvocation, NSMutableDictionary;

@interface RMConfig : NSObject {
	NSString *_apiKey;	// 4 = 0x4
	NSString *_secretKey;	// 8 = 0x8
	NSString *_clientName;	// 12 = 0xc
	NSString *_fromId;	// 16 = 0x10
	NSString *_apiURL;	// 20 = 0x14
	NSString *_sdkVersion;	// 24 = 0x18
	NSString *_urlSchemeSuffix;	// 28 = 0x1c
	NSString *_appId;	// 32 = 0x20
	NSString *_appPageId;	// 36 = 0x24
	NSString *_appName;	// 40 = 0x28
	NSString *_appIconUrlSmall;	// 44 = 0x2c
	NSString *_appIconUrlLarge;	// 48 = 0x30
	NSString *_authLevel;	// 52 = 0x34
	NSString *_authDesc;	// 56 = 0x38
	NSString *_terminal;	// 60 = 0x3c
	NSMutableDictionary *_clientInfo;	// 64 = 0x40
	NSInvocation *beforeSSOInvocation;	// 68 = 0x44
	NSString *_sdkProject;	// 72 = 0x48
}
@property(copy, nonatomic) NSString *apiKey;	// @synthesize=_apiKey
@property(copy, nonatomic) NSString *apiURL;	// @synthesize=_apiURL
@property(copy, nonatomic) NSString *appIconUrlLarge;	// @synthesize=_appIconUrlLarge
@property(copy, nonatomic) NSString *appIconUrlSmall;	// @synthesize=_appIconUrlSmall
@property(copy, nonatomic) NSString *appId;	// @synthesize=_appId
@property(copy, nonatomic) NSString *appName;	// @synthesize=_appName
@property(copy, nonatomic) NSString *appPageId;	// @synthesize=_appPageId
@property(copy, nonatomic) NSString *authDesc;	// @synthesize=_authDesc
@property(copy, nonatomic) NSString *authLevel;	// @synthesize=_authLevel
@property(retain, nonatomic) NSInvocation *beforeSSOInvocation;	// @synthesize
@property(retain, nonatomic) NSMutableDictionary *clientInfo;	// @synthesize=_clientInfo
@property(copy, nonatomic) NSString *clientName;	// @synthesize=_clientName
@property(copy, nonatomic) NSString *fromId;	// @synthesize=_fromId
@property(copy, nonatomic) NSString *sdkProject;	// @synthesize=_sdkProject
@property(copy, nonatomic) NSString *sdkVersion;	// @synthesize=_sdkVersion
@property(copy, nonatomic) NSString *secretKey;	// @synthesize=_secretKey
@property(copy, nonatomic) NSString *terminal;	// @synthesize=_terminal
@property(copy, nonatomic) NSString *urlSchemeSuffix;	// @synthesize=_urlSchemeSuffix
+ (id)allocWithZone:(NSZone *)zone;
+ (id)clientInfoWithHtf:(id)htf;
+ (id)clientInfo_SDKKEY;
+ (void)destroySharedConfig;
+ (id)getDeviceUsingLanguage;
+ (id)iOSVersion;
+ (BOOL)isLargeScreen;
+ (id)macAddress;
+ (id)macAddressUniqid;
+ (id)oauthRequestURLWithScope:(id)scope;
+ (id)otherClientInfo;
+ (id)regSmsNumber;
+ (BOOL)requireIOSVersion:(id)version;
+ (id)screenSize;
+ (id)sdkOS;
+ (id)sharedConfig;
+ (id)unneedSessionkeyRequsetMethods;
+ (id)wapClient;
+ (id)wapTicket;
- (id)init;
// declared property getter: - (id)apiKey;
// declared property getter: - (id)apiURL;
// declared property getter: - (id)appIconUrlLarge;
// declared property getter: - (id)appIconUrlSmall;
// declared property getter: - (id)appId;
// declared property getter: - (id)appName;
// declared property getter: - (id)appPageId;
// declared property getter: - (id)authDesc;
// declared property getter: - (id)authLevel;
// declared property getter: - (id)beforeSSOInvocation;
// declared property getter: - (id)clientInfo;
// declared property getter: - (id)clientName;
- (void)collectAppAuthInfo:(id)info;
- (void)dealloc;
// declared property getter: - (id)fromId;
- (id)getOwnBaseUrl:(id)url;
- (BOOL)handleOpenURL:(id)url;
- (id)renrenSSOURLWithScope:(id)scope;
// declared property getter: - (id)sdkProject;
// declared property getter: - (id)sdkVersion;
// declared property getter: - (id)secretKey;
// declared property setter: - (void)setApiKey:(id)key;
// declared property setter: - (void)setApiURL:(id)url;
// declared property setter: - (void)setAppIconUrlLarge:(id)large;
// declared property setter: - (void)setAppIconUrlSmall:(id)small;
// declared property setter: - (void)setAppId:(id)anId;
// declared property setter: - (void)setAppName:(id)name;
// declared property setter: - (void)setAppPageId:(id)anId;
// declared property setter: - (void)setAuthDesc:(id)desc;
// declared property setter: - (void)setAuthLevel:(id)level;
// declared property setter: - (void)setBeforeSSOInvocation:(id)invocation;
// declared property setter: - (void)setClientInfo:(id)info;
// declared property setter: - (void)setClientName:(id)name;
// declared property setter: - (void)setFromId:(id)anId;
// declared property setter: - (void)setSdkProject:(id)project;
// declared property setter: - (void)setSdkVersion:(id)version;
// declared property setter: - (void)setSecretKey:(id)key;
// declared property setter: - (void)setTerminal:(id)terminal;
// declared property setter: - (void)setUrlSchemeSuffix:(id)suffix;
// declared property getter: - (id)terminal;
// declared property getter: - (id)urlSchemeSuffix;
@end

