/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class RMASIHTTPRequest, RMResponse, NSData;
@protocol RMRequestContextDelegate;

@interface RMCommonContext : NSObject {
	RMResponse *contextResponse;	// 4 = 0x4
	NSData *_responseData;	// 8 = 0x8
	id _objectParsedFromJsonString;	// 12 = 0xc
	RMASIHTTPRequest *_asiHttpRequest;	// 16 = 0x10
	id<RMRequestContextDelegate> _delegate;	// 20 = 0x14
}
@property(retain, nonatomic) RMASIHTTPRequest *asiHttpRequest;	// @synthesize=_asiHttpRequest
@property(assign, nonatomic) id<RMRequestContextDelegate> delegate;	// @synthesize=_delegate
+ (id)contextWithDelegate:(id)delegate;
// declared property getter: - (id)asiHttpRequest;
- (void)cancel;
- (void)dealloc;
// declared property getter: - (id)delegate;
- (void)didCancelLoad;
- (void)didFailLoadWithError:(id)error;
- (void)didFinishLoad;
- (void)didStartLoad;
- (float)downloadProgress;
- (void)generateResponse;
- (id)getContextResponse;
- (id)getContextString;
- (id)getObjectParseFromJsonString;
- (void)requestDidCancelLoad:(id)request;
- (void)requestDidFailLoad:(id)request;
- (void)requestDidFinishLoad:(id)request;
- (void)requestDidStartLoad:(id)request;
- (void)sendAsynchronousRequestWithParameterDictionary:(id)parameterDictionary;
- (BOOL)sendSynchronousRequestWithParameterDictionary:(id)parameterDictionary withError:(id *)error;
// declared property setter: - (void)setAsiHttpRequest:(id)request;
// declared property setter: - (void)setDelegate:(id)delegate;
- (void)setRequestFromSDKProject:(id)sdkproject;
@end

