/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UINavigationControllerDelegate.h"
#import "ModernCombat5-Structs.h"
#import </libobjc.A.h>

@class UIViewController, UIView, RMDashboardBackgroundVC, UIWindow;

@interface RMDashboard : NSObject <UINavigationControllerDelegate> {
	UIWindow *dashboardWindow;	// 4 = 0x4
	UIWindow *appWindow;	// 8 = 0x8
	BOOL appStatusBarHidden;	// 12 = 0xc
	UIView *dashboardView;	// 16 = 0x10
	UIView *containerView;	// 20 = 0x14
	RMDashboardBackgroundVC *dashboardBackground_iPad;	// 24 = 0x18
	UIViewController *containerViewController;	// 28 = 0x1c
	BOOL bFullScreen;	// 32 = 0x20
	int supportedInterfaceOrientations;	// 36 = 0x24
}
@property(assign, nonatomic) UIWindow *appWindow;	// @synthesize
@property(assign, nonatomic) BOOL bFullScreen;	// @synthesize
@property(assign, nonatomic) UIView *containerView;	// @synthesize
@property(retain, nonatomic) UIViewController *containerViewController;	// @synthesize
@property(retain, nonatomic) RMDashboardBackgroundVC *dashboardBackground_iPad;	// @synthesize
@property(retain, nonatomic) UIView *dashboardView;	// @synthesize
@property(retain, nonatomic) UIWindow *dashboardWindow;	// @synthesize
@property(assign, nonatomic) int supportedInterfaceOrientations;	// @synthesize
+ (int)dashboardInterfaceOrientation;
+ (void)destroyDashboard;
+ (CGRect)getDashboardBounds;
+ (CGRect)getDashboardContainerFrame;
+ (id)shareDashboard;
// declared property getter: - (id)appWindow;
// declared property getter: - (BOOL)bFullScreen;
- (void)clickCloseViewController:(id)controller animated:(BOOL)animated;
// declared property getter: - (id)containerView;
// declared property getter: - (id)containerViewController;
// declared property getter: - (id)dashboardBackground_iPad;
- (id)dashboardTopViewController;
// declared property getter: - (id)dashboardView;
// declared property getter: - (id)dashboardWindow;
- (void)dealloc;
- (void)dismissDashboard;
- (void)hideContainViewController:(BOOL)controller;
- (void)hideDashboard;
- (void)loadViewInterfaceOrientation;
- (void)orientationChanged:(id)changed;
- (void)removeContainerView;
// declared property setter: - (void)setAppWindow:(id)window;
// declared property setter: - (void)setBFullScreen:(BOOL)screen;
// declared property setter: - (void)setContainerView:(id)view;
// declared property setter: - (void)setContainerViewController:(id)controller;
// declared property setter: - (void)setDashboardBackground_iPad:(id)pad;
// declared property setter: - (void)setDashboardView:(id)view;
// declared property setter: - (void)setDashboardWindow:(id)window;
// declared property setter: - (void)setSupportedInterfaceOrientations:(int)orientations;
- (void)showContainViewController:(BOOL)controller;
- (void)showDashboard;
- (void)showDashboardAnimatedDone;
- (void)showNavigationRootViewController:(id)controller animated:(BOOL)animated;
// declared property getter: - (int)supportedInterfaceOrientations;
@end

