/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSError.h>

@class NSString;

@interface RMError : NSError {
	NSString *_developerDescription;	// 20 = 0x14
	NSString *_userDescription;	// 24 = 0x18
}
@property(copy, nonatomic) NSString *developerDescription;	// @synthesize=_developerDescription
@property(copy, nonatomic) NSString *userDescription;	// @synthesize=_userDescription
+ (id)errorWhenUserUnlogin;
+ (id)errorWithCode:(int)code errorMessage:(id)message;
+ (id)errorWithNSError:(id)nserror;
+ (id)errorWithOAuthResult:(id)oauthResult;
+ (id)errorWithRestInfo:(id)restInfo;
+ (id)errorwhenInvalidArgument;
+ (id)errorwithUnauthorized;
- (id)initWithDomain:(id)domain code:(int)code userInfo:(id)info;
- (void)dealloc;
// declared property getter: - (id)developerDescription;
- (id)localizedDescription;
// declared property setter: - (void)setDeveloperDescription:(id)description;
// declared property setter: - (void)setUserDescription:(id)description;
// declared property getter: - (id)userDescription;
@end

