/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface RMErrorCodeManager : NSObject {
}
+ (id)pathWithDoucumentsFile;
+ (id)replaceErrorMessageWithError:(id)error;
+ (BOOL)savePlistFileFromPath:(id)path;
- (id)init;
@end

