/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMItem.h"

@class NSString;

@interface RMFeedStatus : RMItem {
	NSString *statusId;	// 8 = 0x8
	NSString *status;	// 12 = 0xc
	NSString *ownerId;	// 16 = 0x10
	NSString *ownerName;	// 20 = 0x14
	int time;	// 24 = 0x18
	int commentCount;	// 28 = 0x1c
}
@property(readonly, assign, nonatomic) int commentCount;	// @synthesize
@property(readonly, assign, nonatomic) NSString *ownerId;	// @synthesize
@property(readonly, assign, nonatomic) NSString *ownerName;	// @synthesize
@property(readonly, assign, nonatomic) NSString *status;	// @synthesize
@property(readonly, assign, nonatomic) NSString *statusId;	// @synthesize
@property(readonly, assign, nonatomic) int time;	// @synthesize
- (id)initWithDictionary:(id)dictionary;
// declared property getter: - (int)commentCount;
- (void)dealloc;
// declared property getter: - (id)ownerId;
// declared property getter: - (id)ownerName;
// declared property getter: - (id)status;
// declared property getter: - (id)statusId;
// declared property getter: - (int)time;
@end

