/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMItem.h"

@class NSString;

@interface RMFeedComment : RMItem {
	NSString *comment;	// 8 = 0x8
	NSString *commentId;	// 12 = 0xc
	NSString *userId;	// 16 = 0x10
	NSString *userName;	// 20 = 0x14
	NSString *headUrl;	// 24 = 0x18
	NSString *time;	// 28 = 0x1c
	NSString *content;	// 32 = 0x20
}
@property(readonly, assign, nonatomic) NSString *comment;	// @synthesize
@property(readonly, assign, nonatomic) NSString *commentId;	// @synthesize
@property(readonly, assign, nonatomic) NSString *content;	// @synthesize
@property(readonly, assign, nonatomic) NSString *headUrl;	// @synthesize
@property(readonly, assign, nonatomic) NSString *time;	// @synthesize
@property(readonly, assign, nonatomic) NSString *userId;	// @synthesize
@property(readonly, assign, nonatomic) NSString *userName;	// @synthesize
- (id)initWithDictionary:(id)dictionary;
// declared property getter: - (id)comment;
// declared property getter: - (id)commentId;
// declared property getter: - (id)content;
// declared property getter: - (id)headUrl;
// declared property getter: - (id)time;
// declared property getter: - (id)userId;
// declared property getter: - (id)userName;
@end

