/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMItem.h"

@class NSString;

@interface RMFeed : RMItem {
	NSString *url;	// 8 = 0x8
	NSString *mainUrl;	// 12 = 0xc
	NSString *type;	// 16 = 0x10
	NSString *src;	// 20 = 0x14
	NSString *mediaId;	// 24 = 0x18
	NSString *ownerId;	// 28 = 0x1c
	NSString *digest;	// 32 = 0x20
}
@property(readonly, assign, nonatomic) NSString *digest;	// @synthesize
@property(readonly, assign, nonatomic) NSString *mainUrl;	// @synthesize
@property(readonly, assign, nonatomic) NSString *mediaId;	// @synthesize
@property(readonly, assign, nonatomic) NSString *ownerId;	// @synthesize
@property(readonly, assign, nonatomic) NSString *src;	// @synthesize
@property(readonly, assign, nonatomic) NSString *type;	// @synthesize
@property(readonly, assign, nonatomic) NSString *url;	// @synthesize
- (id)initWithDictionary:(id)dictionary;
// declared property getter: - (id)digest;
// declared property getter: - (id)mainUrl;
// declared property getter: - (id)mediaId;
// declared property getter: - (id)ownerId;
// declared property getter: - (id)src;
// declared property getter: - (id)type;
// declared property getter: - (id)url;
@end

