/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMResponse.h"

@class NSString;

@interface RMGetClientCountResponse : RMResponse {
	int gossipReplyCount;	// 8 = 0x8
	int friendRequestCount;	// 12 = 0xc
	int appInviteCount;	// 16 = 0x10
	int appPageFeedCount;	// 20 = 0x14
	int homeFeedCount;	// 24 = 0x18
	int appActivityCount;	// 28 = 0x1c
	int appOfficialFeedCount;	// 32 = 0x20
	NSString *now;	// 36 = 0x24
}
@property(readonly, assign, nonatomic) int appActivityCount;	// @synthesize
@property(readonly, assign, nonatomic) int appInviteCount;	// @synthesize
@property(readonly, assign, nonatomic) int appOfficialFeedCount;	// @synthesize
@property(readonly, assign, nonatomic) int appPageFeedCount;	// @synthesize
@property(readonly, assign, nonatomic) int friendRequestCount;	// @synthesize
@property(readonly, assign, nonatomic) int gossipReplyCount;	// @synthesize
@property(readonly, assign, nonatomic) int homeFeedCount;	// @synthesize
@property(readonly, assign, nonatomic) NSString *now;	// @synthesize
- (id)initWithDictionary:(id)dictionary;
// declared property getter: - (int)appActivityCount;
// declared property getter: - (int)appInviteCount;
// declared property getter: - (int)appOfficialFeedCount;
// declared property getter: - (int)appPageFeedCount;
// declared property getter: - (int)friendRequestCount;
// declared property getter: - (int)gossipReplyCount;
// declared property getter: - (int)homeFeedCount;
// declared property getter: - (id)now;
@end

