/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMResponse.h"

@class NSString;

@interface RMGetResultResponse : RMResponse {
	NSString *result;	// 8 = 0x8
}
@property(readonly, assign, nonatomic) NSString *result;	// @synthesize
- (id)initWithDictionary:(id)dictionary;
// declared property getter: - (id)result;
@end

