/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMCommonContext.h"

@class NSString;

@interface RMLoginContext : RMCommonContext {
	BOOL reloginFromSSO;	// 16 = 0x10
	NSString *_callId;	// 20 = 0x14
}
@property(copy, nonatomic) NSString *callId;	// @synthesize=_callId
@property(assign, nonatomic) BOOL reloginFromSSO;	// @synthesize
// declared property getter: - (id)callId;
- (void)dealloc;
- (void)didCancelLoad;
- (void)didFailLoadWithError:(id)error;
- (void)didFinishLoad;
- (void)didStartLoad;
- (void)generateResponse;
- (void)reloginForCurrentUser;
// declared property getter: - (BOOL)reloginFromSSO;
// declared property setter: - (void)setCallId:(id)anId;
// declared property setter: - (void)setReloginFromSSO:(BOOL)sso;
@end

