/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMRequestContextDelegate.h"
#import </libobjc.A.h>


@interface RMLogManager : NSObject <RMRequestContextDelegate> {
}
+ (void)destroyInstance;
+ (id)getInstance;
- (void)context:(id)context didFailLoadWithError:(id)error;
- (void)contextDidCancelLoad:(id)context;
- (void)contextDidFinishLoad:(id)context;
- (void)contextDidStartLoad:(id)context;
- (void)sendActionLogWithID:(id)anId;
- (void)sendActionLogWithID:(id)anId fromComponent:(id)component;
@end

