/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMRequestContextDelegate.h"
#import </libobjc.A.h>
#import "UIAlertViewDelegate.h"

@class NSMutableArray, RMCommonContext, NSMutableDictionary;

@interface RMRequestManage : NSObject <RMRequestContextDelegate, UIAlertViewDelegate> {
	NSMutableArray *managedRequests;	// 4 = 0x4
	NSMutableDictionary *contextWithInvocations;	// 8 = 0x8
	NSMutableDictionary *contextWithAlerts;	// 12 = 0xc
	RMCommonContext *needDealWithContext;	// 16 = 0x10
}
@property(retain, nonatomic) RMCommonContext *needDealWithContext;	// @synthesize
+ (void)destroySharedRequestManage;
+ (id)sharedRequestManage;
- (void)addContext:(id)context;
- (void)addContext:(id)context withInvocation:(id)invocation alertInfo:(id)info;
- (id)alertInfoWithContext:(id)context;
- (void)alertView:(id)view clickedButtonAtIndex:(int)index;
- (void)alertView:(id)view didDismissWithButtonIndex:(int)buttonIndex;
- (void)context:(id)context didFailLoadWithError:(id)error;
- (void)contextDidCancelLoad:(id)context;
- (void)contextDidFinishLoad:(id)context;
- (void)contextDidStartLoad:(id)context;
- (void)dealloc;
- (id)errorInvocationWithContext:(id)context;
// declared property getter: - (id)needDealWithContext;
- (void)removeContext:(id)context;
// declared property setter: - (void)setNeedDealWithContext:(id)context;
@end

