/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import </libobjc.A.h>

@class NSString;

@interface RMReachability : NSObject {
	NSString *key_;	// 4 = 0x4
	SCNetworkReachabilityRef reachabilityRef;	// 8 = 0x8
}
@property(copy) NSString *key;	// @synthesize=key_
+ (BOOL)accessInstanceVariablesDirectly;
+ (id)makeAddressKey:(unsigned)key;
+ (id)reachabilityForInternetConnection;
+ (id)reachabilityForLocalWiFi;
+ (id)reachabilityWithAddress:(const sockaddr_in *)address;
+ (id)reachabilityWithHostName:(id)hostName;
- (id)initWithReachabilityRef:(SCNetworkReachabilityRef)reachabilityRef;
- (BOOL)connectionRequired;
- (unsigned)currentReachabilityStatus;
- (void)dealloc;
- (BOOL)isConnectionOnDemand;
- (BOOL)isConnectionRequired;
- (BOOL)isEqual:(id)equal;
- (BOOL)isInterventionRequired;
- (BOOL)isReachable;
- (BOOL)isReachableViaWWAN;
- (BOOL)isReachableViaWiFi;
// declared property getter: - (id)key;
- (unsigned)networkStatusForFlags:(unsigned)flags;
- (unsigned)reachabilityFlags;
// declared property setter: - (void)setKey:(id)key;
- (BOOL)startNotifier;
- (void)stopNotifier;
@end

