/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMSBJsonStreamParserAdapterDelegate.h"
#import </libobjc.A.h>


@interface RMSBJsonStreamParserAccumulator : NSObject <RMSBJsonStreamParserAdapterDelegate> {
	id value;	// 4 = 0x4
}
@property(readonly, assign) id value;	// @synthesize
- (void)dealloc;
- (void)parser:(id)parser foundArray:(id)array;
- (void)parser:(id)parser foundObject:(id)object;
// declared property getter: - (id)value;
@end

