/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class RMSBJsonStreamWriterState, NSMutableArray, NSString;
@protocol RMSBJsonStreamWriterDelegate;

@interface RMSBJsonStreamWriter : NSObject {
	NSString *error;	// 4 = 0x4
	NSMutableArray *stateStack;	// 8 = 0x8
	RMSBJsonStreamWriterState *state;	// 12 = 0xc
	id<RMSBJsonStreamWriterDelegate> delegate;	// 16 = 0x10
	unsigned maxDepth;	// 20 = 0x14
	BOOL sortKeys;	// 24 = 0x18
	BOOL humanReadable;	// 25 = 0x19
}
@property(assign) id<RMSBJsonStreamWriterDelegate> delegate;	// @synthesize
@property(copy) NSString *error;	// @synthesize
@property(assign) BOOL humanReadable;	// @synthesize
@property(assign) unsigned maxDepth;	// @synthesize
@property(assign) BOOL sortKeys;	// @synthesize
@property(assign, nonatomic) RMSBJsonStreamWriterState *state;	// @synthesize
@property(readonly, assign, nonatomic) NSMutableArray *stateStack;	// @synthesize
+ (void)initialize;
- (id)init;
- (void)appendBytes:(const void *)bytes length:(unsigned)length;
- (void)dealloc;
// declared property getter: - (id)delegate;
// declared property getter: - (id)error;
// declared property getter: - (BOOL)humanReadable;
// declared property getter: - (unsigned)maxDepth;
// declared property setter: - (void)setDelegate:(id)delegate;
// declared property setter: - (void)setError:(id)error;
// declared property setter: - (void)setHumanReadable:(BOOL)readable;
// declared property setter: - (void)setMaxDepth:(unsigned)depth;
// declared property setter: - (void)setSortKeys:(BOOL)keys;
// declared property setter: - (void)setState:(id)state;
// declared property getter: - (BOOL)sortKeys;
// declared property getter: - (id)state;
// declared property getter: - (id)stateStack;
- (BOOL)writeArray:(id)array;
- (BOOL)writeArrayClose;
- (BOOL)writeArrayOpen;
- (BOOL)writeBool:(BOOL)aBool;
- (BOOL)writeNull;
- (BOOL)writeNumber:(id)number;
- (BOOL)writeObject:(id)object;
- (BOOL)writeObjectClose;
- (BOOL)writeObjectOpen;
- (BOOL)writeString:(id)string;
- (BOOL)writeValue:(id)value;
@end

