/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface RMSBJsonParser : NSObject {
	NSString *error;	// 4 = 0x4
	unsigned depth;	// 8 = 0x8
	unsigned maxDepth;	// 12 = 0xc
}
@property(copy) NSString *error;	// @synthesize
@property(assign) unsigned maxDepth;	// @synthesize
- (id)init;
- (void)dealloc;
// declared property getter: - (id)error;
// declared property getter: - (unsigned)maxDepth;
- (id)objectWithData:(id)data;
- (id)objectWithString:(id)string;
- (id)objectWithString:(id)string error:(id *)error;
// declared property setter: - (void)setError:(id)error;
// declared property setter: - (void)setMaxDepth:(unsigned)depth;
@end

