/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableArray, NSString, RMSBJsonStreamParserState, RMSBJsonTokeniser;
@protocol RMSBJsonStreamParserDelegate;

@interface RMSBJsonStreamParser : NSObject {
	BOOL supportMultipleDocuments;	// 4 = 0x4
	id<RMSBJsonStreamParserDelegate> delegate;	// 8 = 0x8
	RMSBJsonTokeniser *tokeniser;	// 12 = 0xc
	NSMutableArray *stateStack;	// 16 = 0x10
	RMSBJsonStreamParserState *state;	// 20 = 0x14
	unsigned maxDepth;	// 24 = 0x18
	NSString *error;	// 28 = 0x1c
}
@property(assign) id<RMSBJsonStreamParserDelegate> delegate;	// @synthesize
@property(copy) NSString *error;	// @synthesize
@property(assign) unsigned maxDepth;	// @synthesize
@property(assign, nonatomic) RMSBJsonStreamParserState *state;	// @synthesize
@property(readonly, assign, nonatomic) NSMutableArray *stateStack;	// @synthesize
@property(assign) BOOL supportMultipleDocuments;	// @synthesize
- (id)init;
- (void)dealloc;
// declared property getter: - (id)delegate;
// declared property getter: - (id)error;
- (void)handleArrayStart;
- (void)handleObjectStart;
// declared property getter: - (unsigned)maxDepth;
- (void)maxDepthError;
- (int)parse:(id)parse;
// declared property setter: - (void)setDelegate:(id)delegate;
// declared property setter: - (void)setError:(id)error;
// declared property setter: - (void)setMaxDepth:(unsigned)depth;
// declared property setter: - (void)setState:(id)state;
// declared property setter: - (void)setSupportMultipleDocuments:(BOOL)documents;
// declared property getter: - (id)state;
// declared property getter: - (id)stateStack;
// declared property getter: - (BOOL)supportMultipleDocuments;
- (id)tokenName:(int)name;
@end

