/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, RMSBJsonUTF8Stream;

@interface RMSBJsonTokeniser : NSObject {
	RMSBJsonUTF8Stream *_stream;	// 4 = 0x4
	NSString *_error;	// 8 = 0x8
}
@property(copy) NSString *error;	// @synthesize=_error
- (id)init;
- (void)appendData:(id)data;
- (void)dealloc;
- (BOOL)decodeEscape:(unsigned short)escape into:(unsigned short *)into;
- (BOOL)decodeHexQuad:(unsigned short *)quad;
// declared property getter: - (id)error;
- (int)getNumberToken:(id *)token;
- (int)getStringToken:(id *)token;
- (int)getToken:(id *)token;
- (int)match:(const char *)match length:(unsigned)length retval:(int)retval;
// declared property setter: - (void)setError:(id)error;
@end

