/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "ModernCombat5-Structs.h"

@class NSMutableData;

@interface RMSBJsonUTF8Stream : NSObject {
	const char *_bytes;	// 4 = 0x4
	NSMutableData *_data;	// 8 = 0x8
	unsigned _length;	// 12 = 0xc
	unsigned _index;	// 16 = 0x10
}
@property(assign) unsigned index;	// @synthesize=_index
- (id)init;
- (void)appendData:(id)data;
- (void)dealloc;
- (BOOL)getNextUnichar:(unsigned short *)unichar;
- (BOOL)getRetainedStringFragment:(id *)fragment;
- (BOOL)getUnichar:(unsigned short *)unichar;
- (BOOL)haveRemainingCharacters:(unsigned)characters;
// declared property getter: - (unsigned)index;
// declared property setter: - (void)setIndex:(unsigned)index;
- (void)skip;
- (BOOL)skipCharacters:(const char *)characters length:(unsigned)length;
- (void)skipWhitespace;
- (id)stringWithRange:(NSRange)range;
@end

