/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMSBJsonStreamParserDelegate.h"
#import </libobjc.A.h>

@class NSMutableArray, NSMutableDictionary;
@protocol RMSBJsonStreamParserAdapterDelegate;

@interface RMSBJsonStreamParserAdapter : NSObject <RMSBJsonStreamParserDelegate> {
	id<RMSBJsonStreamParserAdapterDelegate> delegate;	// 4 = 0x4
	unsigned levelsToSkip;	// 8 = 0x8
	unsigned depth;	// 12 = 0xc
	NSMutableArray *array;	// 16 = 0x10
	NSMutableDictionary *dict;	// 20 = 0x14
	NSMutableArray *keyStack;	// 24 = 0x18
	NSMutableArray *stack;	// 28 = 0x1c
	int currentType;	// 32 = 0x20
}
@property(assign) id<RMSBJsonStreamParserAdapterDelegate> delegate;	// @synthesize
@property(assign) unsigned levelsToSkip;	// @synthesize
- (id)init;
- (void)dealloc;
// declared property getter: - (id)delegate;
// declared property getter: - (unsigned)levelsToSkip;
- (void)parser:(id)parser found:(id)found;
- (void)parser:(id)parser foundBoolean:(BOOL)boolean;
- (void)parser:(id)parser foundNumber:(id)number;
- (void)parser:(id)parser foundObjectKey:(id)key;
- (void)parser:(id)parser foundString:(id)string;
- (void)parserFoundArrayEnd:(id)end;
- (void)parserFoundArrayStart:(id)start;
- (void)parserFoundNull:(id)null;
- (void)parserFoundObjectEnd:(id)end;
- (void)parserFoundObjectStart:(id)start;
- (void)pop;
// declared property setter: - (void)setDelegate:(id)delegate;
// declared property setter: - (void)setLevelsToSkip:(unsigned)skip;
@end

