/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface RMSBJsonStreamWriterState : NSObject {
}
+ (id)sharedInstance;
- (void)appendSeparator:(id)separator;
- (void)appendWhitespace:(id)whitespace;
- (BOOL)expectingKey:(id)key;
- (BOOL)isInvalidState:(id)state;
- (void)transitionState:(id)state;
@end

