/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString;

@interface RMSBJsonWriter : NSObject {
	NSString *error;	// 4 = 0x4
	unsigned maxDepth;	// 8 = 0x8
	BOOL sortKeys;	// 12 = 0xc
	BOOL humanReadable;	// 13 = 0xd
}
@property(copy) NSString *error;	// @synthesize
@property(assign) BOOL humanReadable;	// @synthesize
@property(assign) unsigned maxDepth;	// @synthesize
@property(assign) BOOL sortKeys;	// @synthesize
- (id)init;
- (id)dataWithObject:(id)object;
- (void)dealloc;
// declared property getter: - (id)error;
// declared property getter: - (BOOL)humanReadable;
// declared property getter: - (unsigned)maxDepth;
// declared property setter: - (void)setError:(id)error;
// declared property setter: - (void)setHumanReadable:(BOOL)readable;
// declared property setter: - (void)setMaxDepth:(unsigned)depth;
// declared property setter: - (void)setSortKeys:(BOOL)keys;
// declared property getter: - (BOOL)sortKeys;
- (id)stringWithObject:(id)object;
- (id)stringWithObject:(id)object error:(id *)error;
@end

