/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RMItem.h"


@interface RMUserBirthday : RMItem {
	int day;	// 8 = 0x8
	int month;	// 12 = 0xc
	int year;	// 16 = 0x10
}
@property(readonly, assign, nonatomic) int day;	// @synthesize
@property(readonly, assign, nonatomic) int month;	// @synthesize
@property(readonly, assign, nonatomic) int year;	// @synthesize
- (id)initWithDictionary:(id)dictionary;
// declared property getter: - (int)day;
// declared property getter: - (int)month;
// declared property getter: - (int)year;
@end

