/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface RMUtility : NSObject {
}
+ (id)appendDefaultScope:(id)scope;
+ (void)appendImageData:(id)data withName:(id)name toBody:(id)body;
+ (BOOL)checkCurrentDeviceCanSMS;
+ (BOOL)checkWhetherMultipartPostNeeded:(id)needed;
+ (BOOL)compareStringA:(id)a hasStringB:(id)b;
+ (void)deleteCookies:(id)cookies;
+ (id)encodeString:(id)string urlEncode:(unsigned)encode;
+ (id)generateAESKeyWithSecretKey:(id)secretKey seedString:(id)string;
+ (id)generateHttpBodyForContentTypeOfApplicationXw3formurlencodedWithParameterDictionary:(id)parameterDictionary;
+ (id)generateHttpBodyForcontentTypeOfMultipartFormdataWithParameterDictionary:(id)parameterDictionary;
+ (id)generateSig:(id)sig secretKey:(id)key;
+ (id)generateSig:(id)sig secretKey:(id)key limitParamLength:(int)length;
+ (id)generateURL:(id)url params:(id)params;
+ (id)getDateFromString:(id)string;
+ (id)md5HexDigest:(id)digest;
+ (id)md5UTF8:(id)a8;
+ (void)onMainThreadPostNotification:(id)notification;
+ (id)parseURLParams:(id)params;
+ (id)pathWithDoucumentsFile:(id)doucumentsFile;
+ (id)persistantGetValueForKey:(id)key;
+ (void)persistantRemoveValueForKey:(id)key;
+ (void)persistantSetValue:(id)value withKey:(id)key;
+ (id)placeDataJsonStr:(id)str place_name:(id)name gLatitude:(id)latitude gLongitude:(id)longitude pLatitude:(id)latitude5 pLongitude:(id)longitude6 place_location:(id)location privacy:(id)privacy locate_type:(int)type d:(int)d;
+ (id)readPlistFileFromPath:(id)path;
+ (id)replaceUnicode:(id)unicode;
+ (BOOL)savePlistFileFromPath:(id)path dictionary:(id)dictionary;
+ (id)serializeURL:(id)url params:(id)params httpMethod:(id)method;
+ (BOOL)wrapCommonRequestParametersIfNecessary:(id)necessary withError:(id *)error;
@end

