/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>
#import "UIAlertViewDelegate.h"

@class UIView, NSString, UILabel, UIButton, RMDashboardBackgroundVC, RMWebView;

@interface RMViewController : UIViewController <UIAlertViewDelegate> {
	RMDashboardBackgroundVC *dashboardBackground;	// 160 = 0xa0
	BOOL _bViewLoaded;	// 164 = 0xa4
	BOOL _bShowTopBar;	// 165 = 0xa5
	BOOL _bShowWebView;	// 166 = 0xa6
	UIView *_topBarView;	// 168 = 0xa8
	RMWebView *_contentWebView;	// 172 = 0xac
	UIButton *_leftButton;	// 176 = 0xb0
	UIButton *_rightButton;	// 180 = 0xb4
	UILabel *_titleLabel;	// 184 = 0xb8
	UIView *_logoView;	// 188 = 0xbc
}
@property(assign, nonatomic) BOOL bShowLogo;
@property(assign, nonatomic) BOOL bShowTopBar;
@property(assign, nonatomic) BOOL bShowWebView;
@property(readonly, assign, nonatomic) RMWebView *contentWebView;
@property(assign, nonatomic) RMDashboardBackgroundVC *dashboardBackground;	// @synthesize
@property(retain, nonatomic) UIButton *leftButton;
@property(retain, nonatomic) UIButton *rightButton;
@property(retain, nonatomic) UILabel *titleLabel;
@property(retain, nonatomic) NSString *titleText;
@property(readonly, assign, nonatomic) UIView *topbarView;
- (id)initWithNibName:(id)nibName bundle:(id)bundle;
// declared property getter: - (BOOL)bShowLogo;
// declared property getter: - (BOOL)bShowTopBar;
// declared property getter: - (BOOL)bShowWebView;
// declared property getter: - (id)contentWebView;
// declared property getter: - (id)dashboardBackground;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
- (void)keyboardDidHide:(id)keyboard;
- (void)keyboardDidShow:(id)keyboard;
- (void)keyboardWillHide:(id)keyboard;
- (void)keyboardWillShow:(id)keyboard;
// declared property getter: - (id)leftButton;
- (void)loadView;
- (void)loadViewInterfaceOrientation;
- (void)loadViewInterfaceOrientationForiPad;
- (void)loadViewInterfaceOrientationIsLandscape;
- (void)loadViewInterfaceOrientationIsPortrait;
- (void)loadViewRotateToInterfaceOrientation:(int)interfaceOrientation;
- (void)presentModalViewController:(id)controller animated:(BOOL)animated;
- (void)relayoutWebView;
// declared property getter: - (id)rightButton;
// declared property setter: - (void)setBShowLogo:(BOOL)logo;
// declared property setter: - (void)setBShowTopBar:(BOOL)bar;
// declared property setter: - (void)setBShowWebView:(BOOL)view;
// declared property setter: - (void)setDashboardBackground:(id)background;
// declared property setter: - (void)setLeftButton:(id)button;
// declared property setter: - (void)setRightButton:(id)button;
// declared property setter: - (void)setTitleLabel:(id)label;
// declared property setter: - (void)setTitleText:(id)text;
// declared property getter: - (id)titleLabel;
// declared property getter: - (id)titleText;
// declared property getter: - (id)topbarView;
- (void)viewDidAppear:(BOOL)view;
- (void)viewDidUnload;
- (void)viewWillAppear:(BOOL)view;
- (void)viewWillDisappear:(BOOL)view;
- (void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
@end

