/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SA_OAuthTwitterEngineDelegate
@optional
- (id)cachedTwitterOAuthDataForUsername:(id)username;
- (void)storeCachedTwitterOAuthData:(id)data forUsername:(id)username;
- (void)twitterOAuthConnectionFailedWithData:(id)data;
@required
- (void)unParsedJsonDataReceived:(id)received forRequest:(id)request;
@end

