/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "UIWebViewDelegate.h"

@class UIActivityIndicatorView, SA_OAuthTwitterEngine, UIWebView, UINavigationBar;
@protocol SA_OAuthTwitterControllerDelegate;

@interface SA_OAuthTwitterController : UIView <UIWebViewDelegate> {
	SA_OAuthTwitterEngine *_engine;	// 52 = 0x34
	UIWebView *_webView;	// 56 = 0x38
	UINavigationBar *_navBar;	// 60 = 0x3c
	id<SA_OAuthTwitterControllerDelegate> _delegate;	// 64 = 0x40
	int _orientation;	// 68 = 0x44
	BOOL _loading;	// 72 = 0x48
	BOOL _firstLoad;	// 73 = 0x49
	UIActivityIndicatorView *_spinner;	// 76 = 0x4c
}
@property(assign, nonatomic) id<SA_OAuthTwitterControllerDelegate> delegate;	// @synthesize=_delegate
@property(retain, nonatomic) SA_OAuthTwitterEngine *engine;	// @synthesize=_engine
@property(readonly, assign, nonatomic) UINavigationBar *navigationBar;	// @synthesize=_navBar
@property(assign, nonatomic) int orientation;	// @synthesize=_orientation
+ (id)controllerToEnterCredentialsWithTwitterEngine:(id)twitterEngine delegate:(id)delegate;
+ (id)controllerToEnterCredentialsWithTwitterEngine:(id)twitterEngine delegate:(id)delegate forOrientation:(int)orientation;
+ (BOOL)credentialEntryRequiredWithTwitterEngine:(id)twitterEngine;
- (id)initWithEngine:(id)engine andOrientation:(int)orientation;
- (void)cancel:(id)cancel;
- (void)dealloc;
// declared property getter: - (id)delegate;
- (void)denied;
// declared property getter: - (id)engine;
- (void)gotPin:(id)pin;
- (void)hide;
- (void)loadView;
- (id)locateAuthPinInWebView:(id)webView;
// declared property getter: - (id)navigationBar;
// declared property getter: - (int)orientation;
- (void)pasteboardChanged:(id)changed;
// declared property setter: - (void)setDelegate:(id)delegate;
// declared property setter: - (void)setEngine:(id)engine;
// declared property setter: - (void)setOrientation:(int)orientation;
- (BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
- (void)webViewDidFinishLoad:(id)webView;
- (void)webViewDidStartLoad:(id)webView;
@end

