/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>
#import "UIWebViewDelegate.h"

@class UIWebView, NSMutableURLRequest, NSTimer;

@interface sendInfoInterface : NSObject <UIWebViewDelegate> {
	UIWebView *_siWebView;	// 4 = 0x4
	NSMutableURLRequest *_siRequest;	// 8 = 0x8
	NSTimer *_siTimer;	// 12 = 0xc
}
+ (id)EncryptAES_TRACKING:(id)tracking :(id)arg2;
+ (id)encodeBase64WithData_TRACKING:(id)data_TRACKING;
+ (id)macaddress_tracking;
- (void)IGPSendGameInfo:(int)info :(char *)arg2 :(id)arg3 :(bool)arg4 :(int)arg5;
- (void)checkReachability;
- (void)connection:(id)connection didFailWithError:(id)error;
- (void)connectionDidFinishLoading:(id)connection;
- (void)failedToSend;
- (void)getProfile;
- (void)sendInfo;
- (void)webView:(id)view didFailWithError:(id)error;
- (void)webViewDidFinishLoad:(id)webView;
@end

