/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SinaWeiboDelegate.h"
#import "SinaWeiboRequestDelegate.h"
#import </libobjc.A.h>

@class NSString, NSDate;

@interface SinaWeiboiOSGLSocialLib : NSObject <SinaWeiboDelegate, SinaWeiboRequestDelegate> {
	NSString *dialogMsg;	// 4 = 0x4
	NSString *dialogPictureUrl;	// 8 = 0x8
	NSString *dialogLink;	// 12 = 0xc
	NSString *dialogTitle;	// 16 = 0x10
	NSString *dialogDescription;	// 20 = 0x14
	NSString *_sessionKey;	// 24 = 0x18
	NSDate *_expirationDate;	// 28 = 0x1c
	NSString *_currentUserId;	// 32 = 0x20
	bool isLoggedIn;	// 36 = 0x24
}
@property(retain, nonatomic) NSString *dialogDescription;	// @synthesize
@property(retain, nonatomic) NSString *dialogLink;	// @synthesize
@property(retain, nonatomic) NSString *dialogMsg;	// @synthesize
@property(retain, nonatomic) NSString *dialogPictureUrl;	// @synthesize
@property(retain, nonatomic) NSString *dialogTitle;	// @synthesize
@property(assign, nonatomic) bool isLoggedIn;	// @synthesize
+ (void)didBecomeActive;
+ (void)load;
- (id)init;
- (void)initToken;
- (void)dealloc;
// declared property getter: - (id)dialogDescription;
// declared property getter: - (id)dialogLink;
// declared property getter: - (id)dialogMsg;
// declared property getter: - (id)dialogPictureUrl;
// declared property getter: - (id)dialogTitle;
- (BOOL)handleOpenURL:(id)url;
// declared property getter: - (bool)isLoggedIn;
- (void)removeAuthData;
- (void)request:(id)request didFailWithError:(id)error;
- (void)request:(id)request didFinishLoadingWithResult:(id)result;
// declared property setter: - (void)setDialogDescription:(id)description;
// declared property setter: - (void)setDialogLink:(id)link;
// declared property setter: - (void)setDialogMsg:(id)msg;
// declared property setter: - (void)setDialogPictureUrl:(id)url;
// declared property setter: - (void)setDialogTitle:(id)title;
// declared property setter: - (void)setIsLoggedIn:(bool)anIn;
- (void)sinaweibo:(id)sinaweibo accessTokenInvalidOrExpired:(id)expired;
- (void)sinaweibo:(id)sinaweibo logInDidFailWithError:(id)logIn;
- (void)sinaweiboDidLogIn:(id)sinaweibo;
- (void)sinaweiboDidLogOut:(id)sinaweibo;
- (void)sinaweiboLogInDidCancel:(id)sinaweiboLogIn;
- (id)sinaweiboiOSGLSocialLib_getAppSecret;
- (void)sinaweiboiOSGLSocialLib_getBilateralFriendsDataWithPage:(int)page andLimit:(int)limit andSort:(int)sort;
- (void)sinaweiboiOSGLSocialLib_getBilateralFriendsWithPage:(int)page andLimit:(int)limit andSort:(int)sort;
- (void)sinaweiboiOSGLSocialLib_getFriends;
- (void)sinaweiboiOSGLSocialLib_getFriendsDataWithPage:(int)page andPageSize:(int)size;
- (void)sinaweiboiOSGLSocialLib_getMyInfo;
- (void)sinaweiboiOSGLSocialLib_getPicture;
- (void)sinaweiboiOSGLSocialLib_getUserData:(id)data;
- (BOOL)sinaweiboiOSGLSocialLib_isLoggedIn;
- (void)sinaweiboiOSGLSocialLib_login;
- (void)sinaweiboiOSGLSocialLib_logout;
- (void)sinaweiboiOSGLSocialLib_postPhotoToWall:(id)wall;
- (void)sinaweiboiOSGLSocialLib_postToWallWithoutDialog;
- (void)storeAuthData;
@end

