/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SinaWeiboDelegate <NSObject>
@optional
- (void)sinaweibo:(id)sinaweibo accessTokenInvalidOrExpired:(id)expired;
- (void)sinaweibo:(id)sinaweibo logInDidFailWithError:(id)logIn;
- (void)sinaweiboDidLogIn:(id)sinaweibo;
- (void)sinaweiboDidLogOut:(id)sinaweibo;
- (void)sinaweiboLogInDidCancel:(id)sinaweiboLogIn;
@end

