/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SinaWeiboAuthorizeViewDelegate <NSObject>
- (void)authorizeView:(id)view didFailWithErrorInfo:(id)errorInfo;
- (void)authorizeView:(id)view didRecieveAuthorizationCode:(id)code;
- (void)authorizeViewDidCancel:(id)authorizeView;
@end

