/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "SinaWeiboRequestDelegate.h"
#import </libobjc.A.h>
#import "SinaWeiboAuthorizeViewDelegate.h"

@class NSString, NSDate, NSMutableSet, SinaWeiboRequest;
@protocol SinaWeiboDelegate;

@interface SinaWeibo : NSObject <SinaWeiboAuthorizeViewDelegate, SinaWeiboRequestDelegate> {
	NSString *userID;	// 4 = 0x4
	NSString *accessToken;	// 8 = 0x8
	NSDate *expirationDate;	// 12 = 0xc
	id<SinaWeiboDelegate> delegate;	// 16 = 0x10
	NSString *appKey;	// 20 = 0x14
	NSString *appSecret;	// 24 = 0x18
	NSString *appRedirectURI;	// 28 = 0x1c
	NSString *ssoCallbackScheme;	// 32 = 0x20
	SinaWeiboRequest *request;	// 36 = 0x24
	NSMutableSet *requests;	// 40 = 0x28
	BOOL ssoLoggingIn;	// 44 = 0x2c
	NSString *refreshToken;	// 48 = 0x30
}
@property(copy, nonatomic) NSString *accessToken;	// @synthesize
@property(copy, nonatomic) NSString *appKey;	// @synthesize
@property(copy, nonatomic) NSString *appRedirectURI;	// @synthesize
@property(copy, nonatomic) NSString *appSecret;	// @synthesize
@property(assign, nonatomic) id<SinaWeiboDelegate> delegate;	// @synthesize
@property(copy, nonatomic) NSDate *expirationDate;	// @synthesize
@property(copy, nonatomic) NSString *refreshToken;	// @synthesize
@property(copy, nonatomic) NSString *ssoCallbackScheme;	// @synthesize
@property(copy, nonatomic) NSString *userID;	// @synthesize
- (id)initWithAppKey:(id)appKey appSecret:(id)secret appRedirectURI:(id)uri andDelegate:(id)delegate;
- (id)initWithAppKey:(id)appKey appSecret:(id)secret appRedirectURI:(id)uri ssoCallbackScheme:(id)scheme andDelegate:(id)delegate;
// declared property getter: - (id)accessToken;
// declared property getter: - (id)appKey;
// declared property getter: - (id)appRedirectURI;
// declared property getter: - (id)appSecret;
- (void)applicationDidBecomeActive;
- (void)authorizeView:(id)view didFailWithErrorInfo:(id)errorInfo;
- (void)authorizeView:(id)view didRecieveAuthorizationCode:(id)code;
- (void)authorizeViewDidCancel:(id)authorizeView;
- (void)dealloc;
// declared property getter: - (id)delegate;
// declared property getter: - (id)expirationDate;
- (BOOL)handleOpenURL:(id)url;
- (BOOL)isAuthValid;
- (BOOL)isAuthorizeExpired;
- (BOOL)isLoggedIn;
- (void)logIn;
- (void)logInDidCancel;
- (void)logInDidFailWithErrorInfo:(id)logIn;
- (void)logInDidFinishWithAuthInfo:(id)logIn;
- (void)logOut;
- (void)notifyTokenExpired:(id)expired;
// declared property getter: - (id)refreshToken;
- (void)removeAuthData;
- (void)request:(id)request didFailWithError:(id)error;
- (void)request:(id)request didFinishLoadingWithResult:(id)result;
- (void)requestAccessTokenWithAuthorizationCode:(id)authorizationCode;
- (void)requestDidFailWithInvalidToken:(id)request;
- (void)requestDidFinish:(id)request;
- (id)requestWithURL:(id)url params:(id)params httpMethod:(id)method delegate:(id)delegate;
// declared property setter: - (void)setAccessToken:(id)token;
// declared property setter: - (void)setAppKey:(id)key;
// declared property setter: - (void)setAppRedirectURI:(id)uri;
// declared property setter: - (void)setAppSecret:(id)secret;
// declared property setter: - (void)setDelegate:(id)delegate;
// declared property setter: - (void)setExpirationDate:(id)date;
// declared property setter: - (void)setRefreshToken:(id)token;
// declared property setter: - (void)setSsoCallbackScheme:(id)scheme;
// declared property setter: - (void)setUserID:(id)anId;
// declared property getter: - (id)ssoCallbackScheme;
// declared property getter: - (id)userID;
@end

