/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class TextInput;

@interface TextInputInitParams : NSObject {
	char *textBuff;	// 4 = 0x4
	unsigned buffSize;	// 8 = 0x8
	int x;	// 12 = 0xc
	int y;	// 16 = 0x10
	int w;	// 20 = 0x14
	int h;	// 24 = 0x18
	bool pass;	// 28 = 0x1c
	int orientationTf;	// 32 = 0x20
	int realScreenW;	// 36 = 0x24
	int realScreenH;	// 40 = 0x28
	float angle;	// 44 = 0x2c
	TextInput *ti;	// 48 = 0x30
}
@end

