/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>
#import "ModernCombat5-Structs.h"
#import "UITextFieldDelegate.h"

@class UITextField;

@interface TextInput : UIViewController <UITextFieldDelegate> {
	UITextField *textField;	// 160 = 0xa0
	unsigned char done;	// 164 = 0xa4
	char *textBuffer;	// 168 = 0xa8
	unsigned textBufferSize;	// 172 = 0xac
}
+ (id)getSharedInstance;
+ (void)setSharedInstance:(id)instance;
- (id)initWithTextBuffer:(char *)textBuffer WithSize:(unsigned)size AtX:(int)x Y:(int)y Width:(int)width Height:(int)height PasswordFlag:(bool)flag Orientation:(int)orientation RealScreenW:(int)w RealScreenH:(int)h Angle:(float)angle;
- (void)Disable;
- (void)Enable;
- (void)Remove;
- (void)changeTransformToTextFieldWithTransform:(CGAffineTransform)transform;
- (void)dealloc;
- (BOOL)isDone;
- (void)setOrientation:(int)orientation AtX:(int)x Y:(int)y Width:(int)width Height:(int)height RealScreenW:(int)w RealScreenH:(int)h Angle:(float)angle;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
- (void)textFieldDidChange:(id)textField;
- (BOOL)textFieldShouldBeginEditing:(id)textField;
- (BOOL)textFieldShouldReturn:(id)textField;
@end

