/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import </libobjc.A.h>
#import "SKPaymentTransactionObserver.h"


__attribute__((visibility("hidden")))
@interface TransactionObserver : NSObject <SKPaymentTransactionObserver> {
	list<SKPaymentTransaction *, glwebtools::SAllocator<SKPaymentTransaction *, 4> > *m_sktransactions;	// 4 = 0x4
	list<iap::ios_billing::TransactionInfo, glwebtools::SAllocator<iap::ios_billing::TransactionInfo, 4> > *m_transactionInfos;	// 8 = 0x8
	int m_restoreState;	// 12 = 0xc
	int m_restoreErrorCode;	// 16 = 0x10
	basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > m_restoreErrorString;	// 20 = 0x14
	bool m_isInitialized;	// 32 = 0x20
	Mutex *m_mutex;	// 36 = 0x24
}
- (id)init;
- (id).cxx_construct;
- (void).cxx_destruct;
- (int)completeTransaction:(const TransactionInfo *)transaction;
- (void)dealloc;
- (int)getRestoreErrorCode:(int *)code errorString:(basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > *)string;
- (int)getRestoreState;
- (bool)hasNewTransation;
- (bool)isInitialized;
- (void)paymentQueue:(id)queue removedTransactions:(id)transactions;
- (void)paymentQueue:(id)queue restoreCompletedTransactionsFailedWithError:(id)error;
- (void)paymentQueue:(id)queue updatedTransactions:(id)transactions;
- (void)paymentQueueRestoreCompletedTransactionsFinished:(id)finished;
- (int)popTransaction:(TransactionInfo *)transaction;
- (int)restoreTransactions;
@end

