/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>


@interface UIDeviceApple : NSObject {
}
- (void)RegisterDeviceForApplicationInterrupts;
- (void)appDidEnterBackgroundNotif:(id)app;
- (void)appWillComeBackNotif:(id)app;
- (int)coreNumber;
- (int)cpuFrequency;
- (id)firmware;
- (int)getSysInfo:(unsigned)info;
- (int)height;
- (id)platform;
- (id)platformString;
- (int)totalMemory;
- (int)width;
@end

