/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ModernCombat5-Structs.h"
#import <UIKit/UITextView.h>

@class UILabel, NSString, UIColor;

@interface UIPlaceHolderTextView : UITextView {
	NSString *placeholder;	// 456 = 0x1c8
	UIColor *placeholderColor;	// 460 = 0x1cc
	UILabel *placeHolderLabel;	// 464 = 0x1d0
}
@property(retain, nonatomic) UILabel *placeHolderLabel;	// @synthesize
@property(retain, nonatomic) NSString *placeholder;	// @synthesize
@property(retain, nonatomic) UIColor *placeholderColor;	// @synthesize
- (id)initWithFrame:(CGRect)frame;
- (void).cxx_destruct;
- (void)awakeFromNib;
- (void)dealloc;
- (void)drawRect:(CGRect)rect;
// declared property getter: - (id)placeHolderLabel;
// declared property getter: - (id)placeholder;
// declared property getter: - (id)placeholderColor;
// declared property setter: - (void)setPlaceHolderLabel:(id)label;
// declared property setter: - (void)setPlaceholder:(id)placeholder;
// declared property setter: - (void)setPlaceholderColor:(id)color;
- (void)setText:(id)text;
- (void)textChanged:(id)changed;
@end

