/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIScrollViewDelegate.h"
#import "ModernCombat5-Structs.h"
#import "NSObject.h"


@protocol UITextViewDelegate <NSObject, UIScrollViewDelegate>
@optional
- (BOOL)textView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
- (void)textViewDidBeginEditing:(id)textView;
- (void)textViewDidChange:(id)textView;
- (void)textViewDidChangeSelection:(id)textView;
- (void)textViewDidEndEditing:(id)textView;
- (BOOL)textViewShouldBeginEditing:(id)textView;
- (BOOL)textViewShouldEndEditing:(id)textView;
@end

