/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSString, VkScreen;

@interface VKiOSGLSocialLib : NSObject {
	VkScreen *m_VKController;	// 4 = 0x4
	NSString *m_userId;	// 8 = 0x8
}
@property(retain, nonatomic) VkScreen *m_VKController;	// @synthesize
@property(retain, nonatomic) NSString *m_userId;	// @synthesize
- (id)init;
- (void)dealloc;
// declared property getter: - (id)m_VKController;
// declared property getter: - (id)m_userId;
// declared property setter: - (void)setM_VKController:(id)controller;
// declared property setter: - (void)setM_userId:(id)anId;
@end

