/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIWebViewDelegate.h"
#import <UIKit/UIViewController.h>

@class NSTimer, UIView, UIButton, NSMutableArray, NSURLConnection, NSMutableData, UIWebView, UIActivityIndicatorView, NSString;

@interface VkScreen : UIViewController <UIWebViewDelegate> {
	UIView *_welcomeScreenView;	// 160 = 0xa0
	UIWebView *_welcomeScreenWebView;	// 164 = 0xa4
	float _screenWidth;	// 168 = 0xa8
	float _screenHeight;	// 172 = 0xac
	int _languageIndex;	// 176 = 0xb0
	NSString *_urlAddressVKAuth;	// 180 = 0xb4
	BOOL isAuthorizeComplete;	// 184 = 0xb8
	UIActivityIndicatorView *_spinner;	// 188 = 0xbc
	BOOL _isInVKScreen;	// 192 = 0xc0
	int _remainingWSToDownload;	// 196 = 0xc4
	NSTimer *_welcomeScreenTimer;	// 200 = 0xc8
	NSURLConnection *_connection;	// 204 = 0xcc
	NSMutableData *responseData;	// 208 = 0xd0
	NSMutableArray *_connectionsArray;	// 212 = 0xd4
	NSMutableArray *_receivedDataArray;	// 216 = 0xd8
	NSMutableArray *_wsIdsArray;	// 220 = 0xdc
	int gameOrientation;	// 224 = 0xe0
	UIButton *_closeButton;	// 228 = 0xe4
}
@property(assign, nonatomic) int gameOrientation;	// @synthesize
@property(assign, nonatomic) BOOL isInVKScreen;	// @synthesize=_isInVKScreen
+ (id)URLEncodedString:(id)string;
+ (void)setGameViewController:(id)controller;
- (id)init;
- (void)DismissModalViewController:(id)controller;
- (void)PresentModalViewController:(id)controller;
- (void)authorizeComplete:(id)complete;
- (void)authorizeNotComplete:(id)complete;
- (void)cleanUp;
- (void)closeAd:(id)ad;
- (void)dealloc;
// declared property getter: - (int)gameOrientation;
- (void)getVKLink;
// declared property getter: - (BOOL)isInVKScreen;
- (void)orientationChanged;
- (BOOL)prefersStatusBarHidden;
- (void)quitVK;
- (id)sendRequest:(id)request withCaptcha:(BOOL)captcha;
// declared property setter: - (void)setGameOrientation:(int)orientation;
// declared property setter: - (void)setIsInVKScreen:(BOOL)vkscreen;
- (void)setLangIndex:(int)index;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
- (void)showOnView;
- (unsigned)supportedInterfaceOrientations;
- (void)timeout;
- (void)webView:(id)view didFailWithError:(id)error;
- (BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
- (void)webViewDidFinishLoad:(id)webView;
- (void)webViewDidStartLoad:(id)webView;
@end

