/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import </libobjc.A.h>

@class NSMutableDictionary;

@interface XKeychainItemWrapper : NSObject {
	NSMutableDictionary *keychainItemData;	// 4 = 0x4
	NSMutableDictionary *genericPasswordQuery;	// 8 = 0x8
}
@property(retain, nonatomic) NSMutableDictionary *genericPasswordQuery;	// @synthesize
@property(retain, nonatomic) NSMutableDictionary *keychainItemData;	// @synthesize
- (id)initWithIdentifier:(id)identifier service:(id)service accessGroup:(id)group;
- (void)dealloc;
- (void)deleteKeychainItem;
- (id)dictionaryToSecItemFormat:(id)secItemFormat;
// declared property getter: - (id)genericPasswordQuery;
// declared property getter: - (id)keychainItemData;
- (id)objectForKey:(id)key;
- (void)resetKeychainItem;
- (id)secItemFormatToDictionary:(id)dictionary;
// declared property setter: - (void)setGenericPasswordQuery:(id)query;
// declared property setter: - (void)setKeychainItemData:(id)data;
- (void)setObject:(id)object forKey:(id)key;
- (void)writeToKeychain;
@end

